fareofficelib: FOUnitTest Class Reference
FOUnitTest Class Reference
[FOUnitTest]
Will be used to gather a group of foUnitTestBase inherited classes.
Public Member Functions
FOUnitTest ($testCaseRoot_)
Constructor.
writeTestSuiteGui ()
Write the test suite GUI.
getVersion ()
Return version number of FOUnitTest.
getOnlyReportFailes ()
If true, the GUI should only report failes.
getReportFailDetails ()
If true, the GUI should report more details on failed tests.
getCurrentTestCase ()
The test case that should be executed.
getNumOfTestCases ()
Total number of test case classes/files.
getTestCaseFiles ()
Get all test case classes/files.
Private Member Functions
_retriveURLArguments ()
Get arguments from the URL, set default values if not used on url.
_initializeSkin ()
Create an object instance for the GUI Skin.
_runAllTests ()
Will run all unit tests.
_runTest ($testCaseNumber_)
Will run one test in the $this->_testCaseFilesArr specified by the $testCaseNumber_.
_doRetriveAllTestCases ()
Will retrive all the test case classes in the $this->_testCaseRoot directory.
_fillWithFilesFromDir (&$files_InOut, $path_, $addFiles_=FALSE)
Fill $files_InOut with all .php files in the $path including subdirectories.
_begin ()
Will write a webpage header for the test.
_end ()
Will write a webpage footer for the test.
_writeGuiResult (&$testResult_)
Will write a html result out from a UnitTest result.
Private Attributes
$_versionNumber = "0.3"
Version number of FOUnitTest.
$_skin
Choosen skin class used by the GUI.
$_skinObj
Instance of skin object.
$_testCaseRoot
Root in which all testcases are located.
$_testCaseFilesArr
Array with all test case classes.
$_numOfTestCases
Total number of test case classes/files.
$_currentTestCase
The number of the current test case choosen with the gui navigator.
$_bOnlyReportFailes
Will only report failed tests.
$_bReportFailDetails
Will report a detailed result for failed tests.
$_bRunAllTests
Run all tests.
Detailed Description
Will be used to gather a group of foUnitTestBase inherited classes.
These can be executed in a batch, or be viewed one by one in the integrated GUI.
 include_once('FareOfficeLib/FareOfficeLib.php');
 $testSuite = &new foUnitTest('./');
 $testSuite->writeTestSuiteGui();
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 20 of file FOUnitTest.class.php.
Member Function Documentation
FOUnitTest::_begin () [private]
Will write a webpage header for the test.
Definition at line 254 of file FOUnitTest.class.php.
Referenced by writeTestSuiteGui().
  {
    $this->_skinObj->begin();
  }
FOUnitTest::_doRetriveAllTestCases () [private]
Will retrive all the test case classes in the $this->_testCaseRoot directory.
Definition at line 199 of file FOUnitTest.class.php.
References _fillWithFilesFromDir().
Referenced by writeTestSuiteGui().
  {
    $files = array();
    $this->_fillWithFilesFromDir($files, $this->_testCaseRoot);
    if (!empty($files))
    {
      asort($files);
      $testCase = count($this->_testCaseFilesArr);
      foreach($files as $file)
      {
        $testCase++;
        $pathParts = pathinfo($file);
        $this->_testCaseFilesArr[$testCase] = array
        (
          'package' => $pathParts['dirname'],
          'path' => $file,
          'class_name' => $pathParts['filename']
        );
        $this->_numOfTestCases++;
      }
    }
  }
FOUnitTest::_end () [private]
Will write a webpage footer for the test.
Definition at line 262 of file FOUnitTest.class.php.
Referenced by writeTestSuiteGui().
  {
    $this->_skinObj->end();
  }
FOUnitTest::_fillWithFilesFromDir (&$ files_InOut, $ path_, $ addFiles_ = FALSE) [private]
Fill $files_InOut with all .php files in the $path including subdirectories.
Definition at line 228 of file FOUnitTest.class.php.
Referenced by _doRetriveAllTestCases().
  {
    if (is_dir($path_))
    {
      $result = dir($path_);
      while($entry = $result->read())
      {
        if (is_file($path_.$entry) && $addFiles_)
        {
          if (strtolower(substr($entry,-4)) == '.php')
          {
            $files_InOut[] = $path_.$entry;
          }
        }
        elseif(is_dir($path_.'/'.$entry) && $entry != '.' && $entry != '..')
        {
          $this->_fillWithFilesFromDir($files_InOut, $path_ . $entry . '/', TRUE);
        }
      }
    }
  }
FOUnitTest::_initializeSkin () [private]
Create an object instance for the GUI Skin.
Definition at line 156 of file FOUnitTest.class.php.
Referenced by FOUnitTest().
  {
    $this->_skin = 'Standard';
    include('Skins/'.$this->_skin.'.class.php');
    $this->_skinObj = & new $this->_skin;
    $this->_skinObj->setParent($this);
  }
FOUnitTest::_retriveURLArguments () [private]
Get arguments from the URL, set default values if not used on url.
Definition at line 112 of file FOUnitTest.class.php.
Referenced by FOUnitTest().
  {
    // Default will be false
    if ($_GET['formOnlyReportFailes'] == '1')
    {
      $this->_bOnlyReportFailes = true;
    }
    else
    {
      $this->_bOnlyReportFailes = false;
    }
    // Default will be true
    if ($_GET['formEchoDetails'] == '1' || !array_key_exists('formEchoDetails', $_GET))
    {
      $this->_bReportFailDetails = true;
    }
    else
    {
      $this->_bReportFailDetails = false;
    }
    // Default will be false
    if ($_GET['formRunAllTests'] == '1')
    {
      $this->_bRunAllTests = true;
    }
    else
    {
      $this->_bRunAllTests = false;
    }
    // Default will be 0
    $this->_currentTestCase = $_GET['formTestCase'];
    if (empty($this->_currentTestCase))
    {
      $this->_currentTestCase = 0;
    }
  }
FOUnitTest::_runAllTests () [private]
Will run all unit tests.
Definition at line 167 of file FOUnitTest.class.php.
References _runTest().
Referenced by writeTestSuiteGui().
  {
    foreach($this->_testCaseFilesArr as $key => $row)
    {
      $this->_runTest($key);
    }
  }
FOUnitTest::_runTest ($ testCaseNumber_) [private]
Will run one test in the $this->_testCaseFilesArr specified by the $testCaseNumber_.
Parameters:
$testCaseNumber_ - mixed - The number of the unit test in the unitTestFileArr
Definition at line 182 of file FOUnitTest.class.php.
References _writeGuiResult().
Referenced by _runAllTests(), and writeTestSuiteGui().
  {
    if ($testCaseNumber_ > 0)
    {
      include_once($this->_testCaseFilesArr[$testCaseNumber_]['path']);
      $obj = &new $this->_testCaseFilesArr[$testCaseNumber_]['class_name'];
      $obj->doTest();
      $this->_writeGuiResult($obj->getTestResult());
      unset($obj);
    }
  }
FOUnitTest::_writeGuiResult (&$ testResult_) [private]
Will write a html result out from a UnitTest result.
Definition at line 270 of file FOUnitTest.class.php.
Referenced by _runTest().
  {
    $this->_skinObj->writeGuiResult($testResult_);
  }
FOUnitTest::FOUnitTest ($ testCaseRoot_)
Constructor.
Parameters:
$testCaseRoot_ - mixed - The root for which all the testcases are located in. This is a file server location.
Definition at line 30 of file FOUnitTest.class.php.
References _initializeSkin(), and _retriveURLArguments().
  {
    $this->_retriveURLArguments();
    $this->_initializeSkin();
    $this->_testCaseFilesArr = array();
    $this->_testCaseRoot = $testCaseRoot_;
  }
FOUnitTest::getCurrentTestCase ()
The test case that should be executed.
If returning 0, no test case to should be executed.
Definition at line 88 of file FOUnitTest.class.php.
  {
    return $this->_currentTestCase;
  }
FOUnitTest::getNumOfTestCases ()
Total number of test case classes/files.
Definition at line 96 of file FOUnitTest.class.php.
  {
    return $this->_numOfTestCases;
  }
FOUnitTest::getOnlyReportFailes ()
If true, the GUI should only report failes.
Definition at line 70 of file FOUnitTest.class.php.
  {
    return $this->_bOnlyReportFailes;
  }
FOUnitTest::getReportFailDetails ()
If true, the GUI should report more details on failed tests.
Definition at line 78 of file FOUnitTest.class.php.
  {
    return $this->_bReportFailDetails;
  }
FOUnitTest::getTestCaseFiles ()
Get all test case classes/files.
Definition at line 104 of file FOUnitTest.class.php.
  {
    return $this->_testCaseFilesArr;
  }
FOUnitTest::getVersion ()
Return version number of FOUnitTest.
Definition at line 62 of file FOUnitTest.class.php.
  {
    return $this->_versionNumber;
  }
FOUnitTest::writeTestSuiteGui ()
Write the test suite GUI.
Definition at line 42 of file FOUnitTest.class.php.
References _begin(), _doRetriveAllTestCases(), _end(), _runAllTests(), and _runTest().
  {
    $this->_doRetriveAllTestCases();
    $this->_begin();
      if ($this->_bRunAllTests)
      {
        $this->_runAllTests();
      }
      else
      {
        $this->_runTest($this->_currentTestCase);
      }
    $this->_end();
  }
Member Data Documentation
FOUnitTest::$_bOnlyReportFailes [private]
Will only report failed tests.
Definition at line 314 of file FOUnitTest.class.php.
FOUnitTest::$_bReportFailDetails [private]
Will report a detailed result for failed tests.
Definition at line 319 of file FOUnitTest.class.php.
FOUnitTest::$_bRunAllTests [private]
Run all tests.
Definition at line 324 of file FOUnitTest.class.php.
FOUnitTest::$_currentTestCase [private]
The number of the current test case choosen with the gui navigator.
Definition at line 309 of file FOUnitTest.class.php.
FOUnitTest::$_numOfTestCases [private]
Total number of test case classes/files.
Definition at line 303 of file FOUnitTest.class.php.
FOUnitTest::$_skin [private]
Choosen skin class used by the GUI.
Definition at line 283 of file FOUnitTest.class.php.
FOUnitTest::$_skinObj [private]
Instance of skin object.
Definition at line 288 of file FOUnitTest.class.php.
FOUnitTest::$_testCaseFilesArr [private]
Array with all test case classes.
Definition at line 298 of file FOUnitTest.class.php.
FOUnitTest::$_testCaseRoot [private]
Root in which all testcases are located.
Definition at line 293 of file FOUnitTest.class.php.
FOUnitTest::$_versionNumber = "0.3" [private]
Version number of FOUnitTest.
Definition at line 278 of file FOUnitTest.class.php.
The documentation for this class was generated from the following file:
PhpInclude/FareOfficeLib/FOUnitTest/FOUnitTest.class.php