fareofficelib: unitTestSkin Class Reference
unitTestSkin Class Reference
[FOUnitTest]
The abstract base class that are used by all Unit Test Skins.
Public Member Functions
setParent (FOUnitTest $parent_)
Set the parent FOUnitTest class.
getParent ()
Get the parent FOUnitTest class.
begin ()
Write webpage header for the Unit Test Gui.
end ()
Write webpage footer for the Unit Test Gui.
writeGuiResult ($testResult)
Will write a html result from a UnitTest result.
Private Attributes
$_parent
Object handler to FOUnitTest.
Detailed Description
The abstract base class that are used by all Unit Test Skins.
The Unit Test Skin classes are responsible for all GUI output.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 10 of file UnitTestSkin.class.php.
Member Function Documentation
unitTestSkin::begin () [abstract]
Write webpage header for the Unit Test Gui.
The execution order for the webpage building are begin(); writeGuiResult(); end();
These three functions should create a full html page with html, head and body tags.
Reimplemented in standard.
unitTestSkin::end () [abstract]
Write webpage footer for the Unit Test Gui.
See also:
: begin()
Reimplemented in standard.
unitTestSkin::getParent ()
Get the parent FOUnitTest class.
Definition at line 25 of file UnitTestSkin.class.php.
Referenced by standard::_getUrlArgument(), standard::_writeFailDetails(), standard::_writeFileBrowser(), standard::_writeHtmlHead(), standard::_writeSectionLabel(), standard::_writeStatusChanger(), standard::_writeSuccededTest(), standard::_writeTestCaseName(), standard::_writeTestCaseNavigator(), and standard::begin().
  {
    return $this->_parent;
  }
unitTestSkin::setParent (FOUnitTest $ parent_)
Set the parent FOUnitTest class.
The parent information about the tests that the skin needs.
Definition at line 17 of file UnitTestSkin.class.php.
  {
    $this->_parent = $parent_;
  }
unitTestSkin::writeGuiResult ($ testResult) [abstract]
Will write a html result from a UnitTest result.
See also:
: begin()
Reimplemented in standard.
Member Data Documentation
unitTestSkin::$_parent [private]
Object handler to FOUnitTest.
Definition at line 60 of file UnitTestSkin.class.php.
The documentation for this class was generated from the following file:
PhpInclude/FareOfficeLib/FOUnitTest/Skins/UnitTestSkin.class.php