fareofficelib: Db Class Reference
Db Class Reference
[Db]
Include files.
Public Member Functions
Db (Config $config_)
executeQuery ($sql_)
Execute a database query.
getConnection ()
Get a creole database Connection.
setConfigName ($configName_)
Set database config name.
getConfigName ()
Get current config name that is used.
pushConfigName ($configName_)
Set a new datbase config name, and save the old one on a stack.
popConfigName ()
Set the last pushed config name.
Private Attributes
$_configName = 'foMaster'
The current used database config name.
$_configNameStack = array()
An array used as a stack with config names.
Detailed Description
Include files.
Functions to communicate with the database server.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 15 of file Db.class.php.
Member Function Documentation
Db::Db (Config $ config_)
Definition at line 20 of file Db.class.php.
  {
    $this->_config = $config_;
  }
Db::executeQuery ($ sql_)
Execute a database query.
Parameters:
$sql_ - string - The sql query.
Returns:
ResultSet
Definition at line 33 of file Db.class.php.
References getConnection().
  {
    $conn = $this->getConnection();
    return $conn->executeQuery($sql_);
  }
Db::getConfigName ()
Get current config name that is used.
Returns:
string
Definition at line 67 of file Db.class.php.
Referenced by getConnection().
  {
    return $this->_configName;
  }
Db::getConnection ()
Get a creole database Connection.
Returns:
Connection
Definition at line 44 of file Db.class.php.
References getConfigName().
Referenced by executeQuery().
  {
    $dsn = $this->_config->getDBDSN($this->getConfigName());
    return  Creole::getConnection($dsn);
  }
Db::popConfigName ()
Set the last pushed config name.
Definition at line 88 of file Db.class.php.
  {
    $this->_configName = array_pop($this->_configNameStack);
  }
Db::pushConfigName ($ configName_)
Set a new datbase config name, and save the old one on a stack.
Parameters:
$configName_ - string - A config name. Ie foMaster
Definition at line 78 of file Db.class.php.
References setConfigName().
  {
    array_push($this->_configNameStack, $this->_configName);
    $this->setConfigName($configName_);
  }
Db::setConfigName ($ configName_)
Set database config name.
Parameters:
$configName_ - string - A config name. Ie foMaster
Definition at line 57 of file Db.class.php.
Referenced by pushConfigName().
  {
    $this->_configName = $configName_;
  }
Member Data Documentation
Db::$_configName = 'foMaster' [private]
The current used database config name.
Definition at line 96 of file Db.class.php.
Db::$_configNameStack = array() [private]
An array used as a stack with config names.
See also:
Db::pushConfigName()
Definition at line 103 of file Db.class.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/Db/Db.class.php