fareofficelib: OCI8Connection Class Reference
OCI8Connection Class Reference
Public Member Functions
connect ($dsninfo, $flags=0)
Connect to a database and log in as the specified user.
close ()
executeQuery ($sql, $fetchmode=null)
executeUpdate ($sql)
getUpdateCount ()
Gets the number of rows affected by the data manipulation query.
applyLimit (&$sql, $offset, $limit)
Build Oracle-style query with limit or offset.
nativeError ($result=null)
Get the native Oracle Error Message as a string.
getDatabaseInfo ()
getIdGenerator ()
prepareStatement ($sql)
Oracle supports native prepared statements, but the oci_parse call is actually called by the OCI8PreparedStatement class because some additional SQL processing may be necessary (e.g.
prepareCall ($sql)
createStatement ()
Protected Member Functions
beginTrans ()
Start a database transaction.
commitTrans ()
Commit the current transaction.
rollbackTrans ()
Roll back (undo) the current transaction.
Protected Attributes
$lastStmt = null
$execMode = OCI_COMMIT_ON_SUCCESS
Detailed Description
Definition at line 37 of file OCI8Connection.php.
Member Function Documentation
OCI8Connection::applyLimit (&$ sql, $ offset, $ limit)
Build Oracle-style query with limit or offset.
If the original SQL is in variable: query then the requlting SQL looks like this:
 SELECT B.* FROM (
          SELECT A.*, rownum as TORQUE$ROWNUM FROM (
                  query
           ) A
      ) B WHERE B.TORQUE$ROWNUM > offset AND B.TORQUE$ROWNUM
     <= offset + limit
Parameters:
string &$sql the query
int $offset
int $limit
Returns:
void ($sql parameter is currently manipulated directly)
Implements Connection.
Definition at line 293 of file OCI8Connection.php.
   {
        $sql          =
      'SELECT B.* FROM (  '
      .  'SELECT A.*, rownum AS CREOLE$ROWNUM FROM (  '
      . $sql
      . '  ) A '
      .  ' ) B WHERE ';
        if ( $offset > 0 )
    {
            $sql        .= ' B.CREOLE$ROWNUM > ' . $offset;
            if ( $limit > 0 )
      {
                $sql      .= ' AND B.CREOLE$ROWNUM <= '
                  . ( $offset + $limit );
            }
        }
    else
    {
      $sql        .= ' B.CREOLE$ROWNUM <= ' . $limit;
    }
   }
OCI8Connection::beginTrans () [protected]
Start a database transaction.
Exceptions:
SQLException
Returns:
void
Reimplemented from ConnectionCommon.
Definition at line 203 of file OCI8Connection.php.
    {
        $this->execMode     = OCI_DEFAULT;
    }
OCI8Connection::close ()
See also:
Connection::disconnect()
Implements Connection.
Definition at line 126 of file OCI8Connection.php.
    {
        $ret = @oci_close( $this->dblink );
        $this->dblink = null;
        return $ret;
    }
OCI8Connection::commitTrans () [protected]
Commit the current transaction.
Exceptions:
SQLException
Returns:
void
Reimplemented from ConnectionCommon.
Definition at line 213 of file OCI8Connection.php.
References $result, and nativeError().
    {
        $result         = oci_commit( $this->dblink );
        if ( ! $result )
    {
            throw new SQLException( 'Unable to commit transaction'
        , $this->nativeError()
      );
        }
        $this->execMode     = OCI_COMMIT_ON_SUCCESS;
    }
OCI8Connection::connect ($ dsninfo, $ flags = 0)
Connect to a database and log in as the specified user.
Parameters:
array $dsn The data source hash.
int $flags Any connection flags. public
Exceptions:
SQLException
Returns:
void
Implements Connection.
Definition at line 56 of file OCI8Connection.php.
References ConnectionCommon::$flags, executeQuery(), and Creole::PERSISTENT.
    {
        if ( !extension_loaded( 'oci8' ) )
    {
            throw new SQLException( 'oci8 extension not loaded' );
        }
        $this->dsn        = $dsninfo;
        $this->flags      = $flags;
        $persistent       =
      ( $flags & Creole::PERSISTENT === Creole::PERSISTENT );
        $user         = $dsninfo[ 'username' ];
        $pw           = $dsninfo[ 'password' ];
        $hostspec       = $dsninfo[ 'hostspec' ];
        $db         = $dsninfo[ 'database' ];
        $connect_function   = ( $persistent )
                  ? 'oci_pconnect'
                  : 'oci_connect';
    $encoding = !empty($dsninfo['encoding']) ? $dsninfo['encoding'] : null;
    @ini_set( 'track_errors', true );
        if ( $db && $hostspec && $user && $pw )
  {
      $conn       = @$connect_function( $user, $pw, "//$hostspec/$db", $encoding);
  }
        elseif ( $hostspec && $user && $pw )
    {
      $conn       = @$connect_function( $user, $pw, $hostspec, $encoding );
        }
    elseif ( $user || $pw )
    {
      $conn       = @$connect_function( $user, $pw, null, $encoding );
        }
    else
    {
      $conn       = false;
        }
        @ini_restore( 'track_errors' );
        if ( $conn == false )
    {
            $error        = oci_error();
            $error        = ( is_array( $error ) )
                  ? $error[ 'message' ]
                  : null;
            throw new SQLException( 'connect failed', $error );
        }
        $this->dblink     = $conn;
        //connected ok, need to set a few environment settings
        //please note, if this is changed, the function setTimestamp and setDate in OCI8PreparedStatement.php
        //must be changed to match
        $sql = "ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'";
        $this->executeQuery($sql);
    }
OCI8Connection::createStatement ()
See also:
Connection::createStatement()
Implements Connection.
Definition at line 387 of file OCI8Connection.php.
    {
        require_once 'creole/drivers/oracle/OCI8Statement.php';
        return new OCI8Statement( $this );
    }
OCI8Connection::executeQuery ($ sql, $ fetchmode = null)
See also:
Connection::executeQuery()
Implements Connection.
Definition at line 136 of file OCI8Connection.php.
References $result, and nativeError().
Referenced by connect().
    {
        $this->lastQuery    = $sql;
        // $result = @oci_parse( $this->dblink, $sql );
        $result         = oci_parse( $this->dblink, $sql );
        if ( ! $result )
    {
            throw new SQLException( 'Unable to prepare query'
        , $this->nativeError()
        , $sql
      );
        }
        $success        = oci_execute( $result, $this->execMode );
        if ( ! $success )
    {
            throw new SQLException( 'Unable to execute query'
        , $this->nativeError( $result )
        , $sql
      );
        }
        return new OCI8ResultSet( $this, $result, $fetchmode );
    }
OCI8Connection::executeUpdate ($ sql)
See also:
Connection::simpleUpdate()
Implements Connection.
Definition at line 169 of file OCI8Connection.php.
References nativeError().
    {
        $this->lastQuery    = $sql;
        $statement        = oci_parse( $this->dblink, $sql );
        if ( ! $statement )
    {
            throw new SQLException( 'Unable to prepare update'
        , $this->nativeError()
        , $sql
      );
        }
        $success        = oci_execute( $statement, $this->execMode );
        if ( ! $success )
    {
            throw new SQLException( 'Unable to execute update'
        , $this->nativeError( $statement )
        , $sql
      );
        }
        $this->lastStmt     = $statement;
        return oci_num_rows( $statement );
    }
OCI8Connection::getDatabaseInfo ()
See also:
Connection::getDatabaseInfo()
Implements Connection.
Definition at line 344 of file OCI8Connection.php.
    {
        require_once 'creole/drivers/oracle/metadata/OCI8DatabaseInfo.php';
        return new OCI8DatabaseInfo( $this );
    }
OCI8Connection::getIdGenerator ()
See also:
Connection::getIdGenerator()
Implements Connection.
Definition at line 354 of file OCI8Connection.php.
    {
        require_once 'creole/drivers/oracle/OCI8IdGenerator.php';
        return new OCI8IdGenerator( $this );
    }
OCI8Connection::getUpdateCount ()
Gets the number of rows affected by the data manipulation query.
Returns:
int Number of rows affected by the last query.
Todo:
-cOCI8Connection Figure out whether getUpdateCount() should throw exception on error or just return 0.
Implements Connection.
Definition at line 255 of file OCI8Connection.php.
References $result, and nativeError().
    {
        if ( ! $this->lastStmt )
    {
            return 0;
        }
        $result         = oci_num_rows( $this->lastStmt );
        if ( $result === false )
    {
            throw new SQLException( 'Update count failed'
        , $this->nativeError( $this->lastStmt )
      );
        }
        return $result;
    }
OCI8Connection::nativeError ($ result = null)
Get the native Oracle Error Message as a string.
Parameters:
string $msg The Internal Error Message
mixed $errno The Oracle Error resource
Definition at line 325 of file OCI8Connection.php.
References $result.
Referenced by commitTrans(), executeQuery(), executeUpdate(), getUpdateCount(), and rollbackTrans().
  {
    if ( $result !== null )
    {
      $error        = oci_error( $result );
    }
    else
    {
      $error        = oci_error( $this->dblink );
    }
    return $error[ 'code' ] . ': ' . $error[ 'message' ];
  }
OCI8Connection::prepareCall ($ sql)
See also:
Connection::prepareCall()
Reimplemented from ConnectionCommon.
Definition at line 379 of file OCI8Connection.php.
  {
        throw new SQLException( 'Oracle driver does not yet support stored procedures using CallableStatement.' );
    }
OCI8Connection::prepareStatement ($ sql)
Oracle supports native prepared statements, but the oci_parse call is actually called by the OCI8PreparedStatement class because some additional SQL processing may be necessary (e.g.
to apply limit).
See also:
OCI8PreparedStatement::executeQuery()
OCI8PreparedStatement::executeUpdate()
Connection::prepareStatement()
Implements Connection.
Definition at line 369 of file OCI8Connection.php.
    {
        require_once 'creole/drivers/oracle/OCI8PreparedStatement.php';
        return new OCI8PreparedStatement( $this, $sql );
    }
OCI8Connection::rollbackTrans () [protected]
Roll back (undo) the current transaction.
Exceptions:
SQLException
Returns:
void
Reimplemented from ConnectionCommon.
Definition at line 233 of file OCI8Connection.php.
References $result, and nativeError().
    {
        $result         = oci_rollback( $this->dblink );
        if ( ! $result )
    {
            throw new SQLException( 'Unable to rollback transaction'
        , $this->nativeError()
      );
        }
        $this->execMode     = OCI_COMMIT_ON_SUCCESS;
    }
Member Data Documentation
OCI8Connection::$execMode = OCI_COMMIT_ON_SUCCESS [protected]
Definition at line 45 of file OCI8Connection.php.
OCI8Connection::$lastStmt = null [protected]
Definition at line 39 of file OCI8Connection.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/oracle/OCI8Connection.php