fareofficelib: UrlRequst Class Reference
UrlRequst Class Reference
[General]
Include files.
Static Public Member Functions
static set ($attributeName_, $value_)
Set a value to the URL argument.
static setDefault ($attributeName_, $value_)
Set an default value of an URL argument.
static isSetArg ($attributeName_)
Return true if the argument is present on the URL (_REQUEST).
static get ($attributeName_)
Return an argument from the URL with now validation.
static getDateTime ($attributeName_)
Return an argument from the URL and validate it to be a date or dateTime.
static getBool ($attributeName_)
Return an argument from the URL and validate it to be boolean.
static getString ($attributeName_)
Return an argument from the URL and validate it to be string.
static getInt ($attributeName_)
Return an argument from the URL and validate it to be integer.
Detailed Description
Include files.
Used to get and validate URL variables.
The variables will be retrieved from HTTP POST, HTTP GET and HTTP Cookies.
All variables are validated to prevent any kind of variable injection. All POST, GET or Cookie variables should be cleaned with the this class.
 UrlRequst::dateTime('startTime');
 echo(UrlRequst::get('startTime'));
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 25 of file UrlRequest.class.php.
Member Function Documentation
static UrlRequst::get ($ attributeName_) [static]
Return an argument from the URL with now validation.
Parameters:
$attributeName_ - string -
Returns:
mixed
Definition at line 78 of file UrlRequest.class.php.
Referenced by getBool(), getDateTime(), getInt(), and getString().
  {
    return $_REQUEST[$attributeName_];
  }
static UrlRequst::getBool ($ attributeName_) [static]
Return an argument from the URL and validate it to be boolean.
A valid boolean is case insensitive true, false, yes, no, 1 and 0.
If nothing is entered in the parameter false will be returned.
Parameters:
$attributeName_ - bool -
Definition at line 109 of file UrlRequest.class.php.
References get(), and isSetArg().
  {
    if (UrlRequst::isSetArg($attributeName_))
    {
      switch (strtolower(UrlRequst::get($attributeName_)))
      {
        case 'true':
        case 'yes':
        case '1':
          return true;
        case 'false':
        case 'no':
        case '0':
          return false;
        default:
          die('Invalid parameter for ' . $attributeName_);
      }
    }
    else
    {
      return false;
    }
  }
static UrlRequst::getDateTime ($ attributeName_) [static]
Return an argument from the URL and validate it to be a date or dateTime.
Parameters:
$attributeName_ - dateTime -
Definition at line 88 of file UrlRequest.class.php.
References get(), and isValidDate().
  {
    if (!isValidDate(UrlRequst::get($attributeName_)))
    {
      return false;
    }
    else
    {
      return UrlRequst::get($attributeName_);
    }
  }
static UrlRequst::getInt ($ attributeName_) [static]
Return an argument from the URL and validate it to be integer.
If nothing is entered in the parameter NULL will be returned.
Parameters:
$attributeName_ - string -
Definition at line 161 of file UrlRequest.class.php.
References get().
  {
    if (!ctype_digit(UrlRequst::get($attributeName_)))
    {
      return false;
    }
    else
    {
      return UrlRequst::get($attributeName_);
    }
  }
static UrlRequst::getString ($ attributeName_) [static]
Return an argument from the URL and validate it to be string.
If nothing is entered in the parameter NULL will be returned.
Parameters:
$attributeName_ - string -
Definition at line 142 of file UrlRequest.class.php.
References get(), and isSetArg().
  {
    if (UrlRequst::isSetArg($attributeName_))
    {
      return UrlRequst::get($attributeName_);
    }
    else
    {
      return null;
    }
  }
static UrlRequst::isSetArg ($ attributeName_) [static]
Return true if the argument is present on the URL (_REQUEST).
Returns:
- boolean -
Definition at line 60 of file UrlRequest.class.php.
Referenced by getBool(), getString(), and setDefault().
  {
    if (array_key_exists($attributeName_, $_REQUEST))
    {
      return true;
    }
    else
    {
      return false;
    }
  }
static UrlRequst::set ($ attributeName_, $ value_) [static]
Set a value to the URL argument.
Parameters:
$attributeName_ - string -
$value_ - string -
Definition at line 33 of file UrlRequest.class.php.
Referenced by UTUrlRequest::_testGetBool(), UTUrlRequest::_testgetInt(), and UTUrlRequest::_testGetString().
  {
    $_REQUEST[$attributeName_] = $value_;
  }
static UrlRequst::setDefault ($ attributeName_, $ value_) [static]
Set an default value of an URL argument.
If the argument is not present on the URL (_REQUEST), this default value will be returned by all getters in this class.
Parameters:
$attributeName_ - string -
$value_ - string -
Definition at line 47 of file UrlRequest.class.php.
References isSetArg().
Referenced by UTUrlRequest::_testGet(), UTUrlRequest::_testGetDateTime(), and UTUrlRequest::_testGetString().
  {
    if (!UrlRequst::isSetArg($attributeName_))
    {
      $_REQUEST[$attributeName_] = $value_;
    }
  }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/General/UrlRequest.class.php