fareofficelib: UTDb Class Reference
UTDb Class Reference
[Unit Tests - Unit tests for all classes/functions in fareofficelib.]
Unit test for all functions in Db.php.
Public Member Functions
doTest ()
Private Member Functions
_testDbClass ()
_testEscN ()
_testEscS ()
Detailed Description
Unit test for all functions in Db.php.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 8 of file UTDb.class.php.
Member Function Documentation
UTDb::_testDbClass () [private]
Definition at line 17 of file UTDb.class.php.
Referenced by doTest().
  {
    $this->setSectionLabel('Db class');
    $config = new Config();
    eval($this->needNotEmpty('$db = new Db($config)'));
    eval($this->needEmpty('$db->setConfigName("mysql")'));
    eval($this->needEqual('$db->getConfigName()', '"mysql"'));
    eval($this->needEmpty('$db->pushConfigName("dead_database")'));
    eval($this->needEqual('$db->getConfigName()', '"dead_database"'));
    eval($this->needEmpty('$db->popConfigName()'));
    eval($this->needEqual('$db->getConfigName()', '"mysql"'));
    eval($this->needNotEmpty('$conn = $db->getConnection()'));
    eval($this->needNotEmpty('$resultSet = $db->executeQuery("select \"Hey, Bishop. Do the thing with the knife. \" as col1")'));
    $resultSet->next();
    eval($this->needEqual('$resultSet->getRecordCount()', '1'));
    eval($this->needEqual('$resultSet->getString("col1")', '"Hey, Bishop. Do the thing with the knife. "'));
  }
UTDb::_testEscN () [private]
Definition at line 36 of file UTDb.class.php.
Referenced by doTest().
  {
    $this->setSectionLabel('escN');
    $emptyString = "";
    eval($this->needEqual('escN($emptyString)', '"NULL"'));
    $number23 = 23;
    eval($this->needEqual('escN($number23)', 23));
    $zeroNumber = 0;
    eval($this->needEqual('escN($zeroNumber)', 0));
  }
UTDb::_testEscS () [private]
Definition at line 50 of file UTDb.class.php.
Referenced by doTest().
  {
    $this->setSectionLabel('escS');
    $emptyString = "";
    eval($this->needEqual('escS($emptyString)', '"NULL"'));
    $notEmptyString = "Game over man";
    eval($this->needEqual('escS($notEmptyString)', "'\'Game over man\''"));
    eval($this->needEqual('escS($notEmptyString, "%", ESC_NONE)', "'\'Game over man\''"));
    eval($this->needEqual('escS($notEmptyString, "%", ESC_LAST)', "'\'Game over man%\''"));
    eval($this->needEqual('escS($notEmptyString, "%", ESC_FIRST)', "'\'%Game over man\''"));
    eval($this->needEqual('escS($notEmptyString, "%", ESC_BOTH)', "'\'%Game over man%\''"));
    $number23 = 23;
    eval($this->needEqual('escS($number23)', "'\'23\''"));
    $zeroNumber = 0;
    eval($this->needEqual('escS($zeroNumber)', "'\'0\''"));
    $zeroNumber = 0;
    eval($this->needEqual('escS($zeroNumber)', 0));
  }
UTDb::doTest ()
Definition at line 10 of file UTDb.class.php.
References _testDbClass(), _testEscN(), and _testEscS().
  {
    $this->_testDbClass();
    $this->_testEscN();
    $this->_testEscS();
  }
The documentation for this class was generated from the following file:
Static/UnitTestHtDocs/FareOfficeLib/Db/UTDb.class.php