fareofficelib: ODBCTableInfo Class Reference
ODBCTableInfo Class Reference
Protected Member Functions
initColumns ()
initPrimaryKey ()
initIndexes ()
initForeignKeys ()
Detailed Description
Definition at line 31 of file ODBCTableInfo.php.
Member Function Documentation
ODBCTableInfo::initColumns () [protected]
See also:
TableInfo::initColumns()
Reimplemented from TableInfo.
Definition at line 36 of file ODBCTableInfo.php.
References TableInfo::$name, $result, ODBCTypes::getType(), and ODBCTypes::loadTypeMap().
Referenced by initForeignKeys(), and initPrimaryKey().
    {
        include_once 'creole/metadata/ColumnInfo.php';
        include_once 'creole/drivers/odbc/ODBCTypes.php';
        ODBCTypes::loadTypeMap($this->conn);
        $result = @odbc_columns($this->conn->getResource(), $this->dbname, '', $this->name);
        if (!$result)
            throw new SQLException('Could not get column names', $this->conn->nativeError());
        while (odbc_fetch_row($result))
        {
            $name = odbc_result($result, 'COLUMN_NAME');
            $type = odbc_result($result, 'TYPE_NAME');
            $length = odbc_result($result, 'LENGTH');
            $is_nullable = odbc_result($result, 'NULLABLE');
            $default = '';
            $precision = odbc_result($result, 'PRECISION');
            $scale = odbc_result($result, 'SCALE');
            $this->columns[$name] = new ColumnInfo($this, $name, ODBCTypes::getType($type), $type, $length, $precision, $scale, $is_nullable, $default);
        }
        @odbc_free_result($result);
        $this->colsLoaded = true;
    }
ODBCTableInfo::initForeignKeys () [protected]
See also:
TableInfo::initForeignKeys()
Reimplemented from TableInfo.
Definition at line 103 of file ODBCTableInfo.php.
References TableInfo::$name, $result, and initColumns().
    {
        // columns have to be loaded first
        if (!$this->colsLoaded) $this->initColumns();
        $result = @odbc_foreignkeys($this->conn->getResource(), '', '', '', $this->dbname, '', $this->name);
        while (odbc_fetch_row($result))
        {
            $name = odbc_result($result, 'COLUMN_NAME');
            $ftbl = odbc_result($result, 'FKTABLE_NAME');
            $fcol = odbc_result($result, 'FKCOLUMN_NAME');
            if (!isset($this->foreignKeys[$name]))
            {
                $this->foreignKeys[$name] = new ForeignKeyInfo($name);
                if (($foreignTable = $this->database->getTable($ftbl)) === null)
                {
                    $foreignTable = new TableInfo($ltbl);
                    $this->database->addTable($foreignTable);
                }
                if (($foreignCol = $foreignTable->getColumn($name)) === null)
                {
                    $foreignCol = new ColumnInfo($foreignTable, $name);
                    $foreignTable->addColumn($foreignCol);
                }
                $this->foreignKeys[$name]->addReference($this->columns[$name], $foreignCol);
            }
        }
        @odbc_free_result($result);
        $this->fksLoaded = true;
    }
ODBCTableInfo::initIndexes () [protected]
See also:
TableInfo::initIndexes()
Reimplemented from TableInfo.
Definition at line 95 of file ODBCTableInfo.php.
    {
        // Not sure if this can be implemented in a driver-independent way.
    }
ODBCTableInfo::initPrimaryKey () [protected]
See also:
TableInfo::initPrimaryKey()
Reimplemented from TableInfo.
Definition at line 68 of file ODBCTableInfo.php.
References TableInfo::$name, $result, and initColumns().
    {
        include_once 'creole/metadata/PrimaryKeyInfo.php';
        // columns have to be loaded first
        if (!$this->colsLoaded) $this->initColumns();
        $result = @odbc_primarykeys($this->conn->getResource(), $this->dbname, '', $this->name);
        while (odbc_fetch_row($result))
        {
            $name = odbc_result($result, 'COLUMN_NAME');
            if (!isset($this->primaryKey))
                $this->primaryKey = new PrimaryKeyInfo($name);
            $this->primaryKey->addColumn($this->columns[$name]);
        }
        @odbc_free_result($result);
        $this->pkLoaded = true;
    }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/metadata/ODBCTableInfo.php