fareofficelib: PgSQLResultSetIterator Class Reference
PgSQLResultSetIterator Class Reference
Public Member Functions
__construct (PgSQLResultSet $rs)
Construct the iterator.
rewind ()
This method actually has no effect, since we do not rewind ResultSet for iteration.
valid ()
key ()
Returns the cursor position.
current ()
Returns the row (assoc array) at current cursor pos.
next ()
Advances internal cursor pos.
seek ($index)
Sets cursor to specific value.
count ()
Private Attributes
$result
$pos = 0
$fetchmode
$row_count
$rs
Detailed Description
Definition at line 31 of file PgSQLResultSetIterator.php.
Constructor & Destructor Documentation
PgSQLResultSetIterator::__construct (PgSQLResultSet $ rs)
Construct the iterator.
Parameters:
PgSQLResultSet $rs
Definition at line 43 of file PgSQLResultSetIterator.php.
References ResultSetCommon::getFetchmode(), PgSQLResultSet::getRecordCount(), and ResultSetCommon::getResource().
    {
        $this->result = $rs->getResource();
        $this->fetchmode = $rs->getFetchmode();
    $this->row_count = $rs->getRecordCount();
    $this->rs = $rs; // This is to address reference count bug: http://creole.phpdb.org/trac/ticket/6
    }
Member Function Documentation
PgSQLResultSetIterator::count ()
Definition at line 106 of file PgSQLResultSetIterator.php.
                       {
    return $this->row_count;
    }
PgSQLResultSetIterator::current ()
Returns the row (assoc array) at current cursor pos.
Returns:
array
Definition at line 79 of file PgSQLResultSetIterator.php.
    {
       return pg_fetch_array($this->result, $this->pos, $this->fetchmode);
    }
PgSQLResultSetIterator::key ()
Returns the cursor position.
Note that this will not necessarily be 1 for the first row, since no rewind is performed at beginning of iteration.
Returns:
int
Definition at line 70 of file PgSQLResultSetIterator.php.
    {
        return $this->pos;
    }
PgSQLResultSetIterator::next ()
Advances internal cursor pos.
Definition at line 87 of file PgSQLResultSetIterator.php.
    {
        $this->pos++;
    }
PgSQLResultSetIterator::rewind ()
This method actually has no effect, since we do not rewind ResultSet for iteration.
Definition at line 54 of file PgSQLResultSetIterator.php.
    {
        $this->pos = 0;
    }
PgSQLResultSetIterator::seek ($ index)
Sets cursor to specific value.
Definition at line 95 of file PgSQLResultSetIterator.php.
    {
      if ( ! is_int ( $index ) ) {
      throw new InvalidArgumentException ( 'Invalid arguement to seek' );
    }
    if ( $index < 0 || $index > $this->row_count ) {
      throw new OutOfBoundsException ( 'Invalid seek position' );
    }
    $this->pos = $index;
    }
PgSQLResultSetIterator::valid ()
Definition at line 59 of file PgSQLResultSetIterator.php.
    {
    return ( $this->pos < $this->row_count );
    }
Member Data Documentation
PgSQLResultSetIterator::$fetchmode [private]
Definition at line 35 of file PgSQLResultSetIterator.php.
PgSQLResultSetIterator::$pos = 0 [private]
Definition at line 34 of file PgSQLResultSetIterator.php.
PgSQLResultSetIterator::$result [private]
Definition at line 33 of file PgSQLResultSetIterator.php.
PgSQLResultSetIterator::$row_count [private]
Definition at line 36 of file PgSQLResultSetIterator.php.
PgSQLResultSetIterator::$rs [private]
Definition at line 37 of file PgSQLResultSetIterator.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/pgsql/PgSQLResultSetIterator.php