fareofficelib: PhpCronTab Class Reference
PhpCronTab Class Reference
[General]
Scheduling functionality similiar to the unix crontab.
Public Member Functions
__construct ()
Constructor.
addUnixFormat ($defined_)
Add a new time period when isTimeExecuted should be return true.
addUnixFormatEx ($minute_, $hour_, $dayOfMonth_, $month_, $dayOfWeek_)
See addUnixFormat.
clearUnixFormat ()
Clear all added schedules.
isTimeToExecute ()
Check if it's time to execute the program.
setCurrentTime ($time_)
Set the current time measured in the number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT).
getCurrentTime ()
Returns the current time measured in the number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT).
Public Attributes
const EVERY_MINUTE = '*/1 * * * *'
Parameters for PhpCronTab::addUnixFormat().
const EVERY_5_MINUTE = '*/5 * * * *'
const EVERY_15_MINUTE = '*/15 * * * *'
const EVERY_30_MINUTE = '*/30 * * * *'
const EVERY_HOUR = '* */1 * * *'
const EVERY_DAY = '0 21 * * *'
const EVERY_WEEK = '0 22 * * 1'
Private Member Functions
_getCurrentTimeArr ()
Return array with current time.
_checkClock ($currentClock_, $testClock_)
Check the hour or minute field for crontab syntax.
_checkDayOfMonth ($dayOfMonth_, $scheduleDayOfMonth_)
Check if current day of month matches with the scheduled day of month.
_checkMonth ($currentMonth_, $scheduleDMonth_)
Check if current month matches with scheduled month.
_checkDayOfWeek ($dayOfWeek_, $scheduledDayOfWeek_)
Check if current day of week matches with the scheduled day of week.
Private Attributes
$scheduleList
List of scheduled times.
Detailed Description
Scheduling functionality similiar to the unix crontab.
This class is used to set a time period when something should be executed. The code needs to be combined with other code that will trigger the PhpCronTab::isTimeToExecute() atleast once a minute. For example in unix crontab.
The following example will do database check everyday day 21:00, and optimize database once a week.
/var/www/batches/index.php
 include_once('FareOfficeLib/FareOfficeLib.php');
 $phpCronTab = new PhpCronTab;
 $phpCronTab->addUnixFormat(EVERY_DAY);
 if ($phpCronTab->isTimeToExecute())
 {
   // Check table user fast;
 }
 $phpCronTab->clearUnixFormat()
 $phpCronTab->addUnixFormat(EVERY_WEEK);
 if ($phpCronTab->isTimeToExecute())
 {
   // optimize table user;
 }
Then add this to /etc/crontab
 0 21 * * * root /usr/bin/php /var/www/batches/index.php
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 39 of file PhpCronTab.class.php.
Constructor & Destructor Documentation
PhpCronTab::__construct ()
Constructor.
Definition at line 55 of file PhpCronTab.class.php.
References setCurrentTime().
  {
    $this->scheduleList = array();
    $this->setCurrentTime(time());
  }
Member Function Documentation
PhpCronTab::_checkClock ($ currentClock_, $ testClock_) [private]
Check the hour or minute field for crontab syntax.
Parameters:
$currentClock_ - string - Either the current hour or current minute. Should not begin with 0.
$testClock_ - string - The hour or minute when the execution should start.
Returns:
- bool - true if execution should be done.
Definition at line 239 of file PhpCronTab.class.php.
Referenced by isTimeToExecute().
  {
    $testClockArr = array();
    // * always execute this.
    if ($testClock_ == '*')
    {
      return true;
    }
    // If same value
    elseif ($currentClock_ == $testClock_)
    {
      return true;
    }
    // Ranged values, 1-10 means all values from 1 to 10.
    elseif (strpos($testClock_, '-') !== false)
    {
      $numberRange = explode('-', $testClock_);
      if
      (
        count($numberRange) == 2 &&
        $currentClock_ >= $numberRange[0] &&
        $currentClock_ <= $numberRange[1]
      )
      {
        return true;
      }
    }
    // Will rebuild to real values in an array.
    // */3 will be 0,3,6,9,12,15,18,21 etc.
    elseif (strpos($testClock_, '/') !== false)
    {
      $skipNumber = explode('/', $testClock_);
      if ($skipNumber[0] == '*')
      {
        for($i = 0; $i < 60; $i+=$skipNumber[1])
        {
          $testClockArr[$i] = true;
        }
      }
    }
    // 1,3,7,9 will be expanded to an array.
    elseif (strpos($testClock_, ',') !== false)
    {
      $testClockArr = explode(',', $testClock_);
      $testClockArr = array_flip($testClockArr);
    }
    //
    if (!empty($testClockArr) && array_key_exists($currentClock_,  $testClockArr))
    {
      return true;
    }
    return false;
  }
PhpCronTab::_checkDayOfMonth ($ dayOfMonth_, $ scheduleDayOfMonth_) [private]
Check if current day of month matches with the scheduled day of month.
Parameters:
$dayOfMonth_ - string - Current day of month, 0-6, 0 is sunday.
$scheduleDayOfMonth_ - string - The scheduled day of month.
Returns:
- bool - true if execution should be done.
Definition at line 311 of file PhpCronTab.class.php.
  {
    if ('*' == $scheduleDayOfMonth_ || $dayOfMonth_ == $scheduleDayOfMonth_)
    {
      return true;
    }
    else
    {
      return false;
    }
  }
PhpCronTab::_checkDayOfWeek ($ dayOfWeek_, $ scheduledDayOfWeek_) [private]
Check if current day of week matches with the scheduled day of week.
Parameters:
$dayOfWeek_ - string - Current day of week, 0-6, 0 is sunday.
$scheduledDayOfWeek_ - string - The scheduled day of week.
Returns:
- bool - true if execution should be done.
Definition at line 357 of file PhpCronTab.class.php.
  {
    if ('*' == $scheduledDayOfWeek_ || $dayOfWeek_ == $scheduledDayOfWeek_)
    {
      return true;
    }
    else
    {
      return false;
    }
  }
PhpCronTab::_checkMonth ($ currentMonth_, $ scheduleDMonth_) [private]
Check if current month matches with scheduled month.
Parameters:
$currentMonth_ - string - Current month
$scheduleDMonth_ - string - The scheduled month.
Returns:
- bool - true if execution should be done.
Definition at line 334 of file PhpCronTab.class.php.
  {
    if ('*' == $scheduleDMonth_ || $currentMonth_ == $scheduleDMonth_)
    {
      return true;
    }
    else
    {
      return false;
    }
  }
PhpCronTab::_getCurrentTimeArr () [private]
Return array with current time.
Example return array.
 array
 (
   'minute' => 23,
   'hour'=> 14,
   'day_of_month' = 2,
   'month' => 2,
   'day_of_week = 5'
 );
Current time without leading zeroes and zero based. Hour is between 0-23 for example.
Definition at line 215 of file PhpCronTab.class.php.
References getCurrentTime().
Referenced by isTimeToExecute().
  {
    return array
    (
      'minute'        => ltrim(date('i', $this->getCurrentTime()), '0'),
      'hour'          => ltrim(date('G', $this->getCurrentTime()), '0'),
      'day_of_month'  => ltrim(date('d', $this->getCurrentTime()), '0'),
      'month'         => ltrim(date('n', $this->getCurrentTime()), '0'),
      'day_of_week'   => ltrim(date('w', $this->getCurrentTime()), '0')
    );
  }
PhpCronTab::addUnixFormat ($ defined_)
Add a new time period when isTimeExecuted should be return true.
Each add follows a particular format as a series of fields, separated by spaces and/or tabs. Each field can have a single value or a series of values.
OPERATORS There are several ways of specifying multiple date/time values in a field:
The comma (',') operator specifies a list of values, for example: "1,3,4,7,8"
The dash ('-') operator specifies a range of values, for example: "1-6", which is equivalent to "1,2,3,4,5,6"
The asterisk ('*') operator specifies all possible values for a field. For example, an asterisk in the hour time field would be equivalent to 'every hour'.
There is also an operator which some extended versions of cron support, the slash ('/') operator, which can be used to skip a given number of values. For example, "* /3" in the hour time field is equivalent to "0,3,6,9,12,15,18,21"; "*" specifies 'every hour' but the "/3" means that only the first, fourth, seventh... and such values given by "*" are used.
Fields +---------------- minute (0 - 59) | +------------- hour (0 - 23) | | +---------- day of month (1 - 31) | | | +------- month (1 - 12) | | | | +---- day of week (0 - 7) (Sunday=0 or 7) | | | | | * * * * *
Each of the patterns from the five fields may be either * (an asterisk), meaning all legal values, or a list of elements separated by commas.
For "day of the week" (field 5), 0 are considered Sunday.
Counterintuitively, if both "day of month" (field 3) and "day of week" (field 5) are present on the same line, then the command is executed when either is true.
Parameters:
$defined_ See the function comment.
Definition at line 110 of file PhpCronTab.class.php.
References addUnixFormatEx().
  {
    $arr = explode(' ', $defined_);
    // @todo
    //assertLog(count($arr) == 5, EL_LEVEL_3, ECAT_DIAGNOSTIC, 'Not the right number of arguments: ' . count($arr) . ' ' . $defined_);
    $this->addUnixFormatEx($arr[0], $arr[1], $arr[2], $arr[3], $arr[4]);
  }
PhpCronTab::addUnixFormatEx ($ minute_, $ hour_, $ dayOfMonth_, $ month_, $ dayOfWeek_)
See addUnixFormat.
Definition at line 123 of file PhpCronTab.class.php.
Referenced by addUnixFormat().
  {
    $this->scheduleList[] = array
    (
      'minute'        => ltrim($minute_, '0'),
      'hour'          => ltrim($hour_, '0'),
      'day_of_month'  => ltrim($dayOfMonth_, '0'),
      'month'         => ltrim($month_, '0'),
      'day_of_week'   => ltrim($dayOfWeek_, '0')
    );
  }
PhpCronTab::clearUnixFormat ()
Clear all added schedules.
Definition at line 138 of file PhpCronTab.class.php.
  {
    $this->scheduleList = array();
  }
PhpCronTab::getCurrentTime ()
Returns the current time measured in the number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT).
Definition at line 192 of file PhpCronTab.class.php.
Referenced by _getCurrentTimeArr().
  {
    return $this->_currentTime;
  }
PhpCronTab::isTimeToExecute ()
Check if it's time to execute the program.
Returns:
bool
Definition at line 148 of file PhpCronTab.class.php.
References _checkClock(), and _getCurrentTimeArr().
  {
    if (!empty($this->scheduleList))
    {
      $currentTime = $this->_getCurrentTimeArr();
      foreach ($this->scheduleList as $schedule)
      {
        if
        (
          $this->_checkClock($currentTime['minute'], $schedule['minute']) &&
          $this->_checkClock($currentTime['hour'], $schedule['hour']) &&
          $this->_checkClock($currentTime['day_of_month'], $schedule['day_of_month']) &&
          $this->_checkClock($currentTime['month'], $schedule['month']) &&
          $this->_checkClock($currentTime['day_of_week'], $schedule['day_of_week'])
        )
        {
          return true;
        }
      }
      return false;
    }
    else
    {
      // If no sceduleList are configured, always execute
      return true;
    }
  }
PhpCronTab::setCurrentTime ($ time_)
Set the current time measured in the number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT).
Parameters:
$time_
Definition at line 183 of file PhpCronTab.class.php.
Referenced by __construct().
  {
    $this->_currentTime = $time_;
  }
Member Data Documentation
PhpCronTab::$scheduleList [private]
List of scheduled times.
Definition at line 372 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_15_MINUTE = '*/15 * * * *'
Definition at line 46 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_30_MINUTE = '*/30 * * * *'
Definition at line 47 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_5_MINUTE = '*/5 * * * *'
Definition at line 45 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_DAY = '0 21 * * *'
Definition at line 49 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_HOUR = '* */1 * * *'
Definition at line 48 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_MINUTE = '*/1 * * * *'
Parameters for PhpCronTab::addUnixFormat().
Definition at line 44 of file PhpCronTab.class.php.
const PhpCronTab::EVERY_WEEK = '0 22 * * 1'
Definition at line 50 of file PhpCronTab.class.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/General/PhpCronTab.class.php