fareofficelib: UTUrlRequest Class Reference
UTUrlRequest Class Reference
[Unit Tests - Unit tests for all classes/functions in fareofficelib.]
Unit test for all functions in UrlRequst.class.php.
Public Member Functions
doTest ()
Private Member Functions
_testGet ()
_testGetDateTime ()
_testGetBool ()
_testGetString ()
_testgetInt ()
Detailed Description
Unit test for all functions in UrlRequst.class.php.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 8 of file UTUrlRequest.class.php.
Member Function Documentation
UTUrlRequest::_testGet () [private]
Definition at line 19 of file UTUrlRequest.class.php.
References UrlRequst::setDefault().
Referenced by doTest().
  {
    $this->setSectionLabel('get');
    eval($this->needFalse('UrlRequst::get("start")'));
    eval($this->needFalse('UrlRequst::isSetArg("start")'));
    UrlRequst::setDefault('start', '2001-01-01');
    eval($this->needTrue('UrlRequst::isSetArg("start")'));
    eval($this->needEqual('UrlRequst::get("start")', '"2001-01-01"'));
    eval($this->needDiff('UrlRequst::get("start")', '"2s001-01-01"'));
  }
UTUrlRequest::_testGetBool () [private]
Definition at line 44 of file UTUrlRequest.class.php.
References UrlRequst::set().
Referenced by doTest().
  {
    $this->setSectionLabel('getBool');
    eval($this->needFalse('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', 'false');
    eval($this->needFalse('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', 'nO');
    eval($this->needFalse('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', '0');
    eval($this->needFalse('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', 'FalSe');
    eval($this->needFalse('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', 'true');
    eval($this->needTrue('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', 'yes');
    eval($this->needTrue('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', '1');
    eval($this->needTrue('UrlRequst::getBool("enable")'));
    UrlRequst::set('enable', 'TruE');
    eval($this->needTrue('UrlRequst::getBool("enable")'));
  }
UTUrlRequest::_testGetDateTime () [private]
Definition at line 32 of file UTUrlRequest.class.php.
References UrlRequst::setDefault().
Referenced by doTest().
  {
    $this->setSectionLabel('getDateTime');
    eval($this->needFalse('UrlRequst::getDateTime("startTime")'));
    eval($this->needFalse('UrlRequst::isSetArg("startTime")'));
    UrlRequst::setDefault('startTime', '2001-01-01');
    eval($this->needTrue('UrlRequst::isSetArg("startTime")'));
    eval($this->needDate('UrlRequst::getDateTime("startTime")'));
  }
UTUrlRequest::_testgetInt () [private]
Definition at line 91 of file UTUrlRequest.class.php.
References UrlRequst::set().
Referenced by doTest().
  {
    $this->setSectionLabel('getInt');
    eval($this->needFalse('UrlRequst::getInt("number")'));
    UrlRequst::set('number', 'asdfsdf');
    eval($this->needFalse('UrlRequst::getInt("number")'));
    UrlRequst::set('number', '123');
    eval($this->needEqual('UrlRequst::getInt("number")', '"123"'));
    UrlRequst::set('number', '123');
    eval($this->needEqual('UrlRequst::getInt("number")', '123'));
    UrlRequst::set('number', '123,34');
    eval($this->needFalse('UrlRequst::getInt("number")', '123'));
  }
UTUrlRequest::_testGetString () [private]
Definition at line 75 of file UTUrlRequest.class.php.
References UrlRequst::set(), and UrlRequst::setDefault().
Referenced by doTest().
  {
    $this->setSectionLabel('getString');
    eval($this->needEmpty('UrlRequst::getString("string")', '""'));
    UrlRequst::setDefault('string', 'That\'s it man, game over man, game over!');
    eval($this->needEqual('UrlRequst::getString("string")', '"That\'s it man, game over man, game over!"'));
    UrlRequst::setDefault('string', 'What the fuck are we gonna do now? What are we gonna do?');
    eval($this->needEqual('UrlRequst::getString("string")', '"That\'s it man, game over man, game over!"'));
    UrlRequst::set('string', 'Maybe we could build a fire, sing a couple of songs, huh?');
    eval($this->needEqual('UrlRequst::getString("string")', '"Maybe we could build a fire, sing a couple of songs, huh?"'));
  }
UTUrlRequest::doTest ()
Definition at line 10 of file UTUrlRequest.class.php.
References _testGet(), _testGetBool(), _testGetDateTime(), _testgetInt(), and _testGetString().
  {
    $this->_testGet();
    $this->_testGetDateTime();
    $this->_testGetBool();
    $this->_testGetString();
    $this->_testgetInt();
  }
The documentation for this class was generated from the following file:
Static/UnitTestHtDocs/FareOfficeLib/General/UTUrlRequest.class.php