fareofficelib: OCI8PreparedStatement Class Reference
OCI8PreparedStatement Class Reference
Public Member Functions
close ()
If the statement is set, free it.
executeQuery ($p1=null, $fetchmode=null)
Executes the SQL query in this PreparedStatement object and returns the resultset generated by the query.
executeUpdate ($params=null)
Executes the SQL INSERT, UPDATE, or DELETE statement in this PreparedStatement object.
setBlob ($paramIndex, $blob)
setClob ($paramIndex, $clob)
setString ($paramIndex, $value)
Since bind variables in oracle have no special characters, this setString method differs from the common one in that it does not single quote strings.
setTimestamp ($paramIndex, $value)
Copied this function from common/PreparedStatement.php and modified to work with Oracle Please note the format used with date() matches that of NLS_DATE_FORMAT set in OCI8Connection.php.
setDate ($paramIndex, $value)
Please note the format used with date() matches that of NLS_DATE_FORMAT set in OCI8Connection.php.
setNull ($paramIndex)
Protected Member Functions
escape ($str)
Nothing to do - since oci_bind is used to insert data, no escaping is needed.
Private Member Functions
bindVars ($stmt)
Performs the actual binding of variables using oci_bind_by_name().
sqlToOracleBindVars ($sql)
Convert a Propel SQL into Oracle SQL.
setColumnArray ()
In order to send lob data (clob/blob) to the Oracle data base, the sqlToOracleBindVars function needs to have an ordered list of the columns being addressed in the sql statement.
Private Attributes
$lobDescriptors = array()
$lobs = array()
$columns = array()
Detailed Description
Definition at line 33 of file OCI8PreparedStatement.php.
Member Function Documentation
OCI8PreparedStatement::bindVars ($ stmt) [private]
Performs the actual binding of variables using oci_bind_by_name().
This may seem like useless overhead, but the reason why calls to oci_bind_by_name() are not performed in the set*() methods is that it is possible that the SQL will need to be modified -- e.g. by a setLimit() call -- and re-prepared. We cannot assume that the statement has been prepared when the set*() calls are invoked. This also means, therefore, that the set*() calls will not throw exceptions; all exceptions will be thrown when the statement is prepared.
Parameters:
resource $stmt The statement result of oci_parse to use for binding.
Returns:
void
Definition at line 197 of file OCI8PreparedStatement.php.
Referenced by executeQuery(), and executeUpdate().
    {
        foreach ($this->boundInVars as $idx => $val) {
            $idxName = ":var" . $idx;
            if (!oci_bind_by_name($stmt, $idxName, $this->boundInVars[$idx], -1)) {
                throw new SQLException("Erorr binding value to placeholder " . $idx);
            }
        } // foreach
        foreach ($this->lobs as $idx => $val) {
            $idxName = ":var" . $idx;
            if (class_exists('Blob') && $val instanceof Blob){
                if (!oci_bind_by_name($stmt, $idxName, $this->lobDescriptors[$idx], -1, OCI_B_BLOB))
                    throw new SQLException("Erorr binding blob to placeholder " . $idx);
            } elseif (class_exists('Clob') && $val instanceof Clob){
                if (!oci_bind_by_name($stmt, $idxName, $this->lobDescriptors[$idx], -1, OCI_B_CLOB))
                    throw new SQLException("Erorr binding clob to placeholder " . $idx);
            }
        } // foreach
    }
OCI8PreparedStatement::close ()
If the statement is set, free it.
See also:
PreparedStatement::close()
Reimplemented from PreparedStatementCommon.
Definition at line 62 of file OCI8PreparedStatement.php.
    {
         if (isset($this->stmt))
              @oci_free_statement($this->stmt);
    }
OCI8PreparedStatement::escape ($ str) [protected]
Nothing to do - since oci_bind is used to insert data, no escaping is needed.
Parameters:
string $str
Returns:
string
Reimplemented from PreparedStatementCommon.
Definition at line 73 of file OCI8PreparedStatement.php.
    {
        return $str;
    }
OCI8PreparedStatement::executeQuery ($ p1 = null, $ fetchmode = null)
Executes the SQL query in this PreparedStatement object and returns the resultset generated by the query.
Parameters:
mixed $p1 Either (array) Parameters that will be set using PreparedStatement::set() before query is executed or (int) fetchmode.
int $fetchmode The mode to use when fetching the results (e.g. ResultSet::FETCHMODE_NUM, ResultSet::FETCHMODE_ASSOC).
Returns:
ResultSet
Exceptions:
SQLException if a database access error occurs.
Reimplemented from PreparedStatementCommon.
Definition at line 85 of file OCI8PreparedStatement.php.
References $result, PreparedStatementCommon::$sql, bindVars(), and sqlToOracleBindVars().
    {
        $params = null;
        if ($fetchmode !== null) {
            $params = $p1;
        } elseif ($p1 !== null) {
            if (is_array($p1)) $params = $p1;
            else $fetchmode = $p1;
        }
        if ($params) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        $this->updateCount = null; // reset
        $sql = $this->sqlToOracleBindVars($this->sql);
        if ($this->limit > 0 || $this->offset > 0) {
            $this->conn->applyLimit($sql, $this->offset, $this->limit);
        }
        $result = oci_parse($this->conn->getResource(), $sql);
        if (!$result) {
            throw new SQLException("Unable to prepare query", $this->conn->nativeError(), $this->sqlToOracleBindVars($this->sql));
        }
        // bind all variables
        $this->bindVars($result);
        $success = oci_execute($result, OCI_DEFAULT);
        if (!$success) {
            throw new SQLException("Unable to execute query", $this->conn->nativeError($result), $this->sqlToOracleBindVars($this->sql));
        }
        $this->resultSet = new OCI8ResultSet($this->conn, $result, $fetchmode);
        return $this->resultSet;
    }
OCI8PreparedStatement::executeUpdate ($ params = null)
Executes the SQL INSERT, UPDATE, or DELETE statement in this PreparedStatement object.
Parameters:
array $params Parameters that will be set using PreparedStatement::set() before query is executed.
Returns:
int Number of affected rows (or 0 for drivers that return nothing).
Exceptions:
SQLException if a database access error occurs.
Reimplemented from PreparedStatementCommon.
Definition at line 134 of file OCI8PreparedStatement.php.
References bindVars(), and sqlToOracleBindVars().
    {
        if ($params) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        if($this->resultSet) $this->resultSet->close();
        $this->resultSet = null; // reset
        $stmt = oci_parse($this->conn->getResource(), $this->sqlToOracleBindVars($this->sql));
        if (!$stmt) {
            throw new SQLException("Unable to prepare update", $this->conn->nativeError(), $this->sqlToOracleBindVars($this->sql));
        }
        // bind all variables
        $this->bindVars($stmt);
        // Even if autocommit is on, delay commit until after LOBS have been saved
        $success = oci_execute($stmt, OCI_DEFAULT);
        if (!$success) {
            throw new SQLException("Unable to execute update", $this->conn->nativeError($stmt), $this->sqlToOracleBindVars($this->sql));
        }
        // save data in any LOB descriptors, then free them
        foreach($this->lobDescriptors as $paramIndex => $lobster) {
            $lob = $this->lobs[$paramIndex]; // corresponding Blob/Clob
            if ($lob->isFromFile()) {
                $success = $lobster->savefile($lob->getInputFile());
            } else {
                $success = $lobster->save($lob->getContents());
            }
            if (!$success) {
                $lobster->free();
                throw new SQLException("Error saving lob bound to " . $paramIndex);
            }
            $lobster->free();
        }
        if ($this->conn->getAutoCommit()) {
            oci_commit($this->conn->getResource()); // perform deferred commit
        }
        $this->updateCount = @oci_num_rows($stmt);
        return $this->updateCount;
    }
OCI8PreparedStatement::setBlob ($ paramIndex, $ blob)
Parameters:
string $paramIndex
mixed $blob Blob object or string containing data.
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 280 of file OCI8PreparedStatement.php.
    {
        require_once 'creole/util/Blob.php';
        if (!($blob instanceof Blob)) {
            $b = new Blob();
            $b->setContents($blob);
            $blob = $b;
        }
        $this->lobDescriptors[$paramIndex] = oci_new_descriptor($this->conn->getResource(), OCI_D_LOB);
        $this->lobs[$paramIndex] = $blob;
    }
OCI8PreparedStatement::setClob ($ paramIndex, $ clob)
Parameters:
string $paramIndex
mixed $clob Clob object or string containing data.
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 297 of file OCI8PreparedStatement.php.
    {
        require_once 'creole/util/Clob.php';
        if (!($clob instanceof Clob)) {
            $c = new Clob();
            $c->setContents($clob);
            $clob = $c;
        }
        $this->lobDescriptors[$paramIndex] = oci_new_descriptor($this->conn->getResource(), OCI_D_LOB);
        $this->lobs[$paramIndex] = $clob;
    }
OCI8PreparedStatement::setColumnArray () [private]
In order to send lob data (clob/blob) to the Oracle data base, the sqlToOracleBindVars function needs to have an ordered list of the columns being addressed in the sql statement.
Since only insert and update statements require special handling, there are two ways to find the columns: 1) find the first set of () and parse out the columns names based on the token ',' 2) find all the text strings to the left of the equal signs.
Parameters:
void
Returns:
void
Definition at line 384 of file OCI8PreparedStatement.php.
Referenced by sqlToOracleBindVars().
    {
        $this->columns = array();
        //handle the simple insert case first
        if(strtoupper(substr($this->sql, 0, 6)) == 'INSERT') {
            $firstPos = strpos($this->sql, '(');
            $secPos = strpos($this->sql, ')');
            $collist = substr($this->sql, $firstPos + 1, $secPos - $firstPos - 1);
            $this->columns = explode(',', $collist);
        }
        if (strtoupper(substr($this->sql, 0, 6)) == 'UPDATE') {
            //handle more complex update case
            //first get the string setup so we can explode based on '=?'
            //second split results from previous action based on ' '
            // the last token from this should be a column name
            $tmp = $this->sql;
            $tmp = str_replace(" =", "=", $this->sql);
            $tmp = str_replace("= ", "=", $tmp);
            $tmp = str_replace(",", " ", $tmp);
            $stage1 = explode("=?",$tmp);
            foreach($stage1 as $chunk) {
                $stage2 = explode(' ', $chunk);
                $this->columns[count($this->columns)] = $stage2[count($stage2) - 1];
            }
        }
   }
OCI8PreparedStatement::setDate ($ paramIndex, $ value)
Please note the format used with date() matches that of NLS_DATE_FORMAT set in OCI8Connection.php.
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 360 of file OCI8PreparedStatement.php.
References setNull().
    {
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date("Y-m-d", $value);
            elseif (is_object($value)) $value = date("Y-m-d", $value->getTime());
            $this->boundInVars[$paramIndex] = $value;
        }
    }
OCI8PreparedStatement::setNull ($ paramIndex)
Parameters:
int $paramIndex
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 417 of file OCI8PreparedStatement.php.
Referenced by setDate(), setString(), and setTimestamp().
    {
        $this->boundInVars[$paramIndex] = '';
    }
OCI8PreparedStatement::setString ($ paramIndex, $ value)
Since bind variables in oracle have no special characters, this setString method differs from the common one in that it does not single quote strings.
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 317 of file OCI8PreparedStatement.php.
References setNull().
    {
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            // it's ok to have a fatal error here, IMO, if object doesn't have
            // __toString() and is being passed to this method.
            if ( is_object ( $value ) ) {
                $this->boundInVars[$paramIndex] = $value->__toString();
            } else {
                $this->boundInVars[$paramIndex] = (string)$value;
            }
        }
    }
OCI8PreparedStatement::setTimestamp ($ paramIndex, $ value)
Copied this function from common/PreparedStatement.php and modified to work with Oracle Please note the format used with date() matches that of NLS_DATE_FORMAT set in OCI8Connection.php.
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 341 of file OCI8PreparedStatement.php.
References setNull().
    {
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date('Y-m-d H:i:s', $value);
            elseif (is_object($value)) $value = date('Y-m-d H:i:s', $value->getTime());
            $this->boundInVars[$paramIndex] = $value;
        }
    }
OCI8PreparedStatement::sqlToOracleBindVars ($ sql) [private]
Convert a Propel SQL into Oracle SQL.
Look for all of the '?' and replace with ":varX"
Parameters:
string $sql SQL in Propel native format
Returns:
string SQL in Oracle Bind Var format
Todo:
-cOCI8PreparedStatement Consider changing this implementation to use the fact that we already know where all the '?' chars are (in $positions array).
Definition at line 229 of file OCI8PreparedStatement.php.
References PreparedStatementCommon::$sql, and setColumnArray().
Referenced by executeQuery(), and executeUpdate().
    {
        $out = "";
        $in_literal = 0;
        $idxNum = 1;
        for ($i = 0; $i < strlen($sql); $i++) {
            $char = $sql[$i];
            if (strcmp($char,"'")==0) {
                $in_literal = ~$in_literal;
            }
            if (strcmp($char,"?")==0 && !$in_literal) {
                if (array_key_exists($idxNum, $this->lobs)){
                    if (class_exists('Blob') && ($this->lobs[$idxNum] instanceof Blob))
                        $out .= "empty_blob()";
                    if (class_exists('Clob') && ($this->lobs[$idxNum] instanceof Clob))
                        $out .= "empty_clob()";
                } else
                    $out .= ":var" . $idxNum;
                $idxNum++;
            } else {
                $out .= $char;
            }
        }
        if (isset($this->lobs) && !empty($this->lobs)) {
            $this->setColumnArray();
            $retstmt = " Returning ";
            $collist = "";
            $bindlist = "";
            foreach ($this->lobs as $idx=>$val) {
                $idxName = ":var" . $idx;
                if ((class_exists('Blob') && $val instanceof Blob) || (class_exists('Clob') && $val instanceof Clob)) {
                    //the columns array starts at zero instead of 1 like the lobs array
                    $collist .= $this->columns[$idx-1] . ",";
                    $bindlist .= $idxName . ",";
                }
            }
            if (!empty($collist))
                $out .= $retstmt . rtrim($collist, ",") . " into " . rtrim($bindlist, ",");
        }
        return $out;
    }
Member Data Documentation
OCI8PreparedStatement::$columns = array() [private]
Definition at line 56 of file OCI8PreparedStatement.php.
OCI8PreparedStatement::$lobDescriptors = array() [private]
Definition at line 42 of file OCI8PreparedStatement.php.
OCI8PreparedStatement::$lobs = array() [private]
Definition at line 49 of file OCI8PreparedStatement.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/oracle/OCI8PreparedStatement.php