fareofficelib: ODBCTypes Class Reference
ODBCTypes Class Reference
Static Public Member Functions
static loadTypeMap ($conn=null)
Loads the map of ODBC data types to Creole (JDBC) types.
static getType ($nativeType)
This method returns the generic Creole (JDBC-like) type when given the native db type.
static getNativeType ($creoleType)
This method will return a native type that corresponds to the specified Creole (JDBC-like) type.
Static Protected Attributes
static $typeMap = null
Map ODBC native types to Creole (JDBC) types.
static $reverseMap = null
Reverse mapping, created on demand.
Detailed Description
Definition at line 32 of file ODBCTypes.php.
Member Function Documentation
static ODBCTypes::getNativeType ($ creoleType) [static]
This method will return a native type that corresponds to the specified Creole (JDBC-like) type.
If there is more than one matching native type, then the LAST defined native type will be returned.
Parameters:
int $creoleType
Returns:
string Native type string.
Reimplemented from CreoleTypes.
Definition at line 178 of file ODBCTypes.php.
References loadTypeMap().
    {
        if (!self::$typeMap)
            self::loadTypeMap();
        if (self::$reverseMap === null) {
            self::$reverseMap = array_flip(self::$typeMap);
        }
        return @self::$reverseMap[$creoleType];
    }
static ODBCTypes::getType ($ nativeType) [static]
This method returns the generic Creole (JDBC-like) type when given the native db type.
Parameters:
string $nativeType DB native type (e.g. 'TEXT', 'byetea', etc.).
Returns:
int Creole native type (e.g. CreoleTypes::LONGVARCHAR, CreoleTypes::BINARY, etc.).
Reimplemented from CreoleTypes.
Definition at line 156 of file ODBCTypes.php.
References loadTypeMap(), and CreoleTypes::OTHER.
Referenced by ODBCTableInfo::initColumns(), and ODBCCachedResultSet::loadCache().
    {
        if (!self::$typeMap)
            self::loadTypeMap();
        $t = strtoupper($nativeType);
        if (isset(self::$typeMap[$t])) {
            return self::$typeMap[$t];
        } else {
            return CreoleTypes::OTHER;
        }
    }
static ODBCTypes::loadTypeMap ($ conn = null) [static]
Loads the map of ODBC data types to Creole (JDBC) types.
NOTE: This function cannot map DBMS-specific datatypes. If you use a driver which implements DBMS-specific datatypes, you will need to modify/extend this class to add the correct mapping.
Definition at line 51 of file ODBCTypes.php.
References $result, CreoleTypes::BIGINT, CreoleTypes::BINARY, CreoleTypes::BOOLEAN, CreoleTypes::CHAR, CreoleTypes::DATE, CreoleTypes::DECIMAL, CreoleTypes::DOUBLE, CreoleTypes::FLOAT, CreoleTypes::INTEGER, CreoleTypes::LONGVARBINARY, CreoleTypes::LONGVARCHAR, CreoleTypes::NUMERIC, CreoleTypes::OTHER, CreoleTypes::REAL, CreoleTypes::SMALLINT, CreoleTypes::TIME, CreoleTypes::TIMESTAMP, CreoleTypes::TINYINT, CreoleTypes::VARBINARY, and CreoleTypes::VARCHAR.
Referenced by getNativeType(), getType(), ODBCTableInfo::initColumns(), and ODBCCachedResultSet::loadCache().
    {
        if (self::$typeMap !== null && count(self::$typeMap) > 0)
            return;
        if ($conn == null)
            throw new SQLException('No connection specified when loading ODBC type map.');
        self::$typeMap = array();
        $result = @odbc_gettypeinfo($conn->getResource());
        if ($result === false)
            throw new SQLException('Failed to retrieve type info.', $conn->nativeError());
        $rowNum = 1;
        while (odbc_fetch_row($result, $rowNum++))
        {
            $odbctypeid = odbc_result($result, 'DATA_TYPE');
            $odbctypename = odbc_result($result, 'TYPE_NAME');
            switch ($odbctypeid)
            {
                case SQL_CHAR:
                    self::$typeMap[$odbctypename] = CreoleTypes::CHAR;
                    break;
                case SQL_VARCHAR:
                    self::$typeMap[$odbctypename] = CreoleTypes::VARCHAR;
                    break;
                case SQL_LONGVARCHAR:
                    self::$typeMap[$odbctypename] = CreoleTypes::LONGVARCHAR;
                    break;
                case SQL_DECIMAL:
                    self::$typeMap[$odbctypename] = CreoleTypes::DECIMAL;
                    break;
                case SQL_NUMERIC:
                    self::$typeMap[$odbctypename] = CreoleTypes::NUMERIC;
                    break;
                case SQL_BIT:
                    self::$typeMap[$odbctypename] = CreoleTypes::BOOLEAN;
                    break;
                case SQL_TINYINT:
                    self::$typeMap[$odbctypename] = CreoleTypes::TINYINT;
                    break;
                case SQL_SMALLINT:
                    self::$typeMap[$odbctypename] = CreoleTypes::SMALLINT;
                    break;
                case SQL_INTEGER:
                    self::$typeMap[$odbctypename] = CreoleTypes::INTEGER;
                    break;
                case SQL_BIGINT:
                    self::$typeMap[$odbctypename] = CreoleTypes::BIGINT;
                    break;
                case SQL_REAL:
                    self::$typeMap[$odbctypename] = CreoleTypes::REAL;
                    break;
                case SQL_FLOAT:
                    self::$typeMap[$odbctypename] = CreoleTypes::FLOAT;
                    break;
                case SQL_DOUBLE:
                    self::$typeMap[$odbctypename] = CreoleTypes::DOUBLE;
                    break;
                case SQL_BINARY:
                    self::$typeMap[$odbctypename] = CreoleTypes::BINARY;
                    break;
                case SQL_VARBINARY:
                    self::$typeMap[$odbctypename] = CreoleTypes::VARBINARY;
                    break;
                case SQL_LONGVARBINARY:
                    self::$typeMap[$odbctypename] = CreoleTypes::LONGVARBINARY;
                    break;
                case SQL_DATE:
                    self::$typeMap[$odbctypename] = CreoleTypes::DATE;
                    break;
                case SQL_TIME:
                    self::$typeMap[$odbctypename] = CreoleTypes::TIME;
                    break;
                case SQL_TIMESTAMP:
                    self::$typeMap[$odbctypename] = CreoleTypes::TIMESTAMP;
                    break;
                case SQL_TYPE_DATE:
                    self::$typeMap[$odbctypename] = CreoleTypes::DATE;
                    break;
                case SQL_TYPE_TIME:
                    self::$typeMap[$odbctypename] = CreoleTypes::TIME;
                    break;
                case SQL_TYPE_TIMESTAMP:
                    self::$typeMap[$odbctypename] = CreoleTypes::TIMESTAMP;
                    break;
                default:
                    self::$typeMap[$odbctypename] = CreoleTypes::OTHER;
                    break;
            }
        }
        @odbc_free_result($result);
    }
Member Data Documentation
ODBCTypes::$reverseMap = null [static, protected]
Reverse mapping, created on demand.
Definition at line 42 of file ODBCTypes.php.
ODBCTypes::$typeMap = null [static, protected]
Map ODBC native types to Creole (JDBC) types.
Definition at line 37 of file ODBCTypes.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCTypes.php