fareofficelib: SQLiteResultSetIterator Class Reference
SQLiteResultSetIterator Class Reference
Public Member Functions
__construct (SQLiteResultSet $rs)
Construct the iterator.
rewind ()
This method actually has no effect, since we do not rewind ResultSet for iteration.
valid ()
key ()
Returns the cursor position.
current ()
Returns the row (assoc array) at current cursor pos.
next ()
Advances internal cursor pos.
Private Attributes
$result
$pos = 0
$fetchmode
$row_count
Detailed Description
Definition at line 29 of file SQLiteResultSetIterator.php.
Constructor & Destructor Documentation
SQLiteResultSetIterator::__construct (SQLiteResultSet $ rs)
Construct the iterator.
Parameters:
SQLiteResultSet $rs
Definition at line 40 of file SQLiteResultSetIterator.php.
References ResultSetCommon::getFetchmode(), SQLiteResultSet::getRecordCount(), and ResultSetCommon::getResource().
    {
        $this->result = $rs->getResource();
        $this->fetchmode = $rs->getFetchmode();
  $this->row_count = $rs->getRecordCount();
    }
Member Function Documentation
SQLiteResultSetIterator::current ()
Returns the row (assoc array) at current cursor pos.
Returns:
array
Definition at line 75 of file SQLiteResultSetIterator.php.
    {
       return sqlite_fetch_array($this->result, $this->fetchmode);
    }
SQLiteResultSetIterator::key ()
Returns the cursor position.
Note that this will not necessarily be 1 for the first row, since no rewind is performed at beginning of iteration.
Returns:
int
Definition at line 66 of file SQLiteResultSetIterator.php.
    {
        return $this->pos;
    }
SQLiteResultSetIterator::next ()
Advances internal cursor pos.
Definition at line 83 of file SQLiteResultSetIterator.php.
    {
        $this->pos++;
    }
SQLiteResultSetIterator::rewind ()
This method actually has no effect, since we do not rewind ResultSet for iteration.
Definition at line 50 of file SQLiteResultSetIterator.php.
    {
        sqlite_rewind($this->result);
    }
SQLiteResultSetIterator::valid ()
Definition at line 55 of file SQLiteResultSetIterator.php.
    {
  return ( $this->pos < $this->row_count );
    }
Member Data Documentation
SQLiteResultSetIterator::$fetchmode [private]
Definition at line 33 of file SQLiteResultSetIterator.php.
SQLiteResultSetIterator::$pos = 0 [private]
Definition at line 32 of file SQLiteResultSetIterator.php.
SQLiteResultSetIterator::$result [private]
Definition at line 31 of file SQLiteResultSetIterator.php.
SQLiteResultSetIterator::$row_count [private]
Definition at line 34 of file SQLiteResultSetIterator.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/sqlite/SQLiteResultSetIterator.php