fareofficelib: DatabaseInfo Class Reference
DatabaseInfo Class Reference
Public Member Functions
__construct (Connection $conn, $vendorInfo=array())
getName ()
Get name of database.
__sleep ()
This method is invoked upon serialize().
__wakeup ()
This method is invoked upon unserialize().
getConnection ()
Returns Connection being used.
getTable ($name)
Get the TableInfo object for specified table name.
hasTable ($name)
Return whether database contains specified table.
getTables ()
Gets array of TableInfo objects.
addTable (TableInfo $table)
Adds a table to this db.
isSequence ($key)
getSequences ()
Gets array of ? objects.
getVendorSpecificInfo ()
Get vendor specific optional information for this primary key.
Protected Member Functions
initTables ()
initSequences ()
Protected Attributes
$tables = array()
$sequences = array()
$tablesLoaded = false
have tables been loaded
$seqsLoaded = false
have sequences been loaded
$conn
$dbname
Database name.
$dblink
Private Attributes
$vendorSpecificInfo = array()
additional vendor specific information
Detailed Description
Definition at line 30 of file DatabaseInfo.php.
Constructor & Destructor Documentation
DatabaseInfo::__construct (Connection $ conn, $ vendorInfo = array())
Parameters:
Connection $dbh
Definition at line 63 of file DatabaseInfo.php.
References Connection::getDSN(), and Connection::getResource().
    {
        $this->conn = $conn;
        $this->dblink = $conn->getResource();
        $dsn = $conn->getDSN();
        $this->dbname = $dsn['database'];
        $this->vendorSpecificInfo = $vendorInfo;
    }
Member Function Documentation
DatabaseInfo::__sleep ()
This method is invoked upon serialize().
Because the Info class hierarchy is recursive, we must handle the serialization and unserialization of this object.
Returns:
array The class variables that should be serialized (all must be public!).
Definition at line 87 of file DatabaseInfo.php.
    {
        return array('tables','sequences','conn');
    }
DatabaseInfo::__wakeup ()
This method is invoked upon unserialize().
This method re-hydrates the object and restores the recursive hierarchy.
Definition at line 96 of file DatabaseInfo.php.
    {
        // Re-init vars from serialized connection
        $this->dbname = $conn->database;
        $this->dblink = $conn->connection;
        // restore chaining
        foreach($this->tables as $tbl) {
            $tbl->database = $this;
            $tbl->dbname = $this->dbname;
            $tbl->dblink = $this->dblink;
            $tbl->schema = $this->schema;
        }
    }
DatabaseInfo::addTable (TableInfo $ table)
Adds a table to this db.
Table name is case-insensitive.
Parameters:
TableInfo $table
Definition at line 160 of file DatabaseInfo.php.
References TableInfo::getName().
    {
        $this->tables[strtoupper($table->getName())] = $table;
    }
DatabaseInfo::getConnection ()
Returns Connection being used.
Returns:
Connection
Definition at line 115 of file DatabaseInfo.php.
Referenced by TableInfo::__construct().
    {
        return $this->conn;
    }
DatabaseInfo::getName ()
Get name of database.
Returns:
string
Definition at line 76 of file DatabaseInfo.php.
Referenced by TableInfo::__construct().
    {
        return $this->dbname;
    }
DatabaseInfo::getSequences ()
Gets array of ? objects.
Returns:
array ?[]
Definition at line 191 of file DatabaseInfo.php.
References initSequences().
    {
        if(!$this->seqsLoaded) $this->initSequences();
        return array_values($this->sequences); //re-key [numerically]
    }
DatabaseInfo::getTable ($ name)
Get the TableInfo object for specified table name.
Parameters:
string $name The name of the table to retrieve.
Returns:
TableInfo
Exceptions:
SQLException - if table does not exist in this db.
Definition at line 126 of file DatabaseInfo.php.
References initTables().
    {
        if(!$this->tablesLoaded) $this->initTables();
        if (!isset($this->tables[strtoupper($name)])) {
            throw new SQLException("Database `".$this->dbname."` has no table `".$name."`");
        }
        return $this->tables[ strtoupper($name) ];
    }
DatabaseInfo::getTables ()
Gets array of TableInfo objects.
Returns:
array TableInfo[]
Definition at line 149 of file DatabaseInfo.php.
References initTables().
    {
        if(!$this->tablesLoaded) $this->initTables();
        return array_values($this->tables); //re-key [numerically]
    }
DatabaseInfo::getVendorSpecificInfo ()
Get vendor specific optional information for this primary key.
Returns:
array vendorSpecificInfo[]
Definition at line 201 of file DatabaseInfo.php.
    {
        return $this->vendorSpecificInfo;
    }
DatabaseInfo::hasTable ($ name)
Return whether database contains specified table.
Parameters:
string $name The table name.
Returns:
boolean
Definition at line 140 of file DatabaseInfo.php.
  {
    return isset($this->tables[strtoupper($name)]);
  }
DatabaseInfo::initSequences () [abstract, protected]
Returns:
void
Exceptions:
SQLException
Reimplemented in MSSQLDatabaseInfo, MySQLDatabaseInfo, MySQLiDatabaseInfo, ODBCDatabaseInfo, OCI8DatabaseInfo, PgSQLDatabaseInfo, and SQLiteDatabaseInfo.
Referenced by getSequences(), and isSequence().
DatabaseInfo::initTables () [abstract, protected]
Returns:
void
Exceptions:
SQLException
Reimplemented in MSSQLDatabaseInfo, MySQLDatabaseInfo, MySQLiDatabaseInfo, ODBCDatabaseInfo, OCI8DatabaseInfo, PgSQLDatabaseInfo, and SQLiteDatabaseInfo.
Referenced by getTable(), and getTables().
DatabaseInfo::isSequence ($ key)
Returns:
boolean
Exceptions:
SQLException
Definition at line 181 of file DatabaseInfo.php.
References initSequences().
    {
        if(!$this->seqsLoaded) $this->initSequences();
        return isset($this->sequences[ strtoupper($key) ]);
    }
Member Data Documentation
DatabaseInfo::$conn [protected]
Definition at line 49 of file DatabaseInfo.php.
DatabaseInfo::$dblink [protected]
Definition at line 58 of file DatabaseInfo.php.
DatabaseInfo::$dbname [protected]
Database name.
Definition at line 52 of file DatabaseInfo.php.
DatabaseInfo::$seqsLoaded = false [protected]
have sequences been loaded
Definition at line 40 of file DatabaseInfo.php.
DatabaseInfo::$sequences = array() [protected]
Definition at line 34 of file DatabaseInfo.php.
DatabaseInfo::$tables = array() [protected]
Definition at line 32 of file DatabaseInfo.php.
DatabaseInfo::$tablesLoaded = false [protected]
have tables been loaded
Definition at line 37 of file DatabaseInfo.php.
DatabaseInfo::$vendorSpecificInfo = array() [private]
additional vendor specific information
Definition at line 43 of file DatabaseInfo.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/metadata/DatabaseInfo.php