fareofficelib: PgSQLResultSet Class Reference
PgSQLResultSet Class Reference
Public Member Functions
seek ($rownum)
Gets optimized PgSQLResultSetIterator.
next ()
getRecordCount ()
close ()
getArray ($column)
Reads a column as an array.
getBlob ($column)
Returns Blob with contents of column value.
getBoolean ($column)
Private Member Functions
strToArray ($str)
Convert Postgres string representation of array into native PHP array.
Detailed Description
Definition at line 32 of file PgSQLResultSet.php.
Member Function Documentation
PgSQLResultSet::close ()
See also:
ResultSet::close()
Implements ResultSet.
Definition at line 113 of file PgSQLResultSet.php.
  {
    $this->fields = array();
    @pg_free_result($this->result);
  }
PgSQLResultSet::getArray ($ column)
Reads a column as an array.
The value of the column is unserialized & returned as an array.
Parameters:
mixed $column Column name (string) or index (int) starting with 1.
Returns:
array
Exceptions:
SQLException - If the column specified is not a valid key in current field array.
Reimplemented from ResultSetCommon.
Definition at line 166 of file PgSQLResultSet.php.
References strToArray().
  {
    if (is_int($column)) { $column--; } // because Java convention is to start at 1
    if (!array_key_exists($column, $this->fields)) { throw new SQLException("Invalid resultset column: " . (is_int($column) ? $column + 1 : $column)); }
    if ($this->fields[$column] === null) { return null; }
    return $this->strToArray($this->fields[$column]);
  }
PgSQLResultSet::getBlob ($ column)
Returns Blob with contents of column value.
Parameters:
mixed $column Column name (string) or index (int) starting with 1 (if ResultSet::FETCHMODE_NUM was used).
Returns:
Blob New Blob with data from column.
Exceptions:
SQLException - If the column specified is not a valid key in current field array.
Reimplemented from ResultSetCommon.
Definition at line 181 of file PgSQLResultSet.php.
  {
    if (is_int($column)) { $column--; } // because Java convention is to start at 1
    if (!array_key_exists($column, $this->fields)) { throw new SQLException("Invalid resultset column: " . (is_int($column) ? $column + 1 : $column)); }
    if ($this->fields[$column] === null) { return null; }
    require_once 'creole/util/Blob.php';
    $b = new Blob();
    $b->setContents(pg_unescape_bytea($this->fields[$column]));
    return $b;
  }
PgSQLResultSet::getBoolean ($ column)
Parameters:
mixed $column Column name (string) or index (int) starting with 1.
Returns:
boolean
Exceptions:
SQLException - If the column specified is not a valid key in current field array.
Reimplemented from ResultSetCommon.
Definition at line 197 of file PgSQLResultSet.php.
  {
    if (is_int($column)) { $column--; } // because Java convention is to start at 1
    if (!array_key_exists($column, $this->fields)) { throw new SQLException("Invalid resultset column: " . (is_int($column) ? $column + 1 : $column)); }
    if ($this->fields[$column] === null) { return null; }
    return ($this->fields[$column] === 't');
  }
PgSQLResultSet::getRecordCount ()
See also:
ResultSet::getRecordCount()
Implements ResultSet.
Definition at line 101 of file PgSQLResultSet.php.
Referenced by PgSQLResultSetIterator::__construct().
  {
    $rows = @pg_num_rows($this->result);
    if ($rows === null) {
      throw new SQLException("Error fetching num rows", pg_result_error($this->result));
    }
    return (int) $rows;
  }
PgSQLResultSet::next ()
See also:
ResultSet::next()
Implements ResultSet.
Definition at line 74 of file PgSQLResultSet.php.
References ResultSetCommon::afterLast(), and ResultSet::FETCHMODE_ASSOC.
  {
    $this->fields = @pg_fetch_array($this->result, $this->cursorPos, $this->fetchmode);
    if (!$this->fields) {
      $err = @pg_result_error($this->result);
      if (!$err) {
        // We've advanced beyond end of recordset.
        $this->afterLast();
        return false;
      } else {
        throw new SQLException("Error fetching result", $err);
      }
    }
    if ($this->fetchmode === ResultSet::FETCHMODE_ASSOC && $this->lowerAssocCase) {
            $this->fields = array_change_key_case($this->fields, CASE_LOWER);
        }
    // Advance cursor position
    $this->cursorPos++;
    return true;
  }
PgSQLResultSet::seek ($ rownum)
Gets optimized PgSQLResultSetIterator.
Returns:
PgSQLResultSetIterator Postgres doesn't actually move the db pointer. The specific row is fetched by call to pg_fetch_array() rather than by a seek and then an unspecified pg_fetch_array() call.
The only side-effect of this situation is that we don't really know if the seek will fail or succeed until we have called next(). This behavior is acceptible - and explicitly documented in ResultSet::seek() phpdoc.
See also:
ResultSet::seek()
Implements ResultSet.
Definition at line 59 of file PgSQLResultSet.php.
  {
    if ($rownum < 0) {
      return false;
    }
    // PostgreSQL rows start w/ 0, but this works, because we are
    // looking to move the position _before_ the next desired position
    $this->cursorPos = $rownum;
    return true;
  }
PgSQLResultSet::strToArray ($ str) [private]
Convert Postgres string representation of array into native PHP array.
Parameters:
string $str Postgres string array rep: {1223, 2343} or {{"welcome", "home"}, {"test2", ""}}
Returns:
array
Definition at line 124 of file PgSQLResultSet.php.
Referenced by getArray().
  {
    $str = substr($str, 1, -1); // remove { }
    $res = array();
    $subarr = array();
    $in_subarr = 0;
    $toks = explode(',', $str);
    foreach($toks as $tok) {
      if ($in_subarr > 0) { // already in sub-array?
        $subarr[$in_subarr][] = $tok;
        if ('}' === substr($tok, -1, 1)) { // check to see if we just added last component
          $res[] = $this->strToArray(implode(',', $subarr[$in_subarr]));
          $in_subarr--;
        }
      } elseif ($tok{0} === '{') { // we're inside a new sub-array
        if ('}' !== substr($tok, -1, 1)) {
          $in_subarr++;
          // if sub-array has more than one element
          $subarr[$in_subarr] = array();
          $subarr[$in_subarr][] = $tok;
        } else {
          $res[] = $this->strToArray($tok);
        }
      } else { // not sub-array
        $val = trim($tok, '"'); // remove " (surrounding strings)
        // perform type castng here?
        $res[] = $val;
      }
    }
    return $res;
  }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/pgsql/PgSQLResultSet.php