fareofficelib: UTConfig Class Reference
UTConfig Class Reference
[Unit Tests - Unit tests for all classes/functions in fareofficelib.]
Unit test for all functions in UTConfig.class.php.
Public Member Functions
doTest ()
Private Member Functions
_testConfig ()
_testSiteConfig ()
_testDbConfig ()
Detailed Description
Unit test for all functions in UTConfig.class.php.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 8 of file UTConfig.class.php.
Member Function Documentation
UTConfig::_testConfig () [private]
Definition at line 17 of file UTConfig.class.php.
Referenced by doTest().
  {
    $config = new Config();
    $this->setSectionLabel('Config');
    eval($this->needNotEmpty('$config->getEnvironmentDir()'));
    eval($this->needEmpty('$config->setEnvironmentDir("/var/www/fareofficeroot")'));
    eval($this->needEqual('$config->getEnvironmentDir()', '"/var/www/fareofficeroot/"'));
    eval($this->needEqual('$config->getLogDir()', '"/var/www/fareofficeroot/Log/"'));
    eval($this->needEqual('$config->getSiteDir()', '"/var/www/fareofficeroot/Site/"'));
    eval($this->needNotEmpty('$config->getSites()'));
    foreach($config->getSites() as $siteConfig)
    {
      eval($this->needEqual('get_class($siteConfig)', '"SiteConfig"'));
    }
  }
UTConfig::_testDbConfig () [private]
Definition at line 52 of file UTConfig.class.php.
Referenced by doTest().
  {
    $config = new Config();
    $this->setSectionLabel('DbConfig');
    eval($this->needNotEmpty('$config->getSite("fareofficelib")'));
    eval($this->needEqual('$config->getSite("fareofficelib")->getLogDir()', '"/var/www/fareofficeroot/Site/fareofficelib/Temp/Log/"'));
    eval($this->needEqual('$config->getSite("fareofficelib")->getCacheDir()', '"/var/www/fareofficeroot/Site/fareofficelib/Temp/Cache/"'));
  }
UTConfig::_testSiteConfig () [private]
Definition at line 37 of file UTConfig.class.php.
Referenced by doTest().
  {
    $config = new Config();
    $this->setSectionLabel('SiteConfig');
    eval($this->needNotEmpty('$dbConfig = $config->getDbConfig()'));
    eval($this->needEmpty('$dbConfig->getDSN("mysql_database")'));
    eval($this->needEmpty('$dbConfig->clearDSN()'));
    eval($this->needEmpty('$dbConfig->setDSN("mysql_database", "mysql", "localhost", "root", "", "mysql")'));
    eval($this->needEqual('$dbConfig->getDSN("mysql_database")', 'array(\'phptype\'=>\'mysql\',\'hostspec\'=>\'localhost\',\'username\'=>\'root\',\'password\'=>\'\',\'database\'=>\'mysql\')'));
    eval($this->needEqual('$config->getDBDSN("mysql_database")', 'array(\'phptype\'=>\'mysql\',\'hostspec\'=>\'localhost\',\'username\'=>\'root\',\'password\'=>\'\',\'database\'=>\'mysql\')'));
  }
UTConfig::doTest ()
Definition at line 10 of file UTConfig.class.php.
References _testConfig(), _testDbConfig(), and _testSiteConfig().
  {
    $this->_testConfig();
    $this->_testSiteConfig();
    $this->_testDbConfig();
  }
The documentation for this class was generated from the following file:
Static/UnitTestHtDocs/FareOfficeLib/Config/UTConfig.class.php