fareofficelib: ODBCConnection Class Reference
ODBCConnection Class Reference
Public Member Functions
connect ($dsninfo, $flags=0)
close ()
__destruct ()
Shouldn't this be in ConnectionCommon.php?
nativeError ()
Returns a formatted ODBC error string.
getAdapter ()
Returns driver-specific ODBCAdapter.
getDatabaseInfo ()
getIdGenerator ()
createResultSet ($odbcresult, $fetchmode)
Creates the appropriate ResultSet.
prepareStatement ($sql)
createStatement ()
prepareCall ($sql)
applyLimit (&$sql, $offset, $limit)
executeQuery ($sql, $fetchmode=null)
executeUpdate ($sql)
getUpdateCount ()
Protected Member Functions
beginTrans ()
Start a database transaction.
commitTrans ()
Commit the current transaction.
rollbackTrans ()
Roll back (undo) the current transaction.
Protected Attributes
$adapter = null
$odbcresult = null
Detailed Description
Definition at line 33 of file ODBCConnection.php.
Constructor & Destructor Documentation
ODBCConnection::__destruct ()
Shouldn't this be in ConnectionCommon.php?
Definition at line 129 of file ODBCConnection.php.
References close().
    {
        $this->close();
    }
Member Function Documentation
ODBCConnection::applyLimit (&$ sql, $ offset, $ limit)
See also:
Connection::applyLimit()
Implements Connection.
Definition at line 213 of file ODBCConnection.php.
    {
        if ($this->adapter->hasLimitOffset())
            $this->adapter->applyLimit($sql, $offset, $limit);
    }
ODBCConnection::beginTrans () [protected]
Start a database transaction.
Exceptions:
SQLException
Returns:
void
Reimplemented from ConnectionCommon.
Definition at line 260 of file ODBCConnection.php.
References nativeError().
    {
        if ($this->adapter->supportsTransactions()) {
            @odbc_autocommit($this->dblink, false);
            if (odbc_error($this->dblink) == 'S1C00') {
                throw new SQLException('Could not begin transaction', $this->nativeError());
            }
        }
    }
ODBCConnection::close ()
See also:
Connection::close()
Implements Connection.
Definition at line 110 of file ODBCConnection.php.
Referenced by __destruct().
    {
        $ret = true;
        $this->adapter = null;
        $this->odbcresult = null;
        if ($this->dblink !== null)
        {
            $ret = @odbc_close($this->dblink);
            $this->dblink = null;
        }
        return $ret;
    }
ODBCConnection::commitTrans () [protected]
Commit the current transaction.
Exceptions:
SQLException
Returns:
void
Reimplemented from ConnectionCommon.
Definition at line 275 of file ODBCConnection.php.
References $result, and nativeError().
    {
        if ($this->adapter->supportsTransactions()) {
            $result = @odbc_commit($this->dblink);
            if (!$result) {
                throw new SQLException('Could not commit transaction', $this->nativeError());
            }
            @odbc_autocommit($this->dblink, true);
            if (odbc_error($this->dblink) == 'S1C00') {
                throw new SQLException('Could not commit transaction (autocommit failed)', $this->nativeError());
            }
        }
    }
ODBCConnection::connect ($ dsninfo, $ flags = 0)
See also:
Connection::connect()
This prevents blob fields from being fetched when a row is loaded from a recordset. Clob fields however are loaded with up to 'odbc.defaultlrl' data. This should be the default anyway, but we'll set it here just to keep things consistent.
Implements Connection.
Definition at line 50 of file ODBCConnection.php.
References ConnectionCommon::$flags, Creole::COMPAT_ASSOC_LOWER, Creole::import(), nativeError(), and Creole::PERSISTENT.
    {
    if (!function_exists('odbc_connect'))
            throw new SQLException('odbc extension not loaded');
        $adapterclass = isset($dsninfo['adapter']) ? $dsninfo['adapter'] : null;
        if (!$adapterclass)
            $adapterclass = 'ODBCAdapter';
        else
            $adapterclass .= 'Adapter';
        Creole::import('creole.drivers.odbc.adapters.' . $adapterclass);
        $this->adapter = new $adapterclass();
        $this->dsn = $dsninfo;
        $this->flags = $flags;
        if ( !($this->flags & Creole::COMPAT_ASSOC_LOWER) && !$this->adapter->preservesColumnCase())
        {
            trigger_error('Connection created without Creole::COMPAT_ASSOC_LOWER, ' .
                          'but driver does not support case preservation.',
                          E_USER_WARNING);
            $this->flags != Creole::COMPAT_ASSOC_LOWER;
        }
        $persistent = ($flags & Creole::PERSISTENT) === Creole::PERSISTENT;
        if ($dsninfo['database'])
            $odbcdsn = $dsninfo['database'];
        elseif ($dsninfo['hostspec'])
            $odbcdsn = $dsninfo['hostspec'];
        else
            $odbcdsn = 'localhost';
        $user = @$dsninfo['username'];
        $pw = @$dsninfo['password'];
        $connect_function = $persistent ? 'odbc_pconnect' : 'odbc_connect';
        $conn = @$connect_function($odbcdsn, $user, $pw, SQL_CUR_USE_IF_NEEDED);
        if (!is_resource($conn))
            throw new SQLException('connect failed', $this->nativeError(), $odbcdsn);
        $this->dblink = $conn;
        @odbc_binmode(0, ODBC_BINMODE_PASSTHRU);
        @odbc_longreadlen(0, ini_get('odbc.defaultlrl'));
    }
ODBCConnection::createResultSet ($ odbcresult, $ fetchmode)
Creates the appropriate ResultSet.
Returns:
ResultSet
Definition at line 178 of file ODBCConnection.php.
References $odbcresult.
Referenced by executeQuery().
    {
        return $this->adapter->createResultSet($this, $odbcresult, $fetchmode);
    }
ODBCConnection::createStatement ()
See also:
Connection::createStatement()
Implements Connection.
Definition at line 195 of file ODBCConnection.php.
    {
        require_once 'creole/drivers/odbc/ODBCStatement.php';
        return new ODBCStatement($this);
    }
ODBCConnection::executeQuery ($ sql, $ fetchmode = null)
See also:
Connection::executeQuery()
Implements Connection.
Definition at line 222 of file ODBCConnection.php.
References createResultSet(), and nativeError().
    {
        if ($this->odbcresult)
            $this->odbcresult = null;
        $r = @odbc_exec($this->dblink, $sql);
        if ($r === false)
            throw new SQLException('Could not execute query', $this->nativeError(), $sql);
        $this->odbcresult = new ODBCResultResource($r);
        return $this->createResultSet($this->odbcresult, $fetchmode);
    }
ODBCConnection::executeUpdate ($ sql)
See also:
Connection::executeUpdate()
Implements Connection.
Definition at line 240 of file ODBCConnection.php.
References getUpdateCount(), and nativeError().
    {
        if ($this->odbcresult)
            $this->odbcresult = null;
        $r = @odbc_exec($this->dblink, $sql);
        if ($r === false)
            throw new SQLException('Could not execute update', $this->nativeError(), $sql);
        $this->odbcresult = new ODBCResultResource($r);
        return $this->getUpdateCount();
    }
ODBCConnection::getAdapter ()
Returns driver-specific ODBCAdapter.
Returns:
ODBCAdapter
Definition at line 152 of file ODBCConnection.php.
    {
        return $this->adapter;
    }
ODBCConnection::getDatabaseInfo ()
See also:
Connection::getDatabaseInfo()
Implements Connection.
Definition at line 160 of file ODBCConnection.php.
    {
        require_once 'creole/drivers/odbc/metadata/ODBCDatabaseInfo.php';
        return new ODBCDatabaseInfo($this);
    }
ODBCConnection::getIdGenerator ()
See also:
Connection::getIdGenerator()
Implements Connection.
Definition at line 169 of file ODBCConnection.php.
    {
        return $this->adapter->getIdGenerator($this);
    }
ODBCConnection::getUpdateCount ()
See also:
Connection::getUpdateCount()
Implements Connection.
Definition at line 311 of file ODBCConnection.php.
References nativeError().
Referenced by executeUpdate().
    {
        if ($this->odbcresult === null)
            return 0;
        $n = @odbc_num_rows($this->odbcresult->getHandle());
        if ($n == -1)
            throw new SQLException('Could not retrieve update count', $this->nativeError());
        return (int) $n;
    }
ODBCConnection::nativeError ()
Returns a formatted ODBC error string.
Returns:
string
Definition at line 138 of file ODBCConnection.php.
Referenced by beginTrans(), commitTrans(), connect(), executeQuery(), executeUpdate(), getUpdateCount(), and rollbackTrans().
    {
        if ($this->dblink && is_resource($this->dblink))
            $errstr = '[' . @odbc_error($this->dblink) . '] ' . @odbc_errormsg($this->dblink);
        else
            $errstr = '[' . @odbc_error() . '] ' . @odbc_errormsg();
        return $errstr;
    }
ODBCConnection::prepareCall ($ sql)
Todo:
To be implemented
See also:
Connection::prepareCall()
Reimplemented from ConnectionCommon.
Definition at line 205 of file ODBCConnection.php.
    {
        throw new SQLException('Stored procedures not currently implemented.');
    }
ODBCConnection::prepareStatement ($ sql)
See also:
Connection::prepareStatement()
Implements Connection.
Definition at line 186 of file ODBCConnection.php.
    {
        require_once 'creole/drivers/odbc/ODBCPreparedStatement.php';
        return new ODBCPreparedStatement($this, $sql);
    }
ODBCConnection::rollbackTrans () [protected]
Roll back (undo) the current transaction.
Exceptions:
SQLException
Returns:
void
Reimplemented from ConnectionCommon.
Definition at line 294 of file ODBCConnection.php.
References $result, and nativeError().
    {
        if ($this->adapter->supportsTransactions()) {
            $result = @odbc_rollback($this->dblink);
            if (!$result) {
                throw new SQLException('Could not rollback transaction', $this->nativeError());
            }
            @odbc_autocommit($this->dblink, true);
            if (odbc_error($this->dblink) == 'S1C00') {
                throw new SQLException('Could not rollback transaction (autocommit failed)', $this->nativeError());
            }
        }
    }
Member Data Documentation
ODBCConnection::$adapter = null [protected]
Definition at line 39 of file ODBCConnection.php.
ODBCConnection::$odbcresult = null [protected]
Definition at line 45 of file ODBCConnection.php.
Referenced by createResultSet().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCConnection.php