fareofficelib: FileLock Class Reference
FileLock Class Reference
[General]
Include files.
Public Member Functions
FileLock ($lockPath_)
Constructor.
setLockPath ($lockPath_)
Set the lock path.
getLockPath ()
Get The path to where the lock files are stored.
deleteAllLocks ()
Delete all lock files, both expired and not expired.
isLockExpired ($lockName_, $lockTime_=60, $compressName_=true)
Check if the file is locked.
Private Member Functions
_getFileName ($lockName_, $compressName_)
Returns a valid file path for the $lockName_.
Private Attributes
$_lockPath
The path to where to save the lock files.
Detailed Description
Include files.
Does a server global lock on a lock name.
A file with the lock name are saved to the file system, if that file is older then $lockTime_ seconds this function returns true.
This is used to see how long ago a certatin operation was done. Example, If it's more then 15 minutes since we last did send and SMS message we can now send a new.
Example:
 $lock = new FileLock('/tmp/locks/');
 if ($lock->_isLockExpired('SMS'))
 {
   // Send SMS
 }
 if ($lock->_isLockExpired('/usr/root/master/%more?d=true', 60, TRUE))
 {
   // Send SMS
 }
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 35 of file FileLock.class.php.
Member Function Documentation
FileLock::_getFileName ($ lockName_, $ compressName_) [private]
Returns a valid file path for the $lockName_.
Definition at line 164 of file FileLock.class.php.
References getLockPath().
Referenced by isLockExpired().
  {
    if ($compressName_)
    {
      $lockName_ = md5($lockName_);
    }
    $fileName = $this->getLockPath() . md5($lockName_) . '.lock';
    return $fileName;
  }
FileLock::deleteAllLocks ()
Delete all lock files, both expired and not expired.
Returns:
- boolean - true if files where deleted successfully.
Definition at line 92 of file FileLock.class.php.
References getLockPath().
  {
    $path = $this->getLockPath();
    if
    (
      !empty($path) &&
      $path != '/'
    )
    {
      exec('rm ' . $path . '*.lock', $arr, $retval);
      return true;
    }
    else
    {
      return false;
    }
  }
FileLock::FileLock ($ lockPath_)
Constructor.
Parameters:
$lockPath_ - string - The path to where to save the lock files. Ie. /tmp/locks/
Definition at line 44 of file FileLock.class.php.
References setLockPath().
  {
    $this->setLockPath($lockPath_);
  }
FileLock::getLockPath ()
Get The path to where the lock files are stored.
Ie. /tmp/locks
Returns:
- string -
Definition at line 80 of file FileLock.class.php.
Referenced by _getFileName(), and deleteAllLocks().
  {
    // @todo add assertlog
    //assertLog(!empty($this->_lockPath), EL_LEVEL_3, ECAT_DIAGNOSTIC, 'Couldnt create lockPath: ' . $this->_lockPath);
    return $this->_lockPath;
  }
FileLock::isLockExpired ($ lockName_, $ lockTime_ = 60, $ compressName_ = true)
Check if the file is locked.
An entity is locked in the system, if that entity was locked more then $lockTime_ seconds ago, this funtion returns true.
This is used to see how long ago a certatin operation was done. Example, If it's more then 1 minute since we last did send an SMS message we can now send a new.
Parameters:
$lockName_ - string - The name of the lock/variable/file.
$lockTime_ - string - Seconds the lockTitle is locked before expiring.
$compressName_ - boolean - true - An md5 will be done on the filename/lockName_.
Returns:
- boolean -
Implements ILock.
Definition at line 133 of file FileLock.class.php.
References _getFileName().
  {
    $fileName = $this->_getFileName($lockName_, $compressName_);
    $retVal = false;
    if
    (
      !file_exists($fileName) ||
      filemtime($fileName) < (time() - $lockTime_)
    )
    {
      $handle = @fopen($fileName, 'w');
      if ($handle !== false)
      {
        fwrite($handle, $lockName_);
        $retVal = true;
        fclose($handle);
      }
    }
    return $retVal;
  }
FileLock::setLockPath ($ lockPath_)
Set the lock path.
Parameters:
$lockPath_ - string - The path to where to save the lock files. Ie. /tmp/locks/
Definition at line 56 of file FileLock.class.php.
Referenced by FileLock().
  {
    $this->_lockPath = rtrim($lockPath_, '/') . '/';
    if (!file_exists($this->_lockPath))
    {
      if (!@mkdir($this->_lockPath, 0755, true))
      {
        // @todo add assertlog
        //assertLog(false, EL_LEVEL_3, ECAT_DIAGNOSTIC, 'Couldnt create lockPath: ' . $this->_lockPath);
        echo('Couldnt create path');
        exit;
      }
    }
  }
Member Data Documentation
FileLock::$_lockPath [private]
The path to where to save the lock files.
Ie. /tmp/locks/
Definition at line 180 of file FileLock.class.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/General/FileLock.class.php