fareofficelib: PgSQLPreparedStatement Class Reference
PgSQLPreparedStatement Class Reference
Public Member Functions
setArray ($paramIndex, $value)
Sets an array.
setBoolean ($paramIndex, $value)
For setting value of Postgres BOOLEAN column.
setBlob ($paramIndex, $blob)
Applies sqlite_udf_encode_binary() to ensure that binary contents will be handled correctly by sqlite.
setTime ($paramIndex, $value)
setTimestamp ($paramIndex, $value)
Protected Member Functions
escape ($str)
Quotes string using native pgsql function (pg_escape_string).
Private Member Functions
arrayToStr ($arr)
Recursive function to turn multi-dim array into str representation.
Detailed Description
Definition at line 32 of file PgSQLPreparedStatement.php.
Member Function Documentation
PgSQLPreparedStatement::arrayToStr ($ arr) [private]
Recursive function to turn multi-dim array into str representation.
Parameters:
array $arr
Returns:
string Array in pgsql-friendly string notation: {val1, val2} or {{sub1,sub2}, {sub3, sub4}}
Definition at line 49 of file PgSQLPreparedStatement.php.
References escape().
Referenced by setArray().
    {
        $parts = array();
        foreach((array)$arr as $el) {
            if (is_array($el)) {
                $parts[] = $this->arrayToStr($el);
            } else {
                if (is_string($el)) {
                    $parts[] = '"' . $this->escape($el) . '"';
                } else {
                    $parts[] = $el;
                }
            }
        }
        return '{' . implode(',', $parts) . '}';
    }
PgSQLPreparedStatement::escape ($ str) [protected]
Quotes string using native pgsql function (pg_escape_string).
Parameters:
string $str
Returns:
string
Reimplemented from PreparedStatementCommon.
Definition at line 39 of file PgSQLPreparedStatement.php.
Referenced by arrayToStr(), and setTime().
    {
        return pg_escape_string($str);
    }
PgSQLPreparedStatement::setArray ($ paramIndex, $ value)
Sets an array.
Unless a driver-specific method is used, this means simply serializing the passed parameter and storing it as a string.
Parameters:
int $paramIndex
array $value
Returns:
void
See also:
PreparedStatement::setArray()
Reimplemented from PreparedStatementCommon.
Definition at line 75 of file PgSQLPreparedStatement.php.
References arrayToStr(), and PreparedStatementCommon::setNull().
    {
        if( $paramIndex > $this->positionsCount || $paramIndex < 1) {
            throw new SQLException('Cannot bind to invalid param index: '.$paramIndex);
        }
        if ($value === null)
            $this->setNull($paramIndex);
        else
            $this->boundInVars[$paramIndex] = "'" . $this->arrayToStr($value) . "'";
    }
PgSQLPreparedStatement::setBlob ($ paramIndex, $ blob)
Applies sqlite_udf_encode_binary() to ensure that binary contents will be handled correctly by sqlite.
Parameters:
int $paramIndex
mixed $blob Blob object or string containing data.
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 109 of file PgSQLPreparedStatement.php.
References PreparedStatementCommon::setNull().
    {
        if ($blob === null) {
            $this->setNull($paramIndex);
        } else {
            // they took magic __toString() out of PHP5.0.0; this sucks
            if (is_object($blob)) {
                $blob = $blob->__toString();
            }
            $this->boundInVars[$paramIndex] = "'" . pg_escape_bytea( $blob ) . "'";
        }
    }
PgSQLPreparedStatement::setBoolean ($ paramIndex, $ value)
For setting value of Postgres BOOLEAN column.
Parameters:
int $paramIndex
boolean $value
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 92 of file PgSQLPreparedStatement.php.
References PreparedStatementCommon::setNull().
    {
        if( $paramIndex > $this->positionsCount || $paramIndex < 1) {
            throw new SQLException('Cannot bind to invalid param index: '.$paramIndex);
        }
        if ($value === null)
            $this->setNull($paramIndex);
        else
            $this->boundInVars[$paramIndex] = ($value ? "'t'" : "'f'");
    }
PgSQLPreparedStatement::setTime ($ paramIndex, $ value)
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 128 of file PgSQLPreparedStatement.php.
References escape(), and PreparedStatementCommon::setNull().
    {
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if ( is_numeric ( $value ) ) {
        $value = date ( "H:i:s O", $value );
      } elseif ( is_object ( $value ) ) {
        $value = date ( "H:i:s O", $value->getTime ( ) );
      }
            $this->boundInVars [ $paramIndex ] = "'" . $this->escape ( $value ) . "'";
        }
    }
PgSQLPreparedStatement::setTimestamp ($ paramIndex, $ value)
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented from PreparedStatementCommon.
Definition at line 147 of file PgSQLPreparedStatement.php.
References PreparedStatementCommon::setNull().
    {
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date('Y-m-d H:i:s O', $value);
            elseif (is_object($value)) $value = date("Y-m-d H:i:s O", $value->getTime());
            $this->boundInVars[$paramIndex] = "'".$this->escape($value)."'";
        }
    }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/pgsql/PgSQLPreparedStatement.php