fareofficelib: Mail_MIMEPart Class Reference
Mail_MIMEPart Class Reference
Public Member Functions
__construct ($body= '', $params=array())
Constructor.
encode ()
Encodes and returns the email.
addSubPart ($body, $params)
Adds a subpart to current mime part and returns a reference to it.
Private Member Functions
getEncodedData ($data, $encoding)
Returns encoded data based upon encoding passed to it.
quotedPrintableEncode ($input, $line_max=76)
Encodes data to quoted-printable standard.
Private Attributes
$encoding
$subparts
$encoded
$headers
$body
Detailed Description
Definition at line 74 of file mimePart.php.
Constructor & Destructor Documentation
Mail_MIMEPart::__construct ($ body = '', $ params = array())
Constructor.
Sets up the object.
Parameters:
$body - The body of the mime part if any.
$params - An associative array of parameters: content_type - The content type for this part eg multipart/mixed encoding - The encoding to use, 7bit, 8bit, base64, or quoted-printable cid - Content ID to apply disposition - Content disposition, inline or attachment dfilename - Optional filename parameter for content disposition description - Content description charset - Character set to use public
Definition at line 122 of file mimePart.php.
References $body, and $headers.
    {
        if (!defined('MAIL_MIMEPART_CRLF')) {
            define('MAIL_MIMEPART_CRLF', defined('MAIL_MIME_CRLF') ? MAIL_MIME_CRLF : "\r\n", true);
        }
        foreach ($params as $key => $value) {
            switch ($key) {
                case 'content_type':
                    $headers['Content-Type'] = $value . (isset($charset) ? '; charset="' . $charset . '"' : '');
                    break;
                case 'encoding':
                    $this->encoding = $value;
                    $headers['Content-Transfer-Encoding'] = $value;
                    break;
                case 'cid':
                    $headers['Content-ID'] = '<' . $value . '>';
                    break;
                case 'disposition':
                    $headers['Content-Disposition'] = $value . (isset($dfilename) ? '; filename="' . $dfilename . '"' : '');
                    break;
                case 'dfilename':
                    if (isset($headers['Content-Disposition'])) {
                        $headers['Content-Disposition'] .= '; filename="' . $value . '"';
                    } else {
                        $dfilename = $value;
                    }
                    break;
                case 'description':
                    $headers['Content-Description'] = $value;
                    break;
                case 'charset':
                    if (isset($headers['Content-Type'])) {
                        $headers['Content-Type'] .= '; charset="' . $value . '"';
                    } else {
                        $charset = $value;
                    }
                    break;
            }
        }
        // Default content-type
        if (!isset($headers['Content-Type'])) {
            $headers['Content-Type'] = 'text/plain';
        }
        // Default encoding
        if (!isset($this->encoding)) {
            $this->encoding = '7bit';
        }
        // Assign stuff to member variables
        $this->encoded  = array();
        $this->headers  = $headers;
        $this->body     = $body;
    }
Member Function Documentation
Mail_MIMEPart::addSubPart ($ body, $ params)
Adds a subpart to current mime part and returns a reference to it.
Parameters:
$body The body of the subpart, if any.
$params The parameters for the subpart, same as the $params argument for constructor.
Returns:
A reference to the part you just added.
Definition at line 234 of file mimePart.php.
References $body.
    {
        $this->subparts[] = new Mail_MIMEPart($body, $params);
        return $this->subparts[count($this->subparts) - 1];
    }
Mail_MIMEPart::encode ()
Encodes and returns the email.
Also stores it in the encoded member variable
Returns:
An associative array containing two elements, body and headers. The headers element is itself an indexed array.
Definition at line 193 of file mimePart.php.
References $encoded, $headers, $subparts, and getEncodedData().
    {
        $encoded =& $this->encoded;
        if (!empty($this->subparts)) {
            srand((double)microtime()*1000000);
            $boundary = '=_' . md5(uniqid(rand()) . microtime());
            $this->headers['Content-Type'] .= ';' . MAIL_MIMEPART_CRLF . "\t" . 'boundary="' . $boundary . '"';
            // Add body parts to $subparts
            for ($i = 0; $i < count($this->subparts); $i++) {
                $headers = array();
                $tmp = $this->subparts[$i]->encode();
                foreach ($tmp['headers'] as $key => $value) {
                    $headers[] = $key . ': ' . $value;
                }
                $subparts[] = implode(MAIL_MIMEPART_CRLF, $headers) . MAIL_MIMEPART_CRLF . MAIL_MIMEPART_CRLF . $tmp['body'];
            }
            $encoded['body'] = '--' . $boundary . MAIL_MIMEPART_CRLF .
                               implode('--' . $boundary . MAIL_MIMEPART_CRLF, $subparts) .
                               '--' . $boundary.'--' . MAIL_MIMEPART_CRLF;
        } else {
            $encoded['body'] = $this->getEncodedData($this->body, $this->encoding) . MAIL_MIMEPART_CRLF;
        }
        // Add headers to $encoded
        $encoded['headers'] =& $this->headers;
        return $encoded;
    }
Mail_MIMEPart::getEncodedData ($ data, $ encoding) [private]
Returns encoded data based upon encoding passed to it.
Parameters:
$data The data to encode.
$encoding The encoding type to use, 7bit, base64, or quoted-printable.
Definition at line 248 of file mimePart.php.
References $encoding, and quotedPrintableEncode().
Referenced by encode().
    {
        switch ($encoding) {
            case '8bit':
            case '7bit':
                return $data;
                break;
            case 'quoted-printable':
                return $this->quotedPrintableEncode($data);
                break;
            case 'base64':
                return rtrim(chunk_split(base64_encode($data), 76, MAIL_MIMEPART_CRLF));
                break;
            default:
                return $data;
        }
    }
Mail_MIMEPart::quotedPrintableEncode ($ input, $ line_max = 76) [private]
Encodes data to quoted-printable standard.
Parameters:
$input The data to encode
$line_max Optional max line length. Should not be more than 76 chars
Definition at line 276 of file mimePart.php.
Referenced by getEncodedData().
    {
        $lines  = preg_split("/\r?\n/", $input);
        $eol    = MAIL_MIMEPART_CRLF;
        $escape = '=';
        $output = '';
        while(list(, $line) = each($lines)){
            $linlen     = strlen($line);
            $newline = '';
            for ($i = 0; $i < $linlen; $i++) {
                $char = substr($line, $i, 1);
                $dec  = ord($char);
                if (($dec == 32) AND ($i == ($linlen - 1))){    // convert space at eol only
                    $char = '=20';
                } elseif($dec == 9) {
                    ; // Do nothing if a tab.
                } elseif(($dec == 61) OR ($dec < 32 ) OR ($dec > 126)) {
                    $char = $escape . strtoupper(sprintf('%02s', dechex($dec)));
                }
                if ((strlen($newline) + strlen($char)) >= $line_max) {        // MAIL_MIMEPART_CRLF is not counted
                    $output  .= $newline . $escape . $eol;                    // soft line break; " =\r\n" is okay
                    $newline  = '';
                }
                $newline .= $char;
            } // end of for
            $output .= $newline . $eol;
        }
        $output = substr($output, 0, -1 * strlen($eol)); // Don't want last crlf
        return $output;
    }
Member Data Documentation
Mail_MIMEPart::$body [private]
Definition at line 104 of file mimePart.php.
Referenced by __construct(), and addSubPart().
Mail_MIMEPart::$encoded [private]
Definition at line 92 of file mimePart.php.
Referenced by encode().
Mail_MIMEPart::$encoding [private]
Definition at line 80 of file mimePart.php.
Referenced by getEncodedData().
Mail_MIMEPart::$headers [private]
Definition at line 98 of file mimePart.php.
Referenced by __construct(), and encode().
Mail_MIMEPart::$subparts [private]
Definition at line 86 of file mimePart.php.
Referenced by encode().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/Rmail/mimePart.php