fareofficelib: Record Class Reference
Record Class Reference
Public Member Functions
__construct (DataSet $ds, $addRecord=false)
Creates a new Record and sets the parent dataset to the passed in value.
delete (Connection $conn=null)
Shortcut method to delete this record.
save (Connection $conn=null)
Saves the data in this Record to the database.
getValue ($col)
Gets the value for specified column.
columns ()
Get the column names for current record.
size ()
The number of columns in this object.
toBeSavedWithInsert ()
Whether or not this Record is to be saved with an SQL insert statement.
toBeSavedWithUpdate ()
Whether or not this Record is to be saved with an SQL update statement.
toBeSavedWithDelete ()
Whether or not this Record is to be saved with an SQL delete statement.
markRecordClean ()
Marks all the values in this record as clean.
markForInsert ()
Marks this record to be inserted when a save is executed.
markForUpdate ()
Marks this record to be updated when a save is executed.
markToBeDeleted ()
Marks this record to be deleted when a save is executed.
unmarkToBeDeleted ()
Unmarks a record that has been marked for deletion.
markValueClean ($col)
Marks a value with a given column name as clean (unmodified).
markValueDirty ($col)
Marks a value with a given column as "dirty" (modified).
setSaveType ($type)
Sets the internal save type as one of the defined privates (ie: ZOMBIE).
getSaveType ()
Gets the internal save type as one of the defined privates (ie: ZOMBIE).
setValue ($col, $value)
Sets the value of col.
isAZombie ()
Determines if this record is a Zombie.
needsToBeSaved ()
If the record is not clean, needs to be saved with an Update, Delete or Insert, it returns true.
valueIsClean ($column)
Determines whether or not a value stored in the record is clean.
recordIsClean ()
Goes through all the values in the record to determine if it is clean or not.
refresh (Connection $conn=null)
This method refreshes this Record's Value's.
getRefreshSql ()
This builds the SELECT statement in order to refresh the contents of this Record.
dataset ()
Gets the DataSet for this Record.
setParentDataSet (DataSet $ds)
Sets the parent DataSet for this record.
__toString ()
This returns a representation of this Record.
Public Attributes
const ZOMBIE = -1
const UNKNOWN = 0
const INSERT = 1
const UPDATE = 2
const DELETE = 3
const BEFOREINSERT = 4
const AFTERINSERT = 5
const BEFOREUPDATE = 6
const AFTERUPDATE = 7
const BEFOREDELETE = 8
const AFTERDELETE = 9
Private Member Functions
initializeRecord ()
Performs initialization for this Record.
createValues (ResultSet $rs)
Creates the value objects for this Record.
doDelete (Connection $conn=null)
Performs a DELETE on databse using this Record as criteria.
doUpdate (Connection $conn=null)
Saves the data in this Record to the database with an UPDATE statement.
doInsert (Connection $conn=null)
Saves the data in this Record to the database with an INSERT statement.
getUpdateSql ()
Builds the SQL UPDATE statement for this Record.
getDeleteSql ()
Builds the SQL DELETE statement for this Record.
getInsertSql ()
Builds the SQL INSERT statement for this Record.
dirtyColumns ()
Get the modified (dirty) columns.
Private Attributes
$values = array()
an array of values strings, indexed by column name.
$dirtyCols = array()
array of modified (dirty) columns
$ds
the parent DataSet for this Record
$saveType = 0
this is the state of this record
Detailed Description
Definition at line 41 of file Record.php.
Constructor & Destructor Documentation
Record::__construct (DataSet $ ds, $ addRecord = false)
Creates a new Record and sets the parent dataset to the passed in value.
If $addRecord is true, then an empty record is created.
Parameters:
DataSet $ds The parent / owning dataset.
boolean $addRecord Whether to create an empty record.
Definition at line 76 of file Record.php.
References createValues(), and setParentDataSet().
    {
        $this->setParentDataSet($ds);
        if (!$addRecord) {
            $this->createValues($this->ds->resultSet());
        }
    }
Member Function Documentation
Record::__toString ()
This returns a representation of this Record.
Returns:
string
Definition at line 732 of file Record.php.
References columns(), and getValue().
    {
        $sb = "{";
        foreach($this->columns() as $col) {
            $sb .= "'" . $this->getValue($col) . "',";
        }
        $sb = substr($sb, 0, -1);
        $sb .= "}";
        return $sb;
    }
Record::columns ()
Get the column names for current record.
Returns:
array Column names.
Definition at line 398 of file Record.php.
Referenced by __toString(), and getRefreshSql().
    {
        return array_keys($this->values);
    }
Record::createValues (ResultSet $ rs) [private]
Creates the value objects for this Record.
It is 1 based
Returns:
void
Definition at line 99 of file Record.php.
References ResultSet::getRow().
Referenced by __construct(), and refresh().
    {
        $this->values = $rs->getRow();
    }
Record::dataset ()
Gets the DataSet for this Record.
Returns:
DataSet
Definition at line 714 of file Record.php.
    {
        return $this->ds;
    }
Record::delete (Connection $ conn = null)
Shortcut method to delete this record.
Parameters:
Connection $conn
Definition at line 108 of file Record.php.
References DELETE, save(), and setSaveType().
    {
        $this->setSaveType(DELETE);
        $this->save($conn);
    }
Record::dirtyColumns () [private]
Get the modified (dirty) columns.
Private right now because this is only used internally. No real reason why this couldn't be public, though ...
Returns:
array
Definition at line 409 of file Record.php.
Referenced by doInsert(), doUpdate(), getInsertSql(), and getUpdateSql().
    {
        return array_keys($this->dirtyCols);
    }
Record::doDelete (Connection $ conn = null) [private]
Performs a DELETE on databse using this Record as criteria.
Returns:
int Number of rows affected by delete.
Exceptions:
DataSetException,SQLException
Definition at line 154 of file Record.php.
References CreoleTypes::getAffix(), getDeleteSql(), getValue(), setSaveType(), and ZOMBIE.
Referenced by save().
    {
        if ($conn === null) {
            $conn = $this->ds->connection();
        }
        $table = $this->ds->tableInfo();
        $stmt = null;
        try {
            $stmt = $conn->prepareStatement($this->getDeleteSql());
            $ps = 1;
            $kd = $this->ds->keydef();
            for ($i = 1, $kdsize = $kd->size(); $i <= $kdsize; $i++) {
                $col = $kd->getAttrib($i);
                $val = $this->getValue($col);
                $setter = 'set' . CreoleTypes::getAffix( $table->getColumn($col)->getType() );
                $stmt->$setter($ps++, $val);
            }
            $ret = $stmt->executeUpdate();
            // note that the actual removal of the Record objects
            // from the DataSet is done by the TDS::save() method.
            $this->setSaveType(Record::ZOMBIE);
            $stmt->close();
            if ($ret > 1) {
                throw new SQLException("There were " . $ret . " rows deleted with this records key value.");
            }
            return $ret;
        } catch (SQLException $e) {
            if ($stmt) $stmt->close();
            throw $e;
        }
    }
Record::doInsert (Connection $ conn = null) [private]
Saves the data in this Record to the database with an INSERT statement.
Returns:
int
Exceptions:
DataSetException,SQLException
Definition at line 250 of file Record.php.
References AFTERINSERT, dirtyColumns(), CreoleTypes::getAffix(), getInsertSql(), getValue(), markRecordClean(), refresh(), and setSaveType().
Referenced by save().
    {
        $stmt = null;
        try {
            $stmt = $conn->prepareStatement($this->getInsertSql());
            $ps = 1;
            foreach($this->dirtyColumns() as $col) {
                $val = $this->getValue($col);
                $setter = 'set' . CreoleTypes::getAffix( $table->getColumn($col)->getType() );
                $stmt->$setter($ps++, $val);
            }
            $ret = $stmt->executeUpdate();
            if ($this->ds->refreshOnSave()) {
                $this->refresh();
            } else {
                // Marks all of the values clean since they have now been saved
                $this->markRecordClean();
            }
            $this->setSaveType(Record::AFTERINSERT);
            if ($ret > 1) {
                // a little late again...
                throw new SQLException ("There were " . $ret . " rows inserted with this records key value.");
            }
            return $ret;
        } catch (SQLException $e) {
            if ($stmt) $stmt->close();
            throw $e;
        }
    }
Record::doUpdate (Connection $ conn = null) [private]
Saves the data in this Record to the database with an UPDATE statement.
Returns:
SQL UPDATE statement
Exceptions:
DataSetException,SQLException
Definition at line 198 of file Record.php.
References AFTERUPDATE, dirtyColumns(), CreoleTypes::getAffix(), getUpdateSql(), getValue(), markRecordClean(), refresh(), and setSaveType().
Referenced by save().
    {
        if ($conn === null) {
            $conn = $this->ds->connection();
        }
        $table = $this->ds->tableInfo();
        $stmt = null;
        try {
            $stmt = $conn->prepareStatement($this->getUpdateSql());
            $ps = 1;
            foreach($this->dirtyColumns() as $col) {
                $setter = 'set' . CreoleTypes::getAffix( $table->getColumn($col)->getType() );
                $stmt->$setter($ps++, $this->getValue($col));
            }
            $kd = $this->ds->keydef();
            for ($i = 1, $kdsize = $kd->size(); $i <= $kdsize; $i++) {
                $attrib = $kd->getAttrib($i);
                $setter = 'set' . CreoleTypes::getAffix( $table->getColumn($attrib)->getType() );
                $stmt->$setter($ps++, $this->getValue($attrib));
            }
            $ret = $stmt->executeUpdate();
            if ($this->ds->refreshOnSave()) {
                $this->refresh();
            } else {
                // Marks all of the values clean since they have now been saved
                $this->markRecordClean();
            }
            $this->setSaveType(Record::AFTERUPDATE);
            if ($ret > 1) {
                throw new SQLException ("There were " . $ret . " rows updated with this records key value.");
            }
            return $ret;
        } catch (SQLException $e) {
            if ($stmt) $stmt->close();
            throw $e;
        }
    }
Record::getDeleteSql () [private]
Builds the SQL DELETE statement for this Record.
Returns:
string SQL DELETE statement
Exceptions:
DataSetException - if no keydef
Definition at line 336 of file Record.php.
Referenced by doDelete().
    {
        $kd = $this->ds->keydef();
        if ($kd === null || $kd->size() === 0) {
            throw new DataSetException("You must specify KeyDef attributes for this TableDataSet in order to delete a Record.");
        }
        $where_sql = "";
        $comma = false;
        for ($i = 1, $kdsize = $kd->size(); $i <= $kdsize; $i++) {
            if (!$comma) {
                $where_sql .= $kd->getAttrib($i) . " = ?";
                $comma = true;
            } else {
                $where_sql .= " AND " . $kd->getAttrib($i) . " = ?";
            }
        }
        return "DELETE FROM " . $this->ds->tableName() . " WHERE " . $where_sql;
    }
Record::getInsertSql () [private]
Builds the SQL INSERT statement for this Record.
Returns:
string SQL INSERT statement
Definition at line 362 of file Record.php.
References dirtyColumns().
Referenced by doInsert().
    {
        $fields_sql = "";
        $values_sql = "";
        $comma = false;
        foreach($this->dirtyColumns() as $col) {
            if (!$comma) {
                $fields_sql .= $col;
                $values_sql .= "?";
                $comma = true;
            } else {
                $fields_sql .= ", " . $col;
                $values_sql .= ", ?";
            }
        }
        return "INSERT INTO " . $this->ds->tableName() . " ( " . $fields_sql . " ) VALUES ( " . $values_sql . " )";
    }
Record::getRefreshSql ()
This builds the SELECT statement in order to refresh the contents of this Record.
It depends on a valid KeyDef to exist and it must have been created with a TableDataSet.
Returns:
string The SELECT SQL
Exceptions:
DataSetException
Definition at line 666 of file Record.php.
References columns(), and valueIsClean().
Referenced by refresh().
    {
        if ($this->ds->keydef() === null || $this->ds->keydef()->size() === 0) {
            throw new DataSetException("You can only perform a getRefreshQueryString on a TableDataSet that was created with a KeyDef.");
        } elseif ($this->ds instanceof QueryDataSet) {
            throw new DataSetException("You can only perform a getRefreshQueryString on Records created with a TableDataSet.");
        }
        $sql1 = "";
        $sql2 = "";
        $comma = false;
        foreach($this->columns() as $col) {
            if (!$comma) {
                $attribs_sql .= $col;
                $comma = true;
            } else {
                $attribs_sql .= ", " . $col;
            }
        }
        $comma = false;
        for ($i = 1, $kdsize = $kd->size(); $i <= $kdsize; $i++) {
            $attrib = $kd->getAttrib($i);
            if (!$this->valueIsClean($attrib)) {
                throw new DataSetException (
                        "You cannot do a refresh from the database if the value " .
                        "for a KeyDef column has been changed with a Record.setValue().");
            }
            if (!$comma) {
                $where_sql .= $attrib . " = ?";
                $comma = true;
            } else {
                $where_sql .= " AND " . $attrib . " = ?";
            }
        }
        return "SELECT " . $attribs_sql . " FROM " . $this->ds->tableName() . " WHERE " . $where_sql;
    }
Record::getSaveType ()
Gets the internal save type as one of the defined privates (ie: ZOMBIE).
Returns:
int
Definition at line 551 of file Record.php.
    {
        return $this->saveType;
    }
Record::getUpdateSql () [private]
Builds the SQL UPDATE statement for this Record.
Returns:
string SQL UPDATE statement
Exceptions:
DataSetException
Definition at line 291 of file Record.php.
References dirtyColumns(), recordIsClean(), and valueIsClean().
Referenced by doUpdate().
    {
        $kd = $this->ds->keydef();
        if ($kd === null || $kd->size() === 0) {
            throw new DataSetException("You must specify KeyDef attributes for this TableDataSet in order to create a Record for update.");
        } elseif ($this->recordIsClean()) {
            throw new DataSetException ("You must Record->setValue() on a column before doing an update.");
        }
        $set_sql = "";
        $where_sql = "";
        $comma = false;
        foreach($this->dirtyColumns() as $col)  {
            if (!$comma) {
                $set_sql .= $col . " = ?";
                $comma = true;
            } else {
                $set_sql .= ", " . $col . " = ?";
            }
        }
        $comma = false;
        for ($i = 1, $kdsize = $kd->size(); $i <= $kdsize; $i++) {
            $attrib = $kd->getAttrib($i);
            if (! $this->valueIsClean ($attrib)) {
                throw new DataSetException ("The value for column '" . $attrib . "' is a key value and cannot be updated.");
            }
            if (!$comma) {
                $where_sql .= $attrib . " = ?";
                $comma = true;
            } else {
                $where_sql .= " AND " . $attrib . " = ?";
            }
        }
        return "UPDATE " . $this->ds->tableName() . " SET " . $set_sql . " WHERE " . $where_sql;
    }
Record::getValue ($ col)
Gets the value for specified column.
This function performs no type-conversion.
Returns:
string The value object for specified column as string.
Exceptions:
DataSetException
Definition at line 386 of file Record.php.
Referenced by __toString(), doDelete(), doInsert(), doUpdate(), and refresh().
    {
        if (!isset($this->values[$col])) {
            throw new DataSetException("Undefined column in Record: " . $col);
        }
        return $this->values[$col];
    }
Record::initializeRecord () [private]
Performs initialization for this Record.
Definition at line 87 of file Record.php.
References setSaveType(), and UNKNOWN.
Referenced by refresh().
    {
        $this->values = array();
        $this->dirtyCols = array();
        $this->setSaveType(Record::UNKNOWN);
    }
Record::isAZombie ()
Determines if this record is a Zombie.
A Zombie is a record that has been deleted from the database, but not yet removed from the DataSet.
Returns:
boolean
Definition at line 574 of file Record.php.
References ZOMBIE.
Referenced by needsToBeSaved().
    {
        return ($this->saveType === Record::ZOMBIE);
    }
Record::markForInsert ()
Marks this record to be inserted when a save is executed.
Returns:
void
Exceptions:
DataSetException - if DataSet is not TableDataSet
Definition at line 464 of file Record.php.
References INSERT, and setSaveType().
    {
        if ($this->ds instanceof QueryDataSet) {
            throw new DataSetException ("You cannot mark a record in a QueryDataSet for insert");
        }
        $this->setSaveType(Record::INSERT);
    }
Record::markForUpdate ()
Marks this record to be updated when a save is executed.
Returns:
void
Exceptions:
DataSetException - if DataSet is not TableDataSet
Definition at line 477 of file Record.php.
References setSaveType(), and UPDATE.
    {
        if ($this->ds instanceof QueryDataSet) {
            throw new DataSetException ("You cannot mark a record in a QueryDataSet for update");
        }
        $this->setSaveType(Record::UPDATE);
    }
Record::markRecordClean ()
Marks all the values in this record as clean.
Returns:
void
Definition at line 454 of file Record.php.
Referenced by doInsert(), and doUpdate().
    {
        $this->dirtyCols = array();
    }
Record::markToBeDeleted ()
Marks this record to be deleted when a save is executed.
Returns:
void
Exceptions:
DataSetException - if DataSet is not TableDataSet
Definition at line 489 of file Record.php.
References DELETE, and setSaveType().
    {
        if ($this->ds instanceof QueryDataSet) {
            throw new DataSetException ("You cannot mark a record in a QueryDataSet for deletion");
        }
        $this->setSaveType(Record::DELETE);
        // return this;
    }
Record::markValueClean ($ col)
Marks a value with a given column name as clean (unmodified).
Parameters:
string $col
Returns:
void
Definition at line 522 of file Record.php.
    {
        unset($this->dirtyCols[$col]);
    }
Record::markValueDirty ($ col)
Marks a value with a given column as "dirty" (modified).
Parameters:
string $col
Returns:
void
Definition at line 532 of file Record.php.
Referenced by setValue().
    {
        $this->dirtyCols[$col] = true;
    }
Record::needsToBeSaved ()
If the record is not clean, needs to be saved with an Update, Delete or Insert, it returns true.
Returns:
boolean
Definition at line 583 of file Record.php.
References isAZombie(), recordIsClean(), toBeSavedWithDelete(), toBeSavedWithInsert(), and toBeSavedWithUpdate().
Referenced by save().
    {
        return (!$this->isAZombie() || !$this->recordIsClean() || $this->toBeSavedWithUpdate() ||
                $this->toBeSavedWithDelete() || $this->toBeSavedWithInsert());
    }
Record::recordIsClean ()
Goes through all the values in the record to determine if it is clean or not.
Returns:
true if clean
Definition at line 606 of file Record.php.
Referenced by getUpdateSql(), and needsToBeSaved().
    {
        return empty($this->dirtyCols);
    }
Record::refresh (Connection $ conn = null)
This method refreshes this Record's Value's.
It can only be performed on a Record that has not been modified and has been created with a TableDataSet and corresponding KeyDef.
Parameters:
Connection $conn
Exceptions:
DataSetException
SQLException
Definition at line 620 of file Record.php.
References createValues(), CreoleTypes::getAffix(), getRefreshSql(), getValue(), initializeRecord(), toBeSavedWithDelete(), and toBeSavedWithInsert().
Referenced by doInsert(), and doUpdate().
    {
        if ($conn === null) {
            $conn = $this->ds->connection();
        }
        if ($this->toBeSavedWithDelete()) {
            return;
        } elseif ($this->toBeSavedWithInsert()) {
            throw new DataSetException("There is no way to refresh a record which has been created with addRecord().");
        } elseif ($this->ds instanceof QueryDataSet) {
            throw new DataSetException ("You can only perform a refresh on Records created with a TableDataSet.");
        }
        $stmt = null;
        try {
            $stmt = $conn->prepareStatement ($this->getRefreshSql());
            $ps = 1;
            $kd = $this->ds->keydef();
            for ($i = 1, $kdsize = $kd->size(); $i <= $kdsize; $i++)
            {
                $val = $this->getValue($kd->getAttrib($i));
                if ($val == null) {
                    throw new DataSetException ("You cannot execute an update with a null value for a KeyDef.");
                }
                $setter = 'set' . CreoleTypes::getAffix( $table->getColumn($col)->getType() );
                $stmt->$setter($ps++, $val);
            }
            $rs = $stmt->executeQuery();
            $rs->next();
            $this->initializeRecord();
            $this->createValues($rs);
        } catch (SQLException $e) {
            if ($stmt) $stmt->close();
            throw $e;
        }
    }
Record::save (Connection $ conn = null)
Saves the data in this Record to the database.
Parameters:
Connection $conn
Returns:
boolean True if the save completed. false otherwise.
Exceptions:
DataSetException
Definition at line 120 of file Record.php.
References DELETE, doDelete(), doInsert(), doUpdate(), INSERT, needsToBeSaved(), and UPDATE.
Referenced by delete().
    {
        $returnValue = false;
        if ($this->ds instanceof QueryDataSet) {
            throw new DataSetException("You cannot save a QueryDataSet. Please use a TableDataSet instead.");
        }
        if (!$this->needsToBeSaved()) {
            return $returnValue;
        }
        switch($this->saveType) {
            case Record::INSERT:
                $returnValue = $this->doInsert($conn);
                break;
            case Record::UPDATE:
                $returnValue = $this->doUpdate($conn);
                break;
            case Record::DELETE:
                $returnValue = $this->doDelete($conn);
                break;
            default:
                throw new DataSetException("Invalid or no-action saveType for Record.");
        }
        return (boolean) $returnValue;
    }
Record::setParentDataSet (DataSet $ ds)
Sets the parent DataSet for this record.
Parameters:
DataSet $ds
Definition at line 723 of file Record.php.
Referenced by __construct().
    {
        $this->ds = $ds;
    }
Record::setSaveType ($ type)
Sets the internal save type as one of the defined privates (ie: ZOMBIE).
Parameters:
int $type
Returns:
void
Definition at line 542 of file Record.php.
Referenced by delete(), doDelete(), doInsert(), doUpdate(), initializeRecord(), markForInsert(), markForUpdate(), markToBeDeleted(), and unmarkToBeDeleted().
    {
        $this->saveType = $type;
    }
Record::setValue ($ col, $ value)
Sets the value of col.
Returns:
Record this object.
Exceptions:
DataSetException
Definition at line 561 of file Record.php.
References markValueDirty().
    {
        $this->values[$col] = $value;
        $this->markValueDirty($col);
        return $this;
    }
Record::size ()
The number of columns in this object.
Returns:
the number of columns in this object
Definition at line 418 of file Record.php.
    {
        return count($this->values);
    }
Record::toBeSavedWithDelete ()
Whether or not this Record is to be saved with an SQL delete statement.
Returns:
boolean True if saved with delete
Definition at line 445 of file Record.php.
References DELETE.
Referenced by needsToBeSaved(), and refresh().
    {
        return ($this->saveType === Record::DELETE);
    }
Record::toBeSavedWithInsert ()
Whether or not this Record is to be saved with an SQL insert statement.
Returns:
boolean True if saved with insert
Definition at line 427 of file Record.php.
References INSERT.
Referenced by needsToBeSaved(), and refresh().
    {
        return ($this->saveType === Record::INSERT);
    }
Record::toBeSavedWithUpdate ()
Whether or not this Record is to be saved with an SQL update statement.
Returns:
boolean True if saved with update
Definition at line 436 of file Record.php.
References UPDATE.
Referenced by needsToBeSaved().
    {
        return ($this->saveType === Record::UPDATE);
    }
Record::unmarkToBeDeleted ()
Unmarks a record that has been marked for deletion.
WARNING: You must reset the save type before trying to save this record again.
See also:
markForUpdate()
markForInsert()
markToBeDeleted()
Exceptions:
DataSetException
Definition at line 508 of file Record.php.
References setSaveType(), UNKNOWN, and ZOMBIE.
    {
        if ($this->saveType === Record::ZOMBIE) {
            throw new DataSetException ("This record has already been deleted!");
        }
        $this->setSaveType(UNKNOWN);
        //return $this;
    }
Record::valueIsClean ($ column)
Determines whether or not a value stored in the record is clean.
Returns:
true if clean
Exceptions:
DataSetException
Definition at line 594 of file Record.php.
Referenced by getRefreshSql(), and getUpdateSql().
    {
        if (!isset($this->values[$column])) {
            throw new DataSetException("Undefined column: ".$column);
        }
        return !isset($this->dirtyCols[$column]);
    }
Member Data Documentation
Record::$dirtyCols = array() [private]
array of modified (dirty) columns
Definition at line 60 of file Record.php.
Record::$ds [private]
the parent DataSet for this Record
Definition at line 63 of file Record.php.
Record::$saveType = 0 [private]
this is the state of this record
Definition at line 66 of file Record.php.
Record::$values = array() [private]
an array of values strings, indexed by column name.
Definition at line 57 of file Record.php.
const Record::AFTERDELETE = 9
Definition at line 54 of file Record.php.
const Record::AFTERINSERT = 5
Definition at line 50 of file Record.php.
Referenced by doInsert().
const Record::AFTERUPDATE = 7
Definition at line 52 of file Record.php.
Referenced by doUpdate().
const Record::BEFOREDELETE = 8
Definition at line 53 of file Record.php.
const Record::BEFOREINSERT = 4
Definition at line 49 of file Record.php.
const Record::BEFOREUPDATE = 6
Definition at line 51 of file Record.php.
const Record::DELETE = 3
Definition at line 48 of file Record.php.
Referenced by delete(), markToBeDeleted(), save(), and toBeSavedWithDelete().
const Record::INSERT = 1
Definition at line 46 of file Record.php.
Referenced by markForInsert(), save(), and toBeSavedWithInsert().
const Record::UNKNOWN = 0
Definition at line 45 of file Record.php.
Referenced by initializeRecord(), and unmarkToBeDeleted().
const Record::UPDATE = 2
Definition at line 47 of file Record.php.
Referenced by markForUpdate(), save(), and toBeSavedWithUpdate().
const Record::ZOMBIE = -1
Definition at line 44 of file Record.php.
Referenced by doDelete(), isAZombie(), and unmarkToBeDeleted().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/jargon/Record.php