fareofficelib: ColumnInfo Class Reference
ColumnInfo Class Reference
Public Member Functions
__construct (TableInfo $table, $name, $type=null, $nativeType=null, $size=null, $precision=null, $scale=null, $is_nullable=null, $default=null, $is_auto_increment=null, $vendorInfo=array())
Construct a new ColumnInfo object.
__sleep ()
This "magic" method is invoked upon serialize().
getName ()
Get column name.
getType ()
Get column type.
getNativeType ()
Gets the native type name.
getSize ()
Get column size.
getPrecision ()
Get column precision.
getScale ()
Get column scale.
getDefaultValue ()
Get the default value.
isNullable ()
Is column nullable?
isAutoIncrement ()
Is column of autoincrement type?
getVendorSpecificInfo ()
Get vendor specific optional information for this column.
toString ()
getTable ()
Get parent table.
Public Attributes
$name
Column name.
$type
Column Creole type.
$nativeType
Column native type.
$size
Column length.
$precision
Column presision.
$scale
Column scale (number of digits after decimal).
$isNullable
Is nullable?
$defaultValue
Default value.
$isAutoIncrement
Is autoincrement?
$table
Table.
Protected Attributes
$vendorSpecificInfo = array()
Detailed Description
Definition at line 30 of file ColumnInfo.php.
Constructor & Destructor Documentation
ColumnInfo::__construct (TableInfo $ table, $ name, $ type = null, $ nativeType = null, $ size = null, $ precision = null, $ scale = null, $ is_nullable = null, $ default = null, $ is_auto_increment = null, $ vendorInfo = array())
Construct a new ColumnInfo object.
Parameters:
TableInfo $table The table that owns this column.
string $name Column name.
int $type Creole type.
string $nativeType Native type name.
int $size Column length.
int $scale Column scale (number of digits after decimal).
boolean $is_nullable Whether col is nullable.
mixed $default Default value.
boolean $is_auto_increment Whether col is of autoIncrement type.
Definition at line 86 of file ColumnInfo.php.
References $name, $nativeType, $precision, $scale, $size, $type, isAutoIncrement(), and isNullable().
    {
        $this->table = $table;
        $this->name = $name;
        $this->type = $type;
        $this->nativeType = $nativeType;
        $this->size = $size;
        $this->precision = $precision;
        $this->scale = $scale;
        $this->isNullable = $is_nullable;
        $this->defaultValue = $default;
        $this->isAutoIncrement = $is_auto_increment;
        $this->vendorSpecificInfo = $vendorInfo;
    }
Member Function Documentation
ColumnInfo::__sleep ()
This "magic" method is invoked upon serialize().
Because the Info class hierarchy is recursive, we must handle the serialization and unserialization of this object.
Returns:
array The class variables that should be serialized (all must be public!).
Definition at line 118 of file ColumnInfo.php.
    {
        return array('name', 'type', 'nativeType', 'size', 'precision', 'isNullable', 'defaultValue');
    }
ColumnInfo::getDefaultValue ()
Get the default value.
Returns:
mixed
Definition at line 183 of file ColumnInfo.php.
    {
        return $this->defaultValue;
    }
ColumnInfo::getName ()
Get column name.
Returns:
string
Definition at line 127 of file ColumnInfo.php.
Referenced by TableInfo::addColumn().
    {
        return $this->name;
    }
ColumnInfo::getNativeType ()
Gets the native type name.
Returns:
string
Definition at line 145 of file ColumnInfo.php.
    {
        return $this->nativeType;
    }
ColumnInfo::getPrecision ()
Get column precision.
Returns:
int
Definition at line 163 of file ColumnInfo.php.
    {
        return $this->precision;
    }
ColumnInfo::getScale ()
Get column scale.
Scale refers to number of digits after the decimal. Sometimes this is referred to as precision, but precision is the total number of digits (i.e. length).
Returns:
int
Definition at line 174 of file ColumnInfo.php.
    {
        return $this->scale;
    }
ColumnInfo::getSize ()
Get column size.
Returns:
int
Definition at line 154 of file ColumnInfo.php.
    {
        return $this->size;
    }
ColumnInfo::getTable ()
Get parent table.
Returns:
TableInfo
Definition at line 227 of file ColumnInfo.php.
    {
        return $this->table;
    }
ColumnInfo::getType ()
Get column type.
Returns:
int
Definition at line 136 of file ColumnInfo.php.
    {
        return $this->type;
    }
ColumnInfo::getVendorSpecificInfo ()
Get vendor specific optional information for this column.
Returns:
array vendorSpecificInfo[]
Definition at line 210 of file ColumnInfo.php.
    {
        return $this->vendorSpecificInfo;
    }
ColumnInfo::isAutoIncrement ()
Is column of autoincrement type?
Returns:
boolean
Definition at line 201 of file ColumnInfo.php.
Referenced by __construct().
    {
        return $this->isAutoIncrement === true;
    }
ColumnInfo::isNullable ()
Is column nullable?
Returns:
boolean
Definition at line 192 of file ColumnInfo.php.
Referenced by __construct().
    {
        return $this->isNullable;
    }
ColumnInfo::toString ()
Returns:
string
Definition at line 218 of file ColumnInfo.php.
    {
        return $this->name;
    }
Member Data Documentation
ColumnInfo::$defaultValue
Default value.
Definition at line 59 of file ColumnInfo.php.
ColumnInfo::$isAutoIncrement
Is autoincrement?
Definition at line 62 of file ColumnInfo.php.
ColumnInfo::$isNullable
Is nullable?
Definition at line 56 of file ColumnInfo.php.
ColumnInfo::$name
Column name.
Definition at line 38 of file ColumnInfo.php.
Referenced by __construct().
ColumnInfo::$nativeType
Column native type.
Definition at line 44 of file ColumnInfo.php.
Referenced by __construct().
ColumnInfo::$precision
Column presision.
Definition at line 50 of file ColumnInfo.php.
Referenced by __construct().
ColumnInfo::$scale
Column scale (number of digits after decimal).
Definition at line 53 of file ColumnInfo.php.
Referenced by __construct().
ColumnInfo::$size
Column length.
Definition at line 47 of file ColumnInfo.php.
Referenced by __construct().
ColumnInfo::$table
Table.
Definition at line 65 of file ColumnInfo.php.
ColumnInfo::$type
Column Creole type.
Definition at line 41 of file ColumnInfo.php.
Referenced by __construct().
ColumnInfo::$vendorSpecificInfo = array() [protected]
Definition at line 71 of file ColumnInfo.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/metadata/ColumnInfo.php