fareofficelib: SQLException Class Reference
SQLException Class Reference
Public Member Functions
__construct ($msg, $native=null, $userinfo=null)
Constructs a SQLException.
setUserInfo ($info)
Sets additional user / debug information for this error.
getUserInfo ()
Returns the additional / debug information for this error.
setNativeError ($msg)
Sets driver native error message.
getNativeError ()
Gets driver native error message.
toString ()
Protected Attributes
$userInfo
Information that provides additional information for context of Exception (e.g.
$nativeError
Native RDBMS error string.
Detailed Description
Definition at line 29 of file SQLException.php.
Constructor & Destructor Documentation
SQLException::__construct ($ msg, $ native = null, $ userinfo = null)
Constructs a SQLException.
Parameters:
string $msg Error message
string $native Native DB error message.
string $userinfo More info, e.g. the SQL statement or the connection string that caused the error.
Definition at line 43 of file SQLException.php.
References setNativeError(), and setUserInfo().
    {
        parent::__construct($msg);
        if ($native !== null) {
            $this->setNativeError($native);
        }
        if ($userinfo !== null) {
            $this->setUserInfo($userinfo);
        }
    }
Member Function Documentation
SQLException::getNativeError ()
Gets driver native error message.
Returns:
string
Definition at line 93 of file SQLException.php.
    {
        return $this->nativeError;
    }
SQLException::getUserInfo ()
Returns the additional / debug information for this error.
Returns:
array hash of user info properties.
Definition at line 71 of file SQLException.php.
    {
        return $this->userInfo;
    }
SQLException::setNativeError ($ msg)
Sets driver native error message.
Parameters:
string $info
Returns:
void
Definition at line 82 of file SQLException.php.
Referenced by __construct().
    {
        $this->nativeError = $msg;
        $this->message .= " [Native Error: " .$this->nativeError . "]";
    }
SQLException::setUserInfo ($ info)
Sets additional user / debug information for this error.
Parameters:
array $info
Returns:
void
Definition at line 60 of file SQLException.php.
Referenced by __construct(), and Creole::getConnection().
    {
        $this->userInfo = $info;
        $this->message .= " [User Info: " .$this->userInfo . "]";
    }
SQLException::toString ()
Deprecated:
This method only exists right now for easier compatibility w/ PHPUnit!
Definition at line 101 of file SQLException.php.
    {
        return $this->getMessage();
    }
Member Data Documentation
SQLException::$nativeError [protected]
Native RDBMS error string.
Definition at line 35 of file SQLException.php.
SQLException::$userInfo [protected]
Information that provides additional information for context of Exception (e.g.
SQL statement or DSN).
Definition at line 32 of file SQLException.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/SQLException.php