fareofficelib: UTShellCmd Class Reference
UTShellCmd Class Reference
[Unit Tests - Unit tests for all classes/functions in fareofficelib.]
Unit test for all functions in ShellCmd.class.php.
Public Member Functions
doTest ()
testExec ()
testSshExec ()
Detailed Description
Unit test for all functions in ShellCmd.class.php.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 8 of file UTShellCmd.class.php.
Member Function Documentation
UTShellCmd::doTest ()
Definition at line 10 of file UTShellCmd.class.php.
References testExec().
  {
    $this->testExec();
    // Hard to create general unit test for ssh functions
    // $this->testSshExec();
  }
UTShellCmd::testExec ()
Definition at line 17 of file UTShellCmd.class.php.
References ShellCmd::exec().
Referenced by doTest().
  {
    $this->setSectionLabel('exec');
    try
    {
      eval($this->needEqual('ShellCmd::exec("uname")', '"Linux\n"'));
      eval($this->needEqual('ShellCmd::exec("uptime | wc -l")', '"1\n"'));
      eval($this->needEqual('ShellCmd::exec("wc", "I may be synthetic, but I\'m not stupid.\n\n")', '"      2       8      41\n"'));
    }
    catch (Exception $e)
    {
      eval($this->needEmpty('$e->getMessage()'));
    }
    try
    {
      ShellCmd::exec("ls -2");
    }
    catch (Exception $e)
    {
      eval($this->needEqual('$e->getMessage()', '"ls: invalid option -- \'2\'\nTry `ls --help\' for more information.\n Exit code: 2"'));
    }
  }
UTShellCmd::testSshExec ()
Definition at line 42 of file UTShellCmd.class.php.
References ShellCmd::sshExec().
  {
    $this->setSectionLabel('sshExec');
    try
    {
      eval($this->needEqual('ShellCmd::sshExec("arlukin@localhost", "uname")', '"Linux\n"'));
      eval($this->needEqual('ShellCmd::sshExec("arlukin@localhost", "uptime | wc -l")', '"1\n"'));
      eval($this->needEqual('ShellCmd::sshExec("arlukin@localhost", "wc", "I may be synthetic, but I\'m not stupid.\n\n")', '"      2       8      41\n"'));
    }
    catch (Exception $e)
    {
      eval($this->needEmpty('$e->getMessage()'));
    }
    try
    {
      ShellCmd::sshExec("arlukin@localhost", "ls -2");
    }
    catch (Exception $e)
    {
      eval($this->needEqual('$e->getMessage()', '"ls: invalid option -- \'2\'\nTry `ls --help\' for more information.\n Exit code: 2"'));
    }
  }
The documentation for this class was generated from the following file:
Static/UnitTestHtDocs/FareOfficeLib/General/UTShellCmd.class.php