fareofficelib: standard Class Reference
standard Class Reference
[FOUnitTest]
This is the standard Unit Test Skin.
Public Member Functions
standard ()
Constructor.
begin ()
Write webpage header for the Unit Test Gui.
end ()
Write webpage footer for the Unit Test Gui.
writeGuiResult ($testResult)
Will write a html result from a UnitTest result.
getVariableInfo ($value)
Return an information string about a variable.
Private Member Functions
_writeHtmlHead ()
Write the html < head > tag.
_writeCSSStyle ()
Write a html < style > tag for the html < head > tag.
_writeToolBar ()
Write a toolbar with which you can control the GUI.
_writeStatusChanger ()
Write the GUI buttons [Only Report Fails] [Details About Fails].
_writeRunAllTests ()
Write the [RUN ALL TESTS] button.
_writeTestCaseNavigator ()
Write the [Back] [Next] buttons, to switch current test case.
_writeFileBrowser ()
Write a file browse list of all test cases/classes.
_writeStatus ()
Write status and statistics about the tests.
_getUrlArgument ($onlyReportFailes_=-1, $echoDetails_=-1, $currentTestCase_=-1, $runAllTests_=-1)
Used by writeFileBrowser to build the anchors (a href) on the test gui.
_getTestCount ()
Return at padded testCount number, ie.
_writeTestCaseName ($status_, $className_)
Will write the class name above all tests from one test class.
_writeSectionLabel ($status_, $sectionLabel_, $sectionTextArr_)
Write the section label set by setSectionLabel in the unitTest.
_writeSuccededTest ($type_, $code_)
Write output for a succeded test.
_writeFailedTest ($type_, $code_, $file_)
Write output for a failed test.
_writeFailDetails ($value1_, $value2_, $comment_)
Write details about a failed test.
_writeFailComment ($comment_)
Write a failed test comment set by setFailedComment in the unitTest.
_writeReturnVariable ($value1_, $value2_)
Write the variable that was returned from the failed test.
_writeExpectedReturnVariable ($value1_, $value2_)
Write the expected return result from the failed test.
Private Attributes
$_reportedCompareCount
Number of compares reported to the user.
$_testCount
Number of tests executed.
$_oldClassName
Used by _writeTestCaseName, to only write the class name label, once per test class.
Detailed Description
This is the standard Unit Test Skin.
The class that are responsible for all GUI output.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 12 of file Standard.class.php.
Member Function Documentation
standard::_getTestCount () [private]
Return at padded testCount number, ie.
Definition at line 354 of file Standard.class.php.
Referenced by _writeFailedTest(), and _writeSuccededTest().
  {
    return str_pad($this->_testCount, 4, '0', STR_PAD_LEFT);
  }
standard::_getUrlArgument ($ onlyReportFailes_ = -1, $ echoDetails_ = -1, $ currentTestCase_ = -1, $ runAllTests_ = -1) [private]
Used by writeFileBrowser to build the anchors (a href) on the test gui.
Definition at line 291 of file Standard.class.php.
References unitTestSkin::getParent().
Referenced by _writeFileBrowser(), _writeRunAllTests(), _writeStatusChanger(), and _writeTestCaseNavigator().
  {
    if ((int)$onlyReportFailes_ == -1)
    {
      $onlyReportFailes_ = $this->getParent()->getOnlyReportFailes();
    }
    if ((int)$echoDetails_ == -1)
    {
      $echoDetails_ = $this->getParent()->getReportFailDetails();
    }
    if ((int)$currentTestCase_ == -1)
    {
      $currentTestCase_ = $this->getParent()->getCurrentTestCase();
    }
    if ((int)$runAllTests_ == -1)
    {
      $runAllTests_ = 0;
    }
    $str  = '?formOnlyReportFailes=' . $onlyReportFailes_;
    $str .= '&formEchoDetails=' . $echoDetails_;
    $str .= '&formTestCase=' . $currentTestCase_;
    $str .= '&formRunAllTests=' . $runAllTests_;
    return $str;
  }
standard::_writeCSSStyle () [private]
Write a html < style > tag for the html < head > tag.
Definition at line 101 of file Standard.class.php.
Referenced by _writeHtmlHead().
  {
  ?>
    <style>
      <!--
      body
      {
        font-family: Courier New;
        font-size: 10pt;
      }
      h1
      {
        text-align:center;
      }
      h2
      {
        margin-bottom: 0px;
      }
      .contentarea, .filebrowser, .status, .bodyarea
      {
        margin: 5px;
        padding: 5px;
        width: auto;
        float: left;
        border: 1px solid #0000ff;
      }
      .toolbar
      {
        margin: 5px;
        padding: 5px;
        width: auto;
        border: 1px solid #0000ff;
        float: top;
      }
      .bodyarea
      {
        border: 0px
      }
      a:link, a:visited
      {
        color:"#003399";
        text-decoration: none;
      }
      a:hover
      {
        color: #FF00FF
      }
      td
      {
        font-size: 10pt;
        padding: 1px;
        vertical-align: top;
      }
      -->
    </style>
  <?php
  }
standard::_writeExpectedReturnVariable ($ value1_, $ value2_) [private]
Write the expected return result from the failed test.
Output looks like below.
First comes the output in form of a php formated array/variable.
A difference section that shows what difference are between return variable and expected return. It shows what was expected to be returned.
Return:
array ('0' => 1, '1' => 2, '2' => 3, '3' => 4)
Copy: 'array("0" => 1, "1" => 2, "2" => 3, "3" => 4)'
Difference:
Definition at line 529 of file Standard.class.php.
Referenced by _writeFailDetails().
  {
    echo('<i><b>Expected return:</b></i><br/>');
    if (is_array($value2_))
    {
      echo('<pre>'.getHtmlArrayPhp($value2_).'</pre>');
      echo('<br/>');
      echo('Difference:' . getHtmlArray(array_diff_assoc_recursive($value2_, $value1_)));
    }
    else
    {
      echo($this->getVariableInfo($value2_).'<br/>');
    }
  }
standard::_writeFailComment ($ comment_) [private]
Write a failed test comment set by setFailedComment in the unitTest.
Definition at line 448 of file Standard.class.php.
Referenced by _writeFailDetails().
  {
    if (!empty($comment_))
    {
      echo($comment_);
      echo('<br/>');
    }
  }
standard::_writeFailDetails ($ value1_, $ value2_, $ comment_) [private]
Write details about a failed test.
Definition at line 434 of file Standard.class.php.
References _writeExpectedReturnVariable(), _writeFailComment(), _writeReturnVariable(), and unitTestSkin::getParent().
Referenced by writeGuiResult().
  {
    if ($this->getParent()->getReportFailDetails())
    {
      $this->_writeFailComment($comment_);
      $this->_writeReturnVariable($value1_, $value2_);
      $this->_writeExpectedReturnVariable($value1_, $value2_);
      echo('<br/>');
    }
  }
standard::_writeFailedTest ($ type_, $ code_, $ file_) [private]
Write output for a failed test.
Definition at line 424 of file Standard.class.php.
References _getTestCount().
Referenced by writeGuiResult().
  {
    $this->_reportedCompareCount++;
    echo($this->_getTestCount() . ' <font color="red">ERROR - ' . $type_ . ' - ' . $code_ . '</font><br/>');
    echo('File: <font color="red">' . $file_ . '</font><br/>');
  }
standard::_writeFileBrowser () [private]
Write a file browse list of all test cases/classes.
Key is zerobased and currentTestCase starts at 1.
Definition at line 256 of file Standard.class.php.
References _getUrlArgument(), and unitTestSkin::getParent().
Referenced by end().
  {
    foreach($this->getParent()->getTestCaseFiles() as $key => $row)
    {
      if ($row['package'] != $oldPackage)
      {
        echo('<B>'.$row['package'].'</B><br/>');
        $oldPackage = $row['package'];
      }
      if ($key == $this->getParent()->getCurrentTestCase())
      {
        echo('<b>&nbsp;&nbsp;<a href="' . $this->_getUrlArgument(-1, -1, $key) . '">'.$row['class_name'] . '</a></b><br/>');
      }
      else
      {
        echo('&nbsp;&nbsp;<a href="' . $this->_getUrlArgument(-1, -1, $key) . '">'.$row['class_name'] . '</a><br/>');
      }
    }
  }
standard::_writeHtmlHead () [private]
Write the html < head > tag.
Definition at line 83 of file Standard.class.php.
References _writeCSSStyle().
Referenced by begin().
  {
    echo('<head>');
      echo('<title>');
        echo('FareOffice Unit Tester ');
      echo('</title>');
      echo('<meta name="author" content="Daniel Lindh, aka Arlukin, aka Master Po" />');
      echo('<meta name="robots" content="noindex,nofollow" />');
      echo('<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-15" />');
      $this->_writeCSSStyle();
    echo('</head>');
  }
standard::_writeReturnVariable ($ value1_, $ value2_) [private]
Write the variable that was returned from the failed test.
Output looks like below.
First comes the output in form of a php formated array/variable.
A copy section that can be used to copy directly into the test.
A difference section that shows what difference are between return variable and expected return. It shows what is returned.
Return:
array ('0' => 1, '1' => 2, '2' => 3, '3' => 4)
Copy: 'array("0" => 1, "1" => 2, "2" => 3, "3" => 4)'
Difference:
Definition at line 482 of file Standard.class.php.
References getHtmlArrayPhp().
Referenced by _writeFailDetails().
  {
    echo('<i><b>Return:</b></i><br/>');
    if (is_array($value1_))
    {
      $search = array("'", '"', '<br/>', "\t", '&nbsp;');
      $replace = array("\'", '\"', '', '', '');
      echo('<pre>' . getHtmlArrayPhp($value1_) . '</pre>');
      echo('Copy:<br/>\'' . str_replace($search, $replace, getHtmlArrayPhp($value1_)) . '\'<br/>');
      echo('<br/>');
      echo('Difference:' . getHtmlArray(array_diff_assoc_recursive($value1_, $value2_)));
    }
    else
    {
      $search = array("'", '"');
      $replace = array("\'", '\"');
      echo($this->getVariableInfo($value1_).'<br/>');
      echo('Copy:<br/>\'"' . htmlentities(str_replace($search, $replace, $value1_)).'"\'<br/>');
    }
  }
standard::_writeRunAllTests () [private]
Write the [RUN ALL TESTS] button.
Definition at line 217 of file Standard.class.php.
References _getUrlArgument().
Referenced by _writeToolBar().
  {
    echo('<a href="'.$this->_getUrlArgument(-1, -1, -1, true).'">[RUN ALL TESTS]</a>&nbsp;');
  }
standard::_writeSectionLabel ($ status_, $ sectionLabel_, $ sectionTextArr_) [private]
Write the section label set by setSectionLabel in the unitTest.
Definition at line 384 of file Standard.class.php.
References unitTestSkin::getParent().
Referenced by writeGuiResult().
  {
    if
    (
      $sectionLabel_ != $this->_oldSectionLabel &&
      (
        $status_ == false ||
        !$this->getParent()->getOnlyReportFailes()
      )
    )
    {
      echo('<br/>');
      echo('<b>' . $sectionLabel_ . '</b><br/>');
      foreach($sectionTextArr_ as $text)
      {
        echo($text . '<br/>');
      }
      $this->_oldSectionLabel = $sectionLabel_;
    }
  }
standard::_writeStatus () [private]
Write status and statistics about the tests.
Definition at line 280 of file Standard.class.php.
Referenced by end().
  {
    echo('Reported tests: ' . $this->_reportedCompareCount . '<br/>');
    echo('Executed tests: ' . $this->_testCount . '<br/>');
  }
standard::_writeStatusChanger () [private]
Write the GUI buttons [Only Report Fails] [Details About Fails].
Definition at line 181 of file Standard.class.php.
References _getUrlArgument(), and unitTestSkin::getParent().
Referenced by _writeToolBar().
  {
    if ($this->getParent()->getOnlyReportFailes())
    {
      echo('<b><a href="' . $this->_getUrlArgument(false, -1) . '">');
        echo('[Only Report Fails]');
      echo('</a></b>');
    }
    else
    {
      echo('<a href="' . $this->_getUrlArgument(true, -1) . '">');
        echo('[Only Report Fails]');
      echo('</a>');
    }
    echo('&nbsp;');
    if ($this->getParent()->getReportFailDetails())
    {
      echo('<b><a href="'.$this->_getUrlArgument(-1, false).'">');
        echo('[Details About Fails]');
      echo('</a></b>');
    }
    else
    {
      echo('<a href="'.$this->_getUrlArgument(-1, true).'">');
        echo('[Details About Fails]');
      echo('</a>');
    }
    echo('&nbsp;');
  }
standard::_writeSuccededTest ($ type_, $ code_) [private]
Write output for a succeded test.
Will not write any output if "only report fails" status is set.
Definition at line 412 of file Standard.class.php.
References _getTestCount(), and unitTestSkin::getParent().
Referenced by writeGuiResult().
  {
    if (!$this->getParent()->getOnlyReportFailes())
    {
      $this->_reportedCompareCount++;
      echo($this->_getTestCount() . ' OK - ' . $type_ . ' - ' . $code_ . '<br/>');
    }
  }
standard::_writeTestCaseName ($ status_, $ className_) [private]
Will write the class name above all tests from one test class.
Will not write the class name if bOnlyReportFailes is set.
Definition at line 364 of file Standard.class.php.
References unitTestSkin::getParent().
Referenced by writeGuiResult().
  {
    if
    (
      $className_ != $this->_oldClassName &&
      (
        $status_ == false ||
        !$this->getParent()->getOnlyReportFailes()
      )
    )
    {
      echo('<h2>' . $className_ . '</h2>');
      $this->_oldClassName = $className_;
    }
  }
standard::_writeTestCaseNavigator () [private]
Write the [Back] [Next] buttons, to switch current test case.
Definition at line 225 of file Standard.class.php.
References _getUrlArgument(), and unitTestSkin::getParent().
Referenced by _writeToolBar().
  {
    $currentTestCase = $this->getParent()->getCurrentTestCase();
    $total = $this->getParent()->getNumOfTestCases();
    if ($currentTestCase > 1)
    {
      echo('<b><a href="' . $this->_getUrlArgument(-1, -1, $currentTestCase-1) . '">[Back]</a></b>');
    }
    else
    {
      echo('[Back]');
    }
    echo(' ' . $currentTestCase . '/' . $total . ' ');
    if ($currentTestCase < $total )
    {
      echo('<b><a href="' . $this->_getUrlArgument(-1, -1, $currentTestCase+1) . '">[Next]</a></b>');
    }
    else
    {
      echo('[Next]');
    }
  }
standard::_writeToolBar () [private]
Write a toolbar with which you can control the GUI.
Definition at line 171 of file Standard.class.php.
References _writeRunAllTests(), _writeStatusChanger(), and _writeTestCaseNavigator().
Referenced by begin().
  {
    $this->_writeStatusChanger();
    $this->_writeRunAllTests();
    $this->_writeTestCaseNavigator();
  }
standard::begin ()
Write webpage header for the Unit Test Gui.
The execution order for the webpage building are begin(); writeGuiResult(); end();
These three functions should create a full html page with < html > < head >< body > etc.
Reimplemented from unitTestSkin.
Definition at line 34 of file Standard.class.php.
References _writeHtmlHead(), and _writeToolBar().
  {
    echo('<html>');
      $this->_writeHtmlHead();
      echo('<body>');
      echo('<div class="bodyarea">');
        echo('<h1>FareOffice Unit Tester</h1>');
        echo('<div class="toolbar">');
        $this->_writeToolBar();
        echo('</div>');
        echo('<div class="contentarea">');
  }
standard::end ()
Write webpage footer for the Unit Test Gui.
See also:
: begin()
Reimplemented from unitTestSkin.
Definition at line 55 of file Standard.class.php.
References _writeFileBrowser(), and _writeStatus().
  {
        if ($this->_testCount)
        {
          echo('<br/><b>Finish</b><br/>');
        }
        else
        {
          echo('You must choose a test case to run.');
        }
        echo('</div>');
        echo('<div class="filebrowser">');
        $this->_writeFileBrowser();
        echo('</div>');
        echo('<div class="status">');
        $this->_writeStatus();
        echo('</div>');
      echo('</div>');
      echo('</body>');
    echo('</html>');
  }
standard::getVariableInfo ($ value)
Return an information string about a variable.
ie. string(6) "Daniel"
Definition at line 549 of file Standard.class.php.
  {
    if (is_bool($value) )
    {
      if ($value)
      {
        $humanReadableValue = 'true';
      }
      else
      {
        $humanReadableValue = 'false';
      }
    }
    else
    {
      $humanReadableValue = $value;
    }
    return gettype($value).'('.strlen($value).') "'.$humanReadableValue.'"';
  }
standard::standard ()
Constructor.
Definition at line 17 of file Standard.class.php.
  {
    $this->_testCount = 0;
    $this->_reportedCompareCount = 0;
  }
standard::writeGuiResult ($ testResult)
Will write a html result from a UnitTest result.
See also:
: begin()
Reimplemented from unitTestSkin.
Definition at line 331 of file Standard.class.php.
References $_testCount, _writeFailDetails(), _writeFailedTest(), _writeSectionLabel(), _writeSuccededTest(), and _writeTestCaseName().
  {
    foreach($testResult as $_testCount => $row)
    {
      $this->_testCount++;
      $this->_writeTestCaseName($row['status'], $row['class_name']);
      $this->_writeSectionLabel($row['status'], $row['section_label'], $row['section_text']);
      if ($row['status'] == true)
      {
        $this->_writeSuccededTest($row['type'], $row['code']);
      }
      else
      {
        $this->_writeFailedTest($row['type'], $row['code'], $row['file']);
        $this->_writeFailDetails($row['return'], $row['expected_return'], $row['fail_comment']);
      }
    }
  }
Member Data Documentation
standard::$_oldClassName [private]
Used by _writeTestCaseName, to only write the class name label, once per test class.
Definition at line 584 of file Standard.class.php.
standard::$_reportedCompareCount [private]
Number of compares reported to the user.
Definition at line 573 of file Standard.class.php.
standard::$_testCount [private]
Number of tests executed.
Definition at line 578 of file Standard.class.php.
Referenced by writeGuiResult().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/FOUnitTest/Skins/Standard.class.php