fareofficelib: smtp Class Reference
smtp Class Reference
Public Member Functions
__construct ($params=array())
Constructor function.
connect ($params=array())
Connect function.
send ($params=array())
Function which handles sending the mail.
set ($var, $value)
Sets a variable.
getErrors ()
Function to return the errors array.
Private Member Functions
helo ()
Function to implement HELO cmd.
ehlo ()
Function to implement EHLO cmd.
rset ()
Function to implement RSET cmd.
quit ()
Function to implement QUIT cmd.
auth ()
Function to implement AUTH cmd.
mail ($from)
Function that handles the MAIL FROM: cmd.
rcpt ($to)
Function that handles the RCPT TO: cmd.
data ()
Function that sends the DATA cmd.
is_connected ()
Function to determine if this object is connected to the server or not.
send_data ($data)
Function to send a bit of data.
get_data ()
Function to get data.
Private Attributes
$authenticated
$connection
$recipients
$headers
$timeout
$errors
$status
$body
$from
$host
$port
$helo
$auth
$user
$pass
Detailed Description
Definition at line 18 of file smtp.php.
Constructor & Destructor Documentation
smtp::__construct ($ params = array())
Constructor function.
Arguments: $params - An assoc array of parameters:
host - The hostname of the smtp server Default: localhost port - The port the smtp server runs on Default: 25 helo - What to send as the HELO command Default: localhost (typically the hostname of the machine this script runs on) auth - Whether to use basic authentication Default: FALSE user - Username for authentication Default: <blank> pass - Password for authentication Default: <blank> timeout - The timeout in seconds for the call Default: 5 to fsockopen()
Definition at line 51 of file smtp.php.
References auth(), and helo().
    {
        if(!defined('CRLF'))
            define('CRLF', "\r\n", TRUE);
        $this->authenticated = FALSE;
        $this->timeout       = 5;
        $this->status        = SMTP_STATUS_NOT_CONNECTED;
        $this->host          = 'localhost';
        $this->port          = 25;
        $this->helo          = 'localhost';
        $this->auth          = FALSE;
        $this->user          = '';
        $this->pass          = '';
        $this->errors        = array();
        foreach($params as $key => $value){
            $this->$key = $value;
        }
    }
Member Function Documentation
smtp::auth () [private]
Function to implement AUTH cmd.
Definition at line 240 of file smtp.php.
References get_data(), and send_data().
Referenced by __construct(), connect(), and send().
    {
        if (is_resource($this->connection)
                AND $this->send_data('AUTH LOGIN')
                AND substr(trim($error = $this->get_data()), 0, 3) === '334'
                AND $this->send_data(base64_encode($this->user))      // Send username
                AND substr(trim($error = $this->get_data()),0,3) === '334'
                AND $this->send_data(base64_encode($this->pass))      // Send password
                AND substr(trim($error = $this->get_data()),0,3) === '235' ){
            $this->authenticated = true;
            return true;
        } else {
            $this->errors[] = 'AUTH command failed: ' . trim(substr(trim($error),3));
            return false;
        }
    }
smtp::connect ($ params = array())
Connect function.
This will, when called statically, create a new smtp object, call the connect function (ie this function) and return it. When not called statically, it will connect to the server and send the HELO command.
Definition at line 81 of file smtp.php.
References auth(), ehlo(), get_data(), and helo().
Referenced by Rmail::send().
    {
        if (!isset($this->status)) {
            $obj = new smtp($params);
            if($obj->connect()){
                $obj->status = SMTP_STATUS_CONNECTED;
            }
            return $obj;
        } else {
            $this->connection = fsockopen($this->host, $this->port, $errno, $errstr, $this->timeout);
            if (function_exists('socket_set_timeout')) {
                @socket_set_timeout($this->connection, 5, 0);
            }
            $greeting = $this->get_data();
            if (is_resource($this->connection)) {
                return $this->auth ? $this->ehlo() : $this->helo();
            } else {
                $this->errors[] = 'Failed to connect to server: '.$errstr;
                return FALSE;
            }
        }
    }
smtp::data () [private]
Function that sends the DATA cmd.
Definition at line 295 of file smtp.php.
References get_data(), is_connected(), and send_data().
Referenced by send().
    {
        if($this->is_connected()
            AND $this->send_data('DATA')
            AND substr(trim($error = $this->get_data()), 0, 3) === '354' ) {
            return true;
        } else {
            $this->errors[] = trim(substr(trim($error), 3));
            return false;
        }
    }
smtp::ehlo () [private]
Function to implement EHLO cmd.
Definition at line 187 of file smtp.php.
References get_data(), helo(), and send_data().
Referenced by connect().
    {
        if (is_resource($this->connection)
                AND $this->send_data('EHLO '.$this->helo)
                AND substr(trim($error = $this->get_data()), 0, 3) === '250' ){
            return true;
        } else {
            $this->errors[] = 'EHLO command failed, output: ' . trim(substr(trim($error),3));
            return false;
        }
    }
smtp::get_data () [private]
Function to get data.
Definition at line 334 of file smtp.php.
Referenced by auth(), connect(), data(), ehlo(), helo(), mail(), quit(), rcpt(), rset(), and send().
    {
        $return = '';
        $line   = '';
        $loops  = 0;
        if(is_resource($this->connection)){
            while((strpos($return, CRLF) === FALSE OR substr($line,3,1) !== ' ') AND $loops < 100){
                $line    = fgets($this->connection, 512);
                $return .= $line;
                $loops++;
            }
            return $return;
        }else
            return false;
    }
smtp::getErrors ()
Function to return the errors array.
Definition at line 364 of file smtp.php.
    {
        return $this->errors;
    }
smtp::helo () [private]
Function to implement HELO cmd.
Definition at line 170 of file smtp.php.
References get_data(), and send_data().
Referenced by __construct(), connect(), and ehlo().
    {
        if(is_resource($this->connection)
                AND $this->send_data('HELO '.$this->helo)
                AND substr(trim($error = $this->get_data()), 0, 3) === '250' ){
            return true;
        } else {
            $this->errors[] = 'HELO command failed, output: ' . trim(substr(trim($error),3));
            return false;
        }
    }
smtp::is_connected () [private]
Function to determine if this object is connected to the server or not.
Definition at line 313 of file smtp.php.
Referenced by data(), mail(), rcpt(), and send().
    {
        return (is_resource($this->connection) AND ($this->status === SMTP_STATUS_CONNECTED));
    }
smtp::mail ($ from) [private]
Function that handles the MAIL FROM: cmd.
Definition at line 262 of file smtp.php.
References $from, get_data(), is_connected(), and send_data().
Referenced by send().
    {
        if ($this->is_connected()
            AND $this->send_data('MAIL FROM:<'.$from.'>')
            AND substr(trim($this->get_data()), 0, 2) === '250' ) {
            return true;
        } else {
            return false;
        }
    }
smtp::quit () [private]
Function to implement QUIT cmd.
Definition at line 221 of file smtp.php.
References get_data(), and send_data().
    {
        if(is_resource($this->connection)
                AND $this->send_data('QUIT')
                AND substr(trim($error = $this->get_data()), 0, 3) === '221' ){
            fclose($this->connection);
            $this->status = SMTP_STATUS_NOT_CONNECTED;
            return true;
        } else {
            $this->errors[] = 'QUIT command failed, output: ' . trim(substr(trim($error),3));
            return false;
        }
    }
smtp::rcpt ($ to) [private]
Function that handles the RCPT TO: cmd.
Definition at line 278 of file smtp.php.
References get_data(), is_connected(), and send_data().
Referenced by send().
    {
        if($this->is_connected()
            AND $this->send_data('RCPT TO:<'.$to.'>')
            AND substr(trim($error = $this->get_data()), 0, 2) === '25' ){
            return true;
        } else {
            $this->errors[] = trim(substr(trim($error), 3));
            return false;
        }
    }
smtp::rset () [private]
Function to implement RSET cmd.
Definition at line 204 of file smtp.php.
References get_data(), and send_data().
    {
        if (is_resource($this->connection)
                AND $this->send_data('RSET')
                AND substr(trim($error = $this->get_data()), 0, 3) === '250' ){
            return true;
        } else {
            $this->errors[] = 'RSET command failed, output: ' . trim(substr(trim($error),3));
            return false;
        }
    }
smtp::send ($ params = array())
Function which handles sending the mail.
Arguments: $params - Optional assoc array of parameters. Can contain: recipients - Indexed array of recipients from - The from address. (used in MAIL FROM:), this will be the return path headers - Indexed array of headers, one header per array entry body - The body of the email It can also contain any of the parameters from the connect() function
Definition at line 120 of file smtp.php.
References $body, $headers, $result, auth(), data(), get_data(), is_connected(), mail(), rcpt(), and send_data().
    {
        foreach ($params as $key => $value) {
            $this->set($key, $value);
        }
        if ($this->is_connected()) {
            // Do we auth or not? Note the distinction between the auth variable and auth() function
            if ($this->auth AND !$this->authenticated) {
                if(!$this->auth())
                    return false;
            }
            $this->mail($this->from);
            if (is_array($this->recipients)) {
                foreach ($this->recipients as $value) {
                    $this->rcpt($value);
                }
            } else {
                $this->rcpt($this->recipients);
            }
            if (!$this->data()) {
                return false;
            }
            // Transparency
            $headers = str_replace(CRLF.'.', CRLF.'..', trim(implode(CRLF, $this->headers)));
            $body    = str_replace(CRLF.'.', CRLF.'..', $this->body);
            $body    = substr($body, 0, 1) == '.' ? '.'.$body : $body;
            $this->send_data($headers);
            $this->send_data('');
            $this->send_data($body);
            $this->send_data('.');
            $result = (substr(trim($this->get_data()), 0, 3) === '250');
            //$this->rset();
            return $result;
        } else {
            $this->errors[] = 'Not connected!';
            return FALSE;
        }
    }
smtp::send_data ($ data) [private]
Function to send a bit of data.
Definition at line 321 of file smtp.php.
Referenced by auth(), data(), ehlo(), helo(), mail(), quit(), rcpt(), rset(), and send().
    {
        if(is_resource($this->connection)){
            return fwrite($this->connection, $data.CRLF, strlen($data)+2);
        } else {
            return false;
        }
    }
smtp::set ($ var, $ value)
Sets a variable.
Definition at line 355 of file smtp.php.
    {
        $this->$var = $value;
        return true;
    }
Member Data Documentation
smtp::$auth [private]
Definition at line 32 of file smtp.php.
smtp::$authenticated [private]
Definition at line 20 of file smtp.php.
smtp::$body [private]
Definition at line 27 of file smtp.php.
Referenced by send().
smtp::$connection [private]
Definition at line 21 of file smtp.php.
smtp::$errors [private]
Definition at line 25 of file smtp.php.
smtp::$from [private]
Definition at line 28 of file smtp.php.
Referenced by mail().
smtp::$headers [private]
Definition at line 23 of file smtp.php.
Referenced by send().
smtp::$helo [private]
Definition at line 31 of file smtp.php.
smtp::$host [private]
Definition at line 29 of file smtp.php.
smtp::$pass [private]
Definition at line 34 of file smtp.php.
smtp::$port [private]
Definition at line 30 of file smtp.php.
smtp::$recipients [private]
Definition at line 22 of file smtp.php.
smtp::$status [private]
Definition at line 26 of file smtp.php.
smtp::$timeout [private]
Definition at line 24 of file smtp.php.
smtp::$user [private]
Definition at line 33 of file smtp.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/Rmail/smtp.php