fareofficelib: UTPhpCronTab Class Reference
UTPhpCronTab Class Reference
[Unit Tests - Unit tests for all classes/functions in fareofficelib.]
Unit test for all functions in PhpCronTab.php.
Public Member Functions
doTest ()
_testCheckMinute ()
_testCheckHour ()
_testCheckDayOfMonth ()
_testCheckMonth ()
_testCheckDayOfWeek ()
Private Member Functions
_testGetCurrentTime ()
Detailed Description
Unit test for all functions in PhpCronTab.php.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 8 of file UTPhpCronTab.php.
Member Function Documentation
UTPhpCronTab::_testCheckDayOfMonth ()
Definition at line 116 of file UTPhpCronTab.php.
Referenced by doTest().
  {
    $this->setSectionLabel('checkDayOfMonth');
    $phpCronTab = new PhpCronTab;
    $phpCronTab->setCurrentTime(strtotime("2009-05-02 12:02"));
    $phpCronTab->addUnixFormatEx('*', '*', '45', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', 's', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '0', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '1', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '3', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '2', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
  }
UTPhpCronTab::_testCheckDayOfWeek ()
Definition at line 167 of file UTPhpCronTab.php.
Referenced by doTest().
  {
    $this->setSectionLabel('checkDayOfWeek');
    $phpCronTab = new PhpCronTab;
    $phpCronTab->setCurrentTime(strtotime("2009-05-02 12:02"));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '23');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '0');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '1');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '2');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '3');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '4');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '5');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '7');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '8');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '6');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
  }
UTPhpCronTab::_testCheckHour ()
Definition at line 83 of file UTPhpCronTab.php.
Referenced by doTest().
  {
    $this->setSectionLabel('checkClock hour');
    $phpCronTab = new PhpCronTab;
    $phpCronTab->setCurrentTime(strtotime("2009-05-02 12:02"));
    $phpCronTab->addUnixFormatEx('*', '13', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*/10', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('*', '*/2', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('*', '*/4', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('*', '12', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('2', '12', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
  }
UTPhpCronTab::_testCheckMinute ()
Definition at line 30 of file UTPhpCronTab.php.
Referenced by doTest().
  {
    $this->setSectionLabel('checkClock minute');
    $phpCronTab = new PhpCronTab;
    $phpCronTab->setCurrentTime(strtotime("2009-05-02 12:02"));
    $phpCronTab->addUnixFormatEx('1', '*', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*/3', '*', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('*/1', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('2', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('1-10', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('1-1', '*', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('3-60', '*', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('1,3,5,8', '*', '*', '*', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('5,4,2,3', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('6,7,2', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('2,6,7', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->clearUnixFormat();
    $phpCronTab->addUnixFormatEx('*', '*', '*', '*', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
  }
UTPhpCronTab::_testCheckMonth ()
Definition at line 141 of file UTPhpCronTab.php.
Referenced by doTest().
  {
    $this->setSectionLabel('checkMonth');
    $phpCronTab = new PhpCronTab;
    $phpCronTab->setCurrentTime(strtotime("2009-05-02 12:02"));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '33', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '-2', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '2', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '4', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '6', '*');
    eval($this->needFalse('$phpCronTab->isTimeToExecute()'));
    $phpCronTab->addUnixFormatEx('*', '*', '*', '5', '*');
    eval($this->needTrue('$phpCronTab->isTimeToExecute()'));
  }
UTPhpCronTab::_testGetCurrentTime () [private]
Definition at line 20 of file UTPhpCronTab.php.
Referenced by doTest().
  {
    $this->setSectionLabel('getCurrentTime');
    $phpCronTab = new PhpCronTab;
    $time = time();
    $phpCronTab->setCurrentTime($time);
    eval($this->needEqual('$phpCronTab->getCurrentTime()', '$time'));
  }
UTPhpCronTab::doTest ()
Definition at line 10 of file UTPhpCronTab.php.
References _testCheckDayOfMonth(), _testCheckDayOfWeek(), _testCheckHour(), _testCheckMinute(), _testCheckMonth(), and _testGetCurrentTime().
  {
    $this->_testGetCurrentTime();
    $this->_testCheckMinute();
    $this->_testCheckHour();
    $this->_testCheckDayOfMonth();
    $this->_testCheckMonth();
    $this->_testCheckDayOfWeek();
  }
The documentation for this class was generated from the following file:
Static/UnitTestHtDocs/FareOfficeLib/General/UTPhpCronTab.php