fareofficelib: Static/PhpInclude/FareOfficeLib/3dPart/Rmail/example.php File Reference
Static/PhpInclude/FareOfficeLib/3dPart/Rmail/example.php File Reference
Variables
$mail = new Rmail()
o------------------------------------------------------------------------------o | This package is licensed under the Phpguru license.
$address = 'fruity@licious.com'
Send the email.
$result = $mail->send(array($address))
Variable Documentation
$address = 'fruity@licious.com'
Send the email.
Pass the method an array of recipients.
Definition at line 65 of file example.php.
Referenced by Rmail::send().
$mail = new Rmail()
o------------------------------------------------------------------------------o | This package is licensed under the Phpguru license.
A quick summary is | | that for commercial use, there is a small one-time licensing fee to pay. For | | registered charities and educational institutes there is a reduced license | | fee available. You can read more at: | | | | http://www.phpguru.org/static/license.html | o------------------------------------------------------------------------------o
© Copyright 2008,2009 Richard Heyes
Definition at line 17 of file example.php.
Referenced by Communication::sendEmail().
$result = $mail->send(array($address))
Definition at line 66 of file example.php.
Referenced by FOUnitTest::_fillWithFilesFromDir(), _getHtmlArrayBody(), _getHtmlArrayHeader(), _getHtmlArrayInnerArray(), Url::absUrl(), SQLiteConnection::beginTrans(), PgSQLConnection::beginTrans(), MySQLConnection::beginTrans(), MSSQLConnection::beginTrans(), SQLiteConnection::commitTrans(), PgSQLConnection::commitTrans(), OCI8Connection::commitTrans(), ODBCConnection::commitTrans(), MySQLConnection::commitTrans(), MSSQLConnection::commitTrans(), SQLiteConnection::executeQuery(), PgSQLConnection::executeQuery(), OCI8PreparedStatement::executeQuery(), OCI8Connection::executeQuery(), MySQLiConnection::executeQuery(), MySQLConnection::executeQuery(), MSSQLConnection::executeQuery(), SQLiteConnection::executeUpdate(), PgSQLConnection::executeUpdate(), MySQLiConnection::executeUpdate(), MySQLConnection::executeUpdate(), MSSQLConnection::executeUpdate(), fileList(), getHtmlArray(), MySQLiIdGenerator::getId(), MySQLIdGenerator::getId(), OCI8Connection::getUpdateCount(), MSSQLConnection::getUpdateCount(), PgSQLTableInfo::initColumns(), ODBCTableInfo::initColumns(), PgSQLTableInfo::initForeignKeys(), ODBCTableInfo::initForeignKeys(), MySQLTableInfo::initForeignKeys(), PgSQLTableInfo::initIndexes(), PgSQLTableInfo::initPrimaryKey(), ODBCTableInfo::initPrimaryKey(), PgSQLDatabaseInfo::initSequences(), SQLiteDatabaseInfo::initTables(), PgSQLDatabaseInfo::initTables(), ODBCDatabaseInfo::initTables(), MySQLiDatabaseInfo::initTables(), MySQLDatabaseInfo::initTables(), MSSQLDatabaseInfo::initTables(), ODBCTypes::loadTypeMap(), OCI8Connection::nativeError(), PgSQLTableInfo::processDomain(), SQLiteConnection::rollbackTrans(), PgSQLConnection::rollbackTrans(), OCI8Connection::rollbackTrans(), ODBCConnection::rollbackTrans(), MySQLConnection::rollbackTrans(), MSSQLConnection::rollbackTrans(), smtp::send(), and Rmail::send().