fareofficelib: ODBCResultSetCommon Class Reference
ODBCResultSetCommon Class Reference
Public Member Functions
__construct (Connection $conn, $result, $fetchmode=null)
close ()
_setOffset ($offset)
This function exists to set offset after ResultSet is instantiated.
_setLimit ($limit)
This function exists to set limit after ResultSet is instantiated.
getFieldNum ($colname)
If fetchmode is FETCHMODE_ASSOC, returns the 1-based field index number for the specified column name.
Protected Member Functions
readLobData ($column, $binmode, $curdata=null)
Reads in any unread LOB data.
checkFetchMode (&$row)
Converts row fields to names if FETCHMODE_ASSOC is set.
Protected Attributes
$offset = 0
$limit = 0
Detailed Description
Definition at line 32 of file ODBCResultSetCommon.php.
Constructor & Destructor Documentation
ODBCResultSetCommon::__construct (Connection $ conn, $ result, $ fetchmode = null)
See also:
ResultSet::__construct()
Reimplemented from ResultSetCommon.
Reimplemented in ODBCResultSet.
Definition at line 49 of file ODBCResultSetCommon.php.
References ResultSetCommon::$fetchmode, and ResultSetCommon::$result.
    {
        parent::__construct($conn, $result, $fetchmode);
    }
Member Function Documentation
ODBCResultSetCommon::_setLimit ($ limit)
This function exists to set limit after ResultSet is instantiated.
This function should be "protected" in Java sense: only available to classes in package. THIS METHOD SHOULD NOT BE CALLED BY ANYTHING EXCEPTION DRIVER CLASSES.
Parameters:
int $limit New limit. protected
Definition at line 88 of file ODBCResultSetCommon.php.
References $limit.
    {
        $this->limit = $limit;
    }
ODBCResultSetCommon::_setOffset ($ offset)
This function exists to set offset after ResultSet is instantiated.
This function should be "protected" in Java sense: only available to classes in package. THIS METHOD SHOULD NOT BE CALLED BY ANYTHING EXCEPTION DRIVER CLASSES.
Parameters:
int $offset New offset. protected
Definition at line 76 of file ODBCResultSetCommon.php.
References $offset.
    {
        $this->offset = $offset;
    }
ODBCResultSetCommon::checkFetchMode (&$ row) [protected]
Converts row fields to names if FETCHMODE_ASSOC is set.
Parameters:
array& Row to convert.
Returns:
array& Converted row.
Definition at line 165 of file ODBCResultSetCommon.php.
References ResultSet::FETCHMODE_ASSOC.
Referenced by ODBCResultSet::next(), and ODBCCachedResultSet::next().
    {
        if ($this->fetchmode == ResultSet::FETCHMODE_ASSOC)
        {
            $newrow = array();
            for ($i = 0, $n = count($row); $i < $n; $i++)
            {
                $colname = @odbc_field_name($this->result->getHandle(), $i+1);
                if ($this->lowerAssocCase) {
                    $colname = strtolower($colname);
                }
                $newrow[$colname] = $row[$i];
            }
            $row =& $newrow;
        }
        return $row;
    }
ODBCResultSetCommon::close ()
See also:
ResultSet::close()
Reimplemented in ODBCCachedResultSet, and ODBCResultSet.
Definition at line 57 of file ODBCResultSetCommon.php.
    {
        $this->result = null;
        $this->conn = null;
        $this->fetchmode = null;
        $this->cursorPos = 0;
        $this->fields = null;
        $this->lowerAssocCase = false;
        $this->limit = 0;
        $this->offset = 0;
    }
ODBCResultSetCommon::getFieldNum ($ colname)
If fetchmode is FETCHMODE_ASSOC, returns the 1-based field index number for the specified column name.
Otherwise returns 0 (false).
Returns:
int
Definition at line 98 of file ODBCResultSetCommon.php.
References ResultSet::FETCHMODE_ASSOC.
Referenced by readLobData().
    {
        $fieldnum = 0;
        if ($this->fetchmode == ResultSet::FETCHMODE_ASSOC)
        {
            $keys = array_keys($this->fields);
            $fieldnum = array_search($colname, $keys);
        }
        return $fieldnum;
    }
ODBCResultSetCommon::readLobData ($ column, $ binmode, $ curdata = null) [protected]
Reads in any unread LOB data.
For long char fields, we may already have up to odbc_longreadlen() bytes in the buffer. These are passed in via the $curdata parm. For long binary fields, no data is read initially since odbc_binmode() is set to ODBC_BINMODE_PASSTHRU. This method adjusts the binmode and longreadlen to finish reading these datatypes into the buffer. Returns a string with the complete contents.
Parameters:
int|string $column Column index or name to read data from.
int $binmode ODBC_BINMODE_RETURN for binary data, ODBC_BINMODE_CONVERT for char data.
string $curdata Existing LOB data already in buffer.
Returns:
string
Definition at line 125 of file ODBCResultSetCommon.php.
References getFieldNum().
Referenced by ODBCResultSet::getBlob(), ODBCResultSet::getClob(), and ODBCCachedResultSet::loadCache().
    {
        // Retrieve field num
        $fldNum = (is_int($column) ? $column : getFieldNum($column));
        $data = $curdata;
        $newdata = null;
        // Adjust binmode and longreadlen
        odbc_binmode($this->result->getHandle(), $binmode);
        odbc_longreadlen($this->result->getHandle(), 4096);
        while (1)
        {
            $newdata = odbc_result($this->result->getHandle(), $fldNum);
            if ($newdata === false)
                break;
            else
                $data .= $newdata;
        }
        // Restore the default binmode and longreadlen
        odbc_binmode($this->result->getHandle(), ODBC_BINMODE_PASSTHRU);
        odbc_longreadlen($this->result->getHandle(), ini_get('odbc.defaultlrl'));
        // The ODBC driver I use seems to return a string with an escaped
        // null char at the end for clob data.
        $data = rtrim($data, "\x0");
        return $data;
    }
Member Data Documentation
ODBCResultSetCommon::$limit = 0 [protected]
Definition at line 44 of file ODBCResultSetCommon.php.
Referenced by _setLimit().
ODBCResultSetCommon::$offset = 0 [protected]
Definition at line 38 of file ODBCResultSetCommon.php.
Referenced by _setOffset().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCResultSetCommon.php