fareofficelib: ODBCPreparedStatement Class Reference
ODBCPreparedStatement Class Reference
Public Member Functions
executeQuery ()
executeUpdate ($params=null)
setNull ($paramIndex)
setBlob ($paramIndex, $blob)
setClob ($paramIndex, $clob)
Protected Member Functions
replaceParams ()
This does nothing since ODBC natively supports prepared statements.
_execute ($sql, $params, $fetchmode, $isupdate)
Internal function to call native ODBC prepare/execute functions.
escape ($str)
Detailed Description
Definition at line 33 of file ODBCPreparedStatement.php.
Member Function Documentation
ODBCPreparedStatement::_execute ($ sql, $ params, $ fetchmode, $ isupdate) [protected]
Internal function to call native ODBC prepare/execute functions.
Definition at line 50 of file ODBCPreparedStatement.php.
References PreparedStatementCommon::$sql.
Referenced by executeQuery(), and executeUpdate().
    {
        if ($this->resultSet)
        {
            $this->resultSet->close();
            $this->resultSet = null;
        }
        $this->updateCount = null;
        if ($this->conn->getAdapter()->emulatePrepareStmt())
        {
            $stmt = @odbc_exec($this->conn->getResource(), $sql);
            $ret = ($stmt !== false);
        }
        else
        {
            // Trim surrounding quotes added from default set methods.
            // Exception: for LOB-based parameters, odbc_execute() will
            // accept a filename surrounded by single-quotes.
            foreach ($this->boundInVars as $idx => $var)
            {
                if ($var instanceof Lob)
                {
                    $file = ($isupdate ? $var->getInputFile() : $var->getOutputFile());
                    $this->boundInVars[$idx] = "'$file'";
                }
                else if (is_string($var))
                {
                    $this->boundInVars[$idx] = trim($var, "\"\'");
                }
            }
            $stmt = @odbc_prepare($this->conn->getResource(), $sql);
            if ($stmt === FALSE)
                throw new SQLException('Could not prepare query', $this->conn->nativeError(), $sql);
            $ret = @odbc_execute($stmt, $this->boundInVars);
        }
        if ($ret === FALSE)
        {
            @odbc_free_result($stmt);
            throw new SQLException('Could not execute query', $this->conn->nativeError(), $sql);
        }
        return $this->conn->createResultSet(new ODBCResultResource($stmt), $fetchmode);
    }
ODBCPreparedStatement::escape ($ str) [protected]
See also:
PreparedStatementCommon::escape()
Reimplemented from PreparedStatementCommon.
Definition at line 170 of file ODBCPreparedStatement.php.
Referenced by setBlob(), and setClob().
    {
        if ($this->conn->getAdapter()->emulatePrepareStmt())
            return $this->conn->getAdapter()->escape($str);
        // Nothing to do here. odbc_execute() takes care of escaping strings.
        return $str;
    }
ODBCPreparedStatement::executeQuery ()
See also:
PreparedStatement::executeQuery()
Implements PreparedStatement.
Definition at line 103 of file ODBCPreparedStatement.php.
References PreparedStatementCommon::$sql, _execute(), and replaceParams().
    {
        switch (func_num_args()) {
        case 2:
        list($params, $fetchmode) = func_get_args();
            if (!is_array($params)) {
                unset($params);
            }
            break;
        case 1:
            $params = null;
            list($fetchmode) = func_get_args();
            break;
        case 0:
            $params = null;
            $fetchmode = null;
            break;
        }
        // Set any params passed directly
        if (isset($params)) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        $sql = $this->replaceParams();
        if ($this->conn->getAdapter()->hasLimitOffset())
        {
            if ($this->limit > 0 || $this->offset > 0)
                $this->conn->applyLimit($sql, $this->offset, $this->limit);
        }
        $this->resultSet = $this->_execute($sql, $params, $fetchmode, false);
        if (!$this->conn->getAdapter()->hasLimitOffset())
        {
            $this->resultSet->_setOffset($this->offset);
            $this->resultSet->_setLimit($this->limit);
        }
        return $this->resultSet;
    }
ODBCPreparedStatement::executeUpdate ($ params = null)
See also:
PreparedStatement::executeUpdate()
Reimplemented from PreparedStatementCommon.
Definition at line 151 of file ODBCPreparedStatement.php.
References PreparedStatementCommon::$sql, _execute(), and replaceParams().
    {
        // Set any params passed directly
        if ($params) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        $sql = $this->replaceParams();
        $this->_execute($sql, $params, 0, true);
        $this->updateCount = $this->conn->getUpdateCount();
        return $this->updateCount;
    }
ODBCPreparedStatement::replaceParams () [protected]
This does nothing since ODBC natively supports prepared statements.
See also:
PreparedStatementCommon::replaceParams()
Reimplemented from PreparedStatementCommon.
Definition at line 39 of file ODBCPreparedStatement.php.
Referenced by executeQuery(), and executeUpdate().
    {
        if ($this->conn->getAdapter()->emulatePrepareStmt())
            return parent::replaceParams();
        else
            return $this->sql;
    }
ODBCPreparedStatement::setBlob ($ paramIndex, $ blob)
See also:
PreparedStatement::setBlob()
Reimplemented from PreparedStatementCommon.
Definition at line 191 of file ODBCPreparedStatement.php.
References escape(), and setNull().
    {
        if ($this->conn->getAdapter()->emulatePrepareStmt())
            return parent::setBlob($paramIndex, $blob);
      $this->sql_cache_valid = false;
        if ($blob === null)
        {
            $this->setNull($paramIndex);
            return;
        }
        if ($blob instanceof Blob)
        {
            if ($blob->isFromFile() && !$blob->isModified())
            {
                $this->boundInVars[$paramIndex] = $blob;
                return;
            }
            $blob = $blob->__toString();
        }
        $this->boundInVars[$paramIndex] = "'" . $this->escape($blob) . "'";
    }
ODBCPreparedStatement::setClob ($ paramIndex, $ clob)
See also:
PreparedStatement::setClob()
Reimplemented from PreparedStatementCommon.
Definition at line 220 of file ODBCPreparedStatement.php.
References escape(), and setNull().
    {
        if ($this->conn->getAdapter()->emulatePrepareStmt())
            return parent::setClob($paramIndex, $clob);
      $this->sql_cache_valid = false;
        if ($clob === null)
        {
            $this->setNull($paramIndex);
            return;
        }
        if ($clob instanceof Clob)
        {
            if ($clob->isFromFile() && !$clob->isModified())
            {
                $this->boundInVars[$paramIndex] = $clob;
                return;
            }
            $clob = $clob->__toString();
        }
        $this->boundInVars[$paramIndex] = "'" . $this->escape($clob) . "'";
    }
ODBCPreparedStatement::setNull ($ paramIndex)
See also:
PreparedStatement::setNull()
Reimplemented from PreparedStatementCommon.
Definition at line 182 of file ODBCPreparedStatement.php.
Referenced by setBlob(), and setClob().
    {
      $this->sql_cache_valid = false;
        $this->boundInVars[$paramIndex] = null;
    }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCPreparedStatement.php