fareofficelib: PagedQuery Class Reference
PagedQuery Class Reference
Public Member Functions
__construct (Connection $conn, $sql=null, $page=1, $rowsPerPage=25)
Create a new Query.
setPage ($page)
Set the current page number (First page is 1).
getPage ()
Get current page.
setRowsPerPage ($r)
Set the number of rows per page.
getRowsPerPage ()
Get number of rows per page.
getTotalRecordCount ()
Gets the total number (un-LIMITed) of records.
Private Member Functions
calculateStart ()
Calculate startrow / max rows based on current page and rows-per-page.
Private Attributes
$page
Detailed Description
Definition at line 35 of file PagedQuery.php.
Constructor & Destructor Documentation
PagedQuery::__construct (Connection $ conn, $ sql = null, $ page = 1, $ rowsPerPage = 25)
Create a new Query.
Parameters:
Connection $conn
string $sql
Definition at line 45 of file PagedQuery.php.
References $page, Query::$sql, setPage(), and setRowsPerPage().
    {
        parent::__construct($conn, $sql);
        $this->setRowsPerPage($rowsPerPage);
        $this->setPage($page);
    }
Member Function Documentation
PagedQuery::calculateStart () [private]
Calculate startrow / max rows based on current page and rows-per-page.
Returns:
void
Definition at line 97 of file PagedQuery.php.
Referenced by setPage(), and setRowsPerPage().
    {
        $this->start = ( ($this->page - 1) * $this->max );
    }
PagedQuery::getPage ()
Get current page.
Returns:
int
Definition at line 68 of file PagedQuery.php.
    {
        return $this->page;
    }
PagedQuery::getRowsPerPage ()
Get number of rows per page.
Returns:
int
Definition at line 88 of file PagedQuery.php.
    {
        return $this->max;
    }
PagedQuery::getTotalRecordCount ()
Gets the total number (un-LIMITed) of records.
This method will perform a query that executes un-LIMITed query. This method is not performance-conscious, so don't call this repeatedly for the same query.
Returns:
int Total number of records - disregarding page, maxrows, etc.
Exceptions:
SQLException
Definition at line 112 of file PagedQuery.php.
    {
        $rs = $this->conn->createStatement()->executeQuery($this->sql);
        return $rs->getRecordCount();
    }
PagedQuery::setPage ($ page)
Set the current page number (First page is 1).
Parameters:
int $page
Returns:
void
Definition at line 57 of file PagedQuery.php.
References $page, and calculateStart().
Referenced by __construct().
    {
        $this->page = $page;
        // (re-)calculate start rec
        $this->calculateStart();
    }
PagedQuery::setRowsPerPage ($ r)
Set the number of rows per page.
Parameters:
int $r
Definition at line 77 of file PagedQuery.php.
References calculateStart().
Referenced by __construct().
    {
        $this->max = $r;
        // (re-)calculate start rec
        $this->calculateStart();
    }
Member Data Documentation
PagedQuery::$page [private]
Definition at line 38 of file PagedQuery.php.
Referenced by __construct(), and setPage().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/jargon/PagedQuery.php