fareofficelib: Lob Class Reference
Lob Class Reference
Public Member Functions
__construct ($data=null)
Construct a new Lob.
getContents ()
Get the contents of the LOB.
setContents ($data)
Set the contents of this LOB.
dump ()
Dump the contents of the file to stdout.
setInputFile ($filePath)
Specify the file that we want this LOB read from.
getInputFile ()
Get the file that we want this LOB read from.
setOutputFile ($filePath)
Specify the file that we want this LOB saved to.
getOutputFile ()
Get the file that we want this LOB saved to.
isFromFile ()
Returns whether this Lob is loaded from file.
readFromFile ($file=null)
Read LOB data from file (binary safe).
writeToFile ($file=null)
Write LOB data to file (binary safe).
__toString ()
Convenience method to get contents of LOB as string.
setModified ($b)
Set whether LOB contents have been modified after initial setting.
isModified ()
Whether LOB contents have been modified after initial setting.
Protected Attributes
$data
$outFile
$inFile
Private Attributes
$modified = null
Detailed Description
Definition at line 29 of file Lob.php.
Constructor & Destructor Documentation
Lob::__construct ($ data = null)
Construct a new Lob.
Parameters:
sttring $data The data contents of the Lob.
See also:
setContents()
Definition at line 66 of file Lob.php.
References $data, and setContents().
    {
        if ($data !== null) {
            $this->setContents($data);
        }
    }
Member Function Documentation
Lob::__toString ()
Convenience method to get contents of LOB as string.
Returns:
string
Definition at line 219 of file Lob.php.
References getContents().
    {
        return $this->getContents();
    }
Lob::dump () [abstract]
Dump the contents of the file to stdout.
Must be implemented by subclasses so that binary status is handled correctly. (i.e. ignored for Clob, handled for Blob)
Returns:
void
Exceptions:
Exception if no file or contents.
Reimplemented in Blob, and Clob.
Lob::getContents ()
Get the contents of the LOB.
Returns:
string The characters in this LOB.
Exceptions:
Exception
Definition at line 78 of file Lob.php.
References isFromFile(), and readFromFile().
Referenced by __toString().
    {
        if ($this->data === null && $this->isFromFile()) {
            $this->readFromFile();
        }
        return $this->data;
    }
Lob::getInputFile ()
Get the file that we want this LOB read from.
Returns:
string The location of the file.
Definition at line 133 of file Lob.php.
    {
        return $this->inFile;
    }
Lob::getOutputFile ()
Get the file that we want this LOB saved to.
Returns:
string $filePath The location of the file.
Definition at line 152 of file Lob.php.
    {
        return $this->outFile;
    }
Lob::isFromFile ()
Returns whether this Lob is loaded from file.
This is useful for bypassing need to read in the contents of the Lob.
Returns:
boolean Whether this LOB is to be read from a file.
Definition at line 162 of file Lob.php.
Referenced by getContents().
    {
        return ($this->inFile !== null);
    }
Lob::isModified ()
Whether LOB contents have been modified after initial setting.
Returns:
boolean TRUE if the contents have been modified after initial setting. FALSE if contents have not been modified or if no contents have bene set.
Definition at line 238 of file Lob.php.
    {
        // cast it so that NULL will also eval to false
        return (boolean) $this->modified;
    }
Lob::readFromFile ($ file = null)
Read LOB data from file (binary safe).
(Implementation may need to be moved into Clob / Blob subclasses, but since file_get_contents() is binary-safe, it hasn't been necessary so far.)
Parameters:
string $file Filename may also be specified here (if not specified using setInputFile()).
Returns:
void
Exceptions:
Exception - if no file specified or error on read.
See also:
setInputFile()
Reimplemented in Clob.
Definition at line 176 of file Lob.php.
References $data, setContents(), and setInputFile().
Referenced by getContents().
    {
        if ($file !== null) {
            $this->setInputFile($file);
        }
        if (!$this->inFile) {
            throw Exception('No file specified for read.');
        }
        $data = @file_get_contents($this->inFile);
        if ($data === false) {
            throw new Exception('Unable to read from file: '.$this->inFile);
        }
        $this->setContents($data);
    }
Lob::setContents ($ data)
Set the contents of this LOB.
Sets the modified flag to FALSE if this is the first call to setContents() for this object. Sets the bit to TRUE if this any subsequent call to setContents().
Parameters:
string $bytes
Definition at line 93 of file Lob.php.
References $data.
Referenced by __construct(), readFromFile(), and Clob::readFromFile().
    {
        $this->data = $data;
        if ($this->modified === null) {
             // if modified bit hasn't been set yet,
            // then it should now be set to FALSE, since
            // we just did inital population
            $this->modified = false;
        } elseif ($this->modified === false) {
            // if it was already FALSE, then it should
            // now be set to TRUE, since this is a subsequent
            // modfiication.
            $this->modified = true;
        }
    }
Lob::setInputFile ($ filePath)
Specify the file that we want this LOB read from.
Parameters:
string $filePath The location of the file.
Returns:
void
Definition at line 124 of file Lob.php.
Referenced by readFromFile(), and Clob::readFromFile().
    {
        $this->inFile = $filePath;
    }
Lob::setModified ($ b)
Set whether LOB contents have been modified after initial setting.
Parameters:
boolean $b
Definition at line 228 of file Lob.php.
    {
        $this->modified = $b;
    }
Lob::setOutputFile ($ filePath)
Specify the file that we want this LOB saved to.
Parameters:
string $filePath The location of the file.
Returns:
void
Definition at line 143 of file Lob.php.
Referenced by writeToFile(), and Clob::writeToFile().
    {
        $this->outFile = $filePath;
    }
Lob::writeToFile ($ file = null)
Write LOB data to file (binary safe).
(Impl may need to move into subclasses, but so far not necessary.)
Parameters:
string $file Filename may also be specified here (if not set using setOutputFile()).
Exceptions:
Exception - if no file specified, no contents to write, or error on write.
See also:
setOutputFile()
Reimplemented in Clob.
Definition at line 199 of file Lob.php.
References setOutputFile().
    {
        if ($file !== null) {
            $this->setOutputFile($file);
        }
        if (!$this->outFile) {
            throw new Exception('No file specified for write');
        }
        if ($this->data === null) {
            throw new Exception('No data to write to file');
        }
        if (false === @file_put_contents($this->outFile, $this->data)) {
            throw new Exception('Unable to write to file: '.$this->outFile);
        }
    }
Member Data Documentation
Lob::$data [protected]
Definition at line 37 of file Lob.php.
Referenced by __construct(), readFromFile(), Clob::readFromFile(), and setContents().
Lob::$inFile [protected]
Definition at line 49 of file Lob.php.
Lob::$modified = null [private]
Definition at line 59 of file Lob.php.
Lob::$outFile [protected]
Definition at line 43 of file Lob.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/util/Lob.php