fareofficelib: DebugConnection Class Reference
DebugConnection Class Reference
Public Member Functions
setLogger ($logger)
Sets a Logger class (e.g.
getNumQueriesExecuted ()
Returns the number of queries executed on this connection so far.
getLastExecutedQuery ()
Returns the last query executed on this connection.
connect ($dsninfo, $flags=0)
connect()
getDatabaseInfo ()
getIdGenerator ()
isConnected ()
prepareStatement ($sql)
createStatement ()
applyLimit (&$sql, $offset, $limit)
close ()
executeQuery ($sql, $fetchmode=null)
executeUpdate ($sql)
getUpdateCount ()
prepareCall ($sql)
getResource ()
getDSN ()
getFlags ()
begin ()
commit ()
rollback ()
setAutoCommit ($bit)
getAutoCommit ()
Private Member Functions
log ($msg)
Private function that logs message using specified logger (if provided).
Private Attributes
$childConnection = null
$numQueriesExecuted = 0
$lastExecutedQuery = ''
$logger
Detailed Description
Definition at line 27 of file DebugConnection.php.
Member Function Documentation
DebugConnection::applyLimit (&$ sql, $ offset, $ limit)
See also:
Connection::applyLimit()
Implements Connection.
Definition at line 135 of file DebugConnection.php.
References log().
  {
    $this->log("applyLimit(): $sql, offset: $offset, limit: $limit");
    return $this->childConnection->applyLimit($sql, $offset, $limit);
  }
DebugConnection::begin ()
See also:
Connection::begin()
Implements Connection.
Definition at line 216 of file DebugConnection.php.
References log().
  {
    $this->log("Beginning transaction.");
    return $this->childConnection->begin();
  }
DebugConnection::close ()
See also:
Connection::close()
Implements Connection.
Definition at line 144 of file DebugConnection.php.
References log().
  {
    $this->log("close(): Closing connection.");
    return $this->childConnection->close();
  }
DebugConnection::commit ()
See also:
Connection::commit()
Implements Connection.
Definition at line 225 of file DebugConnection.php.
References log().
  {
    $this->log("Committing transaction.");
    return $this->childConnection->commit();
  }
DebugConnection::connect ($ dsninfo, $ flags = 0)
connect()
Implements Connection.
Definition at line 76 of file DebugConnection.php.
References Creole::getDriver(), Creole::import(), and log().
  {
    if (!($driver = Creole::getDriver($dsninfo['phptype']))) {
      throw new SQLException("No driver has been registered to handle connection type: $type");
    }
    $connectionClass = Creole::import($driver);
    $this->childConnection = new $connectionClass();
    $this->log("connect(): DSN: ". var_export($dsninfo, true) . ", FLAGS: " . var_export($flags, true));
    return $this->childConnection->connect($dsninfo, $flags);
  }
DebugConnection::createStatement ()
See also:
Connection::createStatement()
Implements Connection.
Definition at line 125 of file DebugConnection.php.
  {
    $obj = $this->childConnection->createStatement();
    $objClass = get_class($obj);
    return new $objClass($this);
  }
DebugConnection::executeQuery ($ sql, $ fetchmode = null)
See also:
Connection::executeQuery()
Implements Connection.
Definition at line 153 of file DebugConnection.php.
References log().
  {
    $this->log("executeQuery(): $sql");
    $this->lastExecutedQuery = $sql;
    $this->numQueriesExecuted++;
    return $this->childConnection->executeQuery($sql, $fetchmode);
  }
DebugConnection::executeUpdate ($ sql)
See also:
Connection::executeUpdate()
Implements Connection.
Definition at line 164 of file DebugConnection.php.
References log().
  {
    $this->log("executeUpdate(): $sql");
    $this->lastExecutedQuery = $sql;
    $this->numQueriesExecuted++;
    return $this->childConnection->executeUpdate($sql);
  }
DebugConnection::getAutoCommit ()
See also:
Connection::getAutoCommit()
Implements Connection.
Definition at line 252 of file DebugConnection.php.
  {
    return $this->childConnection->getAutoCommit();
  }
DebugConnection::getDatabaseInfo ()
See also:
Connection::getDatabaseInfo()
Implements Connection.
Definition at line 90 of file DebugConnection.php.
  {
    return $this->childConnection->getDatabaseInfo();
  }
DebugConnection::getDSN ()
See also:
Connection::connect()
Implements Connection.
Definition at line 200 of file DebugConnection.php.
  {
    return $this->childConnection->getDSN();
  }
DebugConnection::getFlags ()
See also:
Connection::getFlags()
Implements Connection.
Definition at line 208 of file DebugConnection.php.
  {
    return $this->childConnection->getFlags();
  }
DebugConnection::getIdGenerator ()
See also:
Connection::getIdGenerator()
Implements Connection.
Definition at line 98 of file DebugConnection.php.
  {
    return $this->childConnection->getIdGenerator();
  }
DebugConnection::getLastExecutedQuery ()
Returns the last query executed on this connection.
Returns:
string
Definition at line 68 of file DebugConnection.php.
  {
    return $this->lastExecutedQuery;
  }
DebugConnection::getNumQueriesExecuted ()
Returns the number of queries executed on this connection so far.
Returns:
int
Definition at line 58 of file DebugConnection.php.
  {
    return $this->numQueriesExecuted;
  }
DebugConnection::getResource ()
See also:
Connection::getResource()
Implements Connection.
Definition at line 192 of file DebugConnection.php.
  {
    return $this->childConnection->getResource();
  }
DebugConnection::getUpdateCount ()
See also:
Connection::getUpdateCount()
Implements Connection.
Definition at line 175 of file DebugConnection.php.
  {
    return $this->childConnection->getUpdateCount();
  }
DebugConnection::isConnected ()
See also:
Connection::isConnected()
Implements Connection.
Definition at line 106 of file DebugConnection.php.
  {
    return $this->childConnection->isConnected();
  }
DebugConnection::log ($ msg) [private]
Private function that logs message using specified logger (if provided).
Parameters:
string $msg Message to log.
Definition at line 261 of file DebugConnection.php.
Referenced by applyLimit(), begin(), close(), commit(), connect(), executeQuery(), executeUpdate(), prepareCall(), prepareStatement(), rollback(), and setAutoCommit().
  {
    if ($this->logger) {
      $this->logger->log($msg);
    }
  }
DebugConnection::prepareCall ($ sql)
See also:
Connection::prepareCall()
Implements Connection.
Definition at line 183 of file DebugConnection.php.
References log().
  {
    $this->log("prepareCall(): $sql");
    return $this->childConnection->prepareCall($sql);
  }
DebugConnection::prepareStatement ($ sql)
See also:
Connection::prepareStatement()
Implements Connection.
Definition at line 114 of file DebugConnection.php.
References log().
  {
    $this->log("prepareStatement(): $sql");
    $obj = $this->childConnection->prepareStatement($sql);
    $objClass = get_class($obj);
    return new $objClass($this, $sql);
  }
DebugConnection::rollback ()
See also:
Connection::rollback()
Implements Connection.
Definition at line 234 of file DebugConnection.php.
References log().
  {
    $this->log("Rolling back transaction.");
    return $this->childConnection->rollback();
  }
DebugConnection::setAutoCommit ($ bit)
See also:
Connection::setAutoCommit()
Implements Connection.
Definition at line 243 of file DebugConnection.php.
References log().
  {
    $this->log("Setting autocommit to: " . var_export($bit, true));
    return $this->childConnection->setAutoCommit($bit);
  }
DebugConnection::setLogger ($ logger)
Sets a Logger class (e.g.
PEAR Log) to use for logging. The logger class must have a log() method. All messages are logged at default log level.
Parameters:
object $logger
Definition at line 48 of file DebugConnection.php.
References $logger.
  {
    $this->logger = $logger;
  }
Member Data Documentation
DebugConnection::$childConnection = null [private]
Definition at line 30 of file DebugConnection.php.
DebugConnection::$lastExecutedQuery = '' [private]
Definition at line 36 of file DebugConnection.php.
DebugConnection::$logger [private]
Definition at line 41 of file DebugConnection.php.
Referenced by setLogger().
DebugConnection::$numQueriesExecuted = 0 [private]
Definition at line 33 of file DebugConnection.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/contrib/DebugConnection.php