fareofficelib: SQLStatementExtractor Class Reference
SQLStatementExtractor Class Reference
Static Public Member Functions
static extractFile ($filename)
Get SQL statements from file.
static extract ($buffer)
Extract statements from string.
Static Protected Member Functions
static extractStatements ($lines)
Extract SQL statements from array of lines.
static startsWith ($check, $string)
Tests if a string starts with a given string.
static endsWith ($check, $string)
Tests if a string ends with a given string.
static substring ($string, $startpos, $endpos=-1)
a natural way of getting a subtring, php's circular string buffer and strange return values suck if you want to program strict as of C or friends
static getLines ($buffer)
Convert string buffer into array of lines.
Static Protected Attributes
static $delimiter = ';'
Detailed Description
Definition at line 29 of file SQLStatementExtractor.php.
Member Function Documentation
static SQLStatementExtractor::endsWith ($ check, $ string) [static, protected]
Tests if a string ends with a given string.
Parameters:
string $check The substring to check.
string $string The string to check in (haystack).
Returns:
boolean True if $string ends with $check, or they are equal, or $check is empty.
Definition at line 124 of file SQLStatementExtractor.php.
{
        if ($check === "" || $check === $string) {
            return true;
        } else {
            return (strpos(strrev($string), strrev($check)) === 0) ? true : false;
        }
    }
static SQLStatementExtractor::extract ($ buffer) [static]
Extract statements from string.
Parameters:
string $txt
Returns:
array
Definition at line 53 of file SQLStatementExtractor.php.
References extractStatements().
{
        return self::extractStatements(self::getLines($buffer));
    }
static SQLStatementExtractor::extractFile ($ filename) [static]
Get SQL statements from file.
Parameters:
string $filename Path to file to read.
Returns:
array SQL statements
Definition at line 39 of file SQLStatementExtractor.php.
References extractStatements().
{
        $buffer = file_get_contents($filename);
        if ($buffer === false) {
           throw new Exception("Unable to read file: " . $filename);
        }
        return self::extractStatements(self::getLines($buffer));
    }
static SQLStatementExtractor::extractStatements ($ lines) [static, protected]
Extract SQL statements from array of lines.
Parameters:
array $lines Lines of the read-in file.
Returns:
string
Definition at line 63 of file SQLStatementExtractor.php.
References substring().
Referenced by extract(), and extractFile().
{
        $statements = array();
        $sql = "";
        foreach($lines as $line) {
                $line = trim($line);
                if (self::startsWith("//", $line) ||
                    self::startsWith("--", $line) ||
                    self::startsWith("#", $line)) {
                    continue;
                }
                if (strlen($line) > 4 && strtoupper(substr($line,0, 4)) == "REM ") {
                    continue;
                }
                $sql .= " " . $line;
                $sql = trim($sql);
                // SQL defines "--" as a comment to EOL
                // and in Oracle it may contain a hint
                // so we cannot just remove it, instead we must end it
                if (strpos($line, "--") !== false) {
                    $sql .= "\n";
                }
                if (self::endsWith(self::$delimiter, $sql)) {
                    $statements[] = self::substring($sql, 0, strlen($sql)-1 - strlen(self::$delimiter));
                    $sql = "";
                }
            }
        return $statements;
    }
static SQLStatementExtractor::getLines ($ buffer) [static, protected]
Convert string buffer into array of lines.
Parameters:
string $filename
Returns:
array string[] lines of file.
Definition at line 159 of file SQLStatementExtractor.php.
{
       $lines = preg_split("/\r?\n|\r/", $buffer);
       return $lines;
    }
static SQLStatementExtractor::startsWith ($ check, $ string) [static, protected]
Tests if a string starts with a given string.
Parameters:
string $check The substring to check.
string $string The string to check in (haystack).
Returns:
boolean True if $string starts with $check, or they are equal, or $check is empty.
Definition at line 110 of file SQLStatementExtractor.php.
{
        if ($check === "" || $check === $string) {
            return true;
        } else {
            return (strpos($string, $check) === 0) ? true : false;
        }
    }
static SQLStatementExtractor::substring ($ string, $ startpos, $ endpos = -1) [static, protected]
a natural way of getting a subtring, php's circular string buffer and strange return values suck if you want to program strict as of C or friends
Definition at line 136 of file SQLStatementExtractor.php.
Referenced by extractStatements().
{
        $len    = strlen($string);
        $endpos = (int) (($endpos === -1) ? $len-1 : $endpos);
        if ($startpos > $len-1 || $startpos < 0) {
            trigger_error("substring(), Startindex out of bounds must be 0<n<$len", E_USER_ERROR);
        }
        if ($endpos > $len-1 || $endpos < $startpos) {
            trigger_error("substring(), Endindex out of bounds must be $startpos<n<".($len-1), E_USER_ERROR);
        }
        if ($startpos === $endpos) {
            return (string) $string{$startpos};
        } else {
            $len = $endpos-$startpos;
        }
        return substr($string, $startpos, $len+1);
    }
Member Data Documentation
SQLStatementExtractor::$delimiter = ';' [static, protected]
Definition at line 31 of file SQLStatementExtractor.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/util/sql/SQLStatementExtractor.php