fareofficelib: ODBCIdGenerator Class Reference
ODBCIdGenerator Class Reference
Public Member Functions
__construct (Connection $conn)
Creates a new IdGenerator class, saves passed connection for use later by getId() method.
isBeforeInsert ()
isAfterInsert ()
getIdMethod ()
getId ($seqname=null)
create ($seqname)
Creates the sequence emulation table.
drop ($seqname, $ignoreerrs=false)
Drops the sequence emulation table.
Private Attributes
$conn
Connection object that instantiated this class.
Detailed Description
Definition at line 16 of file ODBCIdGenerator.php.
Constructor & Destructor Documentation
ODBCIdGenerator::__construct (Connection $ conn)
Creates a new IdGenerator class, saves passed connection for use later by getId() method.
Parameters:
Connection $conn
Definition at line 26 of file ODBCIdGenerator.php.
    {
        $this->conn = $conn;
    }
Member Function Documentation
ODBCIdGenerator::create ($ seqname)
Creates the sequence emulation table.
Definition at line 100 of file ODBCIdGenerator.php.
Referenced by getId().
    {
        $this->conn->executeUpdate("CREATE TABLE $seqname ( id numeric(19,0) NOT NULL )");
        $this->conn->executeUpdate("INSERT INTO $seqname ( id ) VALUES ( 0 )");
    }
ODBCIdGenerator::drop ($ seqname, $ ignoreerrs = false)
Drops the sequence emulation table.
Definition at line 109 of file ODBCIdGenerator.php.
Referenced by getId().
    {
        try {
            $this->conn->executeUpdate("DROP TABLE $seqname");
        } catch (Exception $e) {
            if (!$ignoreerrs) throw $e;
        }
    }
ODBCIdGenerator::getId ($ seqname = null)
See also:
IdGenerator::getId()
Implements IdGenerator.
Definition at line 58 of file ODBCIdGenerator.php.
References create(), drop(), and ResultSet::FETCHMODE_NUM.
    {
        if ($seqname === null)
            throw new SQLException('You must specify the sequence name when calling getId() method.');
        $triedcreate = false;
        while (1)
        {
            try
            {
                $n = $this->conn->executeUpdate("UPDATE $seqname SET id = id + 1", ResultSet::FETCHMODE_NUM);
                if ($n == 0)
                    throw new SQLException('Failed to update IdGenerator id', $this->conn->nativeError());
                $rs = $this->conn->executeQuery("SELECT id FROM $seqname", ResultSet::FETCHMODE_NUM);
            }
            catch (SQLException $e)
            {
                //$odbcerr = odbc_error($this->conn->getResource());
                if ($triedcreate)// || ($odbcerr != 'S0000' && $odbcerr != 'S0002'))
                    throw $e;
                $this->drop($seqname, true);
                $this->create($seqname);
                $triedcreate = true;
                continue;
            }
            break;
        }
        $rs->first();
        return $rs->getInt(1);
    }
ODBCIdGenerator::getIdMethod ()
See also:
IdGenerator::getIdMethod()
Implements IdGenerator.
Definition at line 50 of file ODBCIdGenerator.php.
    {
        return self::SEQUENCE;
    }
ODBCIdGenerator::isAfterInsert ()
See also:
IdGenerator::isAfterInsert()
Implements IdGenerator.
Definition at line 42 of file ODBCIdGenerator.php.
    {
        return false;
    }
ODBCIdGenerator::isBeforeInsert ()
See also:
IdGenerator::isBeforeInsert()
Implements IdGenerator.
Definition at line 34 of file ODBCIdGenerator.php.
    {
        return true;
    }
Member Data Documentation
ODBCIdGenerator::$conn [private]
Connection object that instantiated this class.
Definition at line 19 of file ODBCIdGenerator.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCIdGenerator.php