fareofficelib: Clob Class Reference
Clob Class Reference
Public Member Functions
readFromFile ($file=null)
Read LOB data from file.
writeToFile ($file=null)
Write LOB data to file.
dump ()
Dump the contents of the file using fpassthru().
Detailed Description
Definition at line 31 of file Clob.php.
Member Function Documentation
Clob::dump ()
Dump the contents of the file using fpassthru().
Returns:
void
Exceptions:
Exception if no file or contents.
Reimplemented from Lob.
Definition at line 88 of file Clob.php.
    {
        if (!$this->data) {
            // is there a file name set?
            if ($this->inFile) {
                $fp = @fopen($this->inFile, "r");
                if (!$fp) {
                    throw new Exception('Unable to open file: '.$this->inFile);
                }
                fpassthru($fp);
                @fclose($fp);
            } else {
                throw new Exception('No data to dump');
            }
        } else {
            echo $this->data;
        }
    }
Clob::readFromFile ($ file = null)
Read LOB data from file.
Parameters:
string $file Filename may also be specified here (if not specified using setInputFile()).
Returns:
void
Exceptions:
Exception - if no file specified or error on read.
See also:
setInputFile()
Reimplemented from Lob.
Definition at line 40 of file Clob.php.
References Lob::$data, Lob::setContents(), and Lob::setInputFile().
    {
        if ($file !== null) {
            $this->setInputFile($file);
        }
        if (!$this->inFile) {
            throw Exception('No file specified for read.');
        }
        $data = null;
        $file = fopen($this->inFile, "rt");
        while (!feof($file)) $data .= fgets($file, 4096);
        fclose($file);
        if ($data === false) {
            throw new Exception('Unable to read from file: '.$this->inFile);
        }
        $this->setContents($data);
    }
Clob::writeToFile ($ file = null)
Write LOB data to file.
Parameters:
string $file Filename may also be specified here (if not set using setOutputFile()).
Exceptions:
Exception - if no file specified, no contents to write, or error on write.
See also:
setOutputFile()
Reimplemented from Lob.
Definition at line 65 of file Clob.php.
References Lob::setOutputFile().
    {
        if ($file !== null) {
            $this->setOutputFile($file);
        }
        if (!$this->outFile) {
            throw new Exception('No file specified for write');
        }
        if ($this->data === null) {
            throw new Exception('No data to write to file');
        }
        $file = fopen($this->inFile, "wt");
        if (fputs($file, $this->data) === false)
            throw new Exception('Unable to write to file: '.$this->outFile);
        fclose($file);
    }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/util/Clob.php