fareofficelib: ResultSetCommon Class Reference
ResultSetCommon Class Reference
Public Member Functions
__construct (Connection $conn, $result, $fetchmode=null)
Constructor.
__destruct ()
Destructor.
getIterator ()
getResource ()
isLowerAssocCase ()
setFetchmode ($mode)
getFetchmode ()
previous ()
relative ($offset)
absolute ($pos)
first ()
last ()
beforeFirst ()
afterLast ()
isAfterLast ()
isBeforeFirst ()
getCursorPos ()
getRow ()
get ($column)
getArray ($column)
getBoolean ($column)
getBlob ($column)
getClob ($column)
getDate ($column, $format= '%x')
getFloat ($column)
getInt ($column)
getString ($column)
getTime ($column, $format= '%X')
getTimestamp ($column, $format= 'Y-m-d H:i:s')
Protected Attributes
$fetchmode
$conn
$result
$cursorPos = 0
$fields
$lowerAssocCase = false
$rtrimString = false
Detailed Description
Definition at line 53 of file ResultSetCommon.php.
Constructor & Destructor Documentation
ResultSetCommon::__construct (Connection $ conn, $ result, $ fetchmode = null)
Constructor.
Reimplemented in ODBCResultSet, and ODBCResultSetCommon.
Definition at line 100 of file ResultSetCommon.php.
References $fetchmode, $result, Creole::COMPAT_ASSOC_LOWER, Creole::COMPAT_RTRIM_STRING, ResultSet::FETCHMODE_ASSOC, and Connection::getFlags().
    {
        $this->conn = $conn;
        $this->result = $result;
        if ($fetchmode !== null) {
            $this->fetchmode = $fetchmode;
        } else {
            $this->fetchmode = ResultSet::FETCHMODE_ASSOC; // default
        }
        $this->lowerAssocCase = (($conn->getFlags() & Creole::COMPAT_ASSOC_LOWER) === Creole::COMPAT_ASSOC_LOWER);
    $this->rtrimString = (($conn->getFlags() & Creole::COMPAT_RTRIM_STRING) === Creole::COMPAT_RTRIM_STRING);
    }
ResultSetCommon::__destruct ()
Destructor.
Free db result resource.
Definition at line 118 of file ResultSetCommon.php.
    {
          $this->close();
    }
Member Function Documentation
ResultSetCommon::absolute ($ pos)
See also:
ResultSet::absolute()
Definition at line 203 of file ResultSetCommon.php.
References afterLast(), and beforeFirst().
    {
        $ok = $this->seek( $pos - 1 ); // compensate for next() factor
        if ($ok === false) {
            if ($pos - 1 < 0) {
                $this->beforeFirst();
            } else {
                $this->afterLast();
            }
        } else {
            $ok = $this->next();
        }
        return $ok;
    }
ResultSetCommon::afterLast ()
See also:
ResultSet::afterLast()
Definition at line 249 of file ResultSetCommon.php.
Referenced by absolute(), SQLiteResultSet::next(), PgSQLResultSet::next(), OCI8ResultSet::next(), MySQLiResultSet::next(), MySQLResultSet::next(), MSSQLResultSet::next(), and relative().
    {
        $this->cursorPos = $this->getRecordCount() + 1;
    }
ResultSetCommon::beforeFirst ()
See also:
ResultSet::beforeFirst()
Definition at line 241 of file ResultSetCommon.php.
Referenced by absolute(), previous(), and relative().
    {
        $this->cursorPos = 0;
    }
ResultSetCommon::first ()
See also:
ResultSet::first()
Definition at line 221 of file ResultSetCommon.php.
    {
        if($this->cursorPos !== 0) { $this->seek(0); }
        return $this->next();
    }
ResultSetCommon::get ($ column)
See also:
ResultSet::get()
Definition at line 289 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        return $this->fields[$idx];
    }
ResultSetCommon::getArray ($ column)
See also:
ResultSet::getArray()
Reimplemented in PgSQLResultSet.
Definition at line 299 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        return (array) unserialize($this->fields[$idx]);
    }
ResultSetCommon::getBlob ($ column)
See also:
ResultSet::getBlob()
Reimplemented in ODBCResultSet, PgSQLResultSet, and SQLiteResultSet.
Definition at line 321 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        require_once 'creole/util/Blob.php';
        $b = new Blob();
        $b->setContents($this->fields[$idx]);
        return $b;
    }
ResultSetCommon::getBoolean ($ column)
See also:
ResultSet::getBoolean()
Reimplemented in PgSQLResultSet.
Definition at line 310 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        return (boolean) $this->fields[$idx];
    }
ResultSetCommon::getClob ($ column)
See also:
ResultSet::getClob()
Reimplemented in ODBCResultSet.
Definition at line 335 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        require_once 'creole/util/Clob.php';
        $c = new Clob();
        $c->setContents($this->fields[$idx]);
        return $c;
    }
ResultSetCommon::getCursorPos ()
See also:
ResultSet::getCursorPos()
Definition at line 273 of file ResultSetCommon.php.
    {
        return $this->cursorPos;
    }
ResultSetCommon::getDate ($ column, $ format = '%x')
See also:
ResultSet::getDate()
Definition at line 349 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        $ts = strtotime($this->fields[$idx]);
        if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
            throw new SQLException("Unable to convert value at column " . $column . " to timestamp: " . $this->fields[$idx]);
        }
        if ($format === null) {
            return $ts;
        }
        if (strpos($format, '%') !== false) {
            return strftime($format, $ts);
        } else {
            return date($format, $ts);
        }
    }
ResultSetCommon::getFetchmode ()
See also:
ResultSet::getFetchmode()
Definition at line 159 of file ResultSetCommon.php.
Referenced by SQLiteResultSetIterator::__construct(), and PgSQLResultSetIterator::__construct().
    {
        return $this->fetchmode;
    }
ResultSetCommon::getFloat ($ column)
See also:
ResultSet::getFloat()
Definition at line 371 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        return (float) $this->fields[$idx];
    }
ResultSetCommon::getInt ($ column)
See also:
ResultSet::getInt()
Definition at line 382 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        return (int) $this->fields[$idx];
    }
ResultSetCommon::getIterator ()
See also:
ResultSet::getIterator()
Reimplemented in SQLiteResultSet.
Definition at line 126 of file ResultSetCommon.php.
    {
        require_once 'creole/ResultSetIterator.php';
        return new ResultSetIterator($this);
    }
ResultSetCommon::getResource ()
See also:
ResultSet::getResource()
Definition at line 135 of file ResultSetCommon.php.
Referenced by SQLiteResultSetIterator::__construct(), and PgSQLResultSetIterator::__construct().
    {
        return $this->result;
    }
ResultSetCommon::getRow ()
See also:
ResultSet::getRow()
Definition at line 281 of file ResultSetCommon.php.
    {
        return $this->fields;
    }
ResultSetCommon::getString ($ column)
See also:
ResultSet::getString()
Reimplemented in MySQLResultSet, and MySQLiResultSet.
Definition at line 393 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
    return ($this->rtrimString ? rtrim($this->fields[$idx]) : (string) $this->fields[$idx]);
    }
ResultSetCommon::getTime ($ column, $ format = '%X')
See also:
ResultSet::getTime()
Definition at line 404 of file ResultSetCommon.php.
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        $ts = strtotime($this->fields[$idx]);
        if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
            throw new SQLException("Unable to convert value at column " . (is_int($column) ? $column + 1 : $column) . " to timestamp: " . $this->fields[$idx]);
        }
        if ($format === null) {
            return $ts;
        }
        if (strpos($format, '%') !== false) {
            return strftime($format, $ts);
        } else {
            return date($format, $ts);
        }
    }
ResultSetCommon::getTimestamp ($ column, $ format = 'Y-m-d H:i:s')
See also:
ResultSet::getTimestamp()
Reimplemented in MySQLResultSet, and MySQLiResultSet.
Definition at line 428 of file ResultSetCommon.php.
                                                            :i:s')
    {
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        if ($this->fields[$idx] === null) { return null; }
        $ts = strtotime($this->fields[$idx]);
        if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
            throw new SQLException("Unable to convert value at column " . $column . " to timestamp: " . $this->fields[$idx]);
        }
        if ($format === null) {
            return $ts;
        }
        if (strpos($format, '%') !== false) {
            return strftime($format, $ts);
        } else {
            return date($format, $ts);
        }
    }
ResultSetCommon::isAfterLast ()
See also:
ResultSet::isAfterLast()
Reimplemented in ODBCCachedResultSet, and ODBCResultSet.
Definition at line 257 of file ResultSetCommon.php.
    {
        return ($this->cursorPos === $this->getRecordCount() + 1);
    }
ResultSetCommon::isBeforeFirst ()
See also:
ResultSet::isBeforeFirst()
Definition at line 265 of file ResultSetCommon.php.
    {
        return ($this->cursorPos === 0);
    }
ResultSetCommon::isLowerAssocCase ()
See also:
ResultSet::isLowereAssocCase()
Definition at line 143 of file ResultSetCommon.php.
    {
        return $this->lowerAssocCase;
    }
ResultSetCommon::last ()
See also:
ResultSet::last()
Definition at line 230 of file ResultSetCommon.php.
    {
        if($this->cursorPos !==  ($last = $this->getRecordCount() - 1)) {
            $this->seek( $last );
        }
        return $this->next();
    }
ResultSetCommon::previous ()
See also:
ResultSet::previous()
Definition at line 167 of file ResultSetCommon.php.
References beforeFirst().
    {
        // Go back 2 spaces so that we can then advance 1 space.
        $ok = $this->seek($this->cursorPos - 2);
        if ($ok === false) {
            $this->beforeFirst();
            return false;
        }
        return $this->next();
    }
ResultSetCommon::relative ($ offset)
See also:
ResultSet::isBeforeFirst()
Definition at line 181 of file ResultSetCommon.php.
References afterLast(), and beforeFirst().
    {
        // which absolute row number are we seeking
        $pos = $this->cursorPos + ($offset - 1);
        $ok = $this->seek($pos);
        if ($ok === false) {
            if ($pos < 0) {
                $this->beforeFirst();
            } else {
                $this->afterLast();
            }
        } else {
            $ok = $this->next();
        }
        return $ok;
    }
ResultSetCommon::setFetchmode ($ mode)
See also:
ResultSet::setFetchmode()
Definition at line 151 of file ResultSetCommon.php.
    {
        $this->fetchmode = $mode;
    }
Member Data Documentation
ResultSetCommon::$conn [protected]
Definition at line 65 of file ResultSetCommon.php.
ResultSetCommon::$cursorPos = 0 [protected]
Definition at line 77 of file ResultSetCommon.php.
ResultSetCommon::$fetchmode [protected]
Definition at line 59 of file ResultSetCommon.php.
Referenced by ODBCResultSetCommon::__construct(), ODBCResultSet::__construct(), ODBCCachedResultSet::__construct(), and __construct().
ResultSetCommon::$fields [protected]
Definition at line 83 of file ResultSetCommon.php.
Referenced by ODBCResultSet::next().
ResultSetCommon::$lowerAssocCase = false [protected]
Definition at line 89 of file ResultSetCommon.php.
ResultSetCommon::$result [protected]
Definition at line 71 of file ResultSetCommon.php.
Referenced by ODBCResultSetCommon::__construct(), ODBCResultSet::__construct(), ODBCCachedResultSet::__construct(), __construct(), and ODBCCachedResultSet::loadCache().
ResultSetCommon::$rtrimString = false [protected]
Definition at line 95 of file ResultSetCommon.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/common/ResultSetCommon.php