fareofficelib: ODBCCachedResultSet Class Reference
ODBCCachedResultSet Class Reference
Public Member Functions
__construct (Connection $conn, $result, $fetchmode=null, $cacheLobs=false)
close ()
loadCache ($recPos=-1)
Caches specified records up to and including the specified 1-based record position.
seek ($rownum)
next ()
getRecordCount ()
isAfterLast ()
Protected Attributes
$recs = array()
$lastPos = -1
$cacheLobs = false
Detailed Description
Definition at line 51 of file ODBCCachedResultSet.php.
Constructor & Destructor Documentation
ODBCCachedResultSet::__construct (Connection $ conn, $ result, $ fetchmode = null, $ cacheLobs = false)
See also:
ResultSet::__construct()
Definition at line 74 of file ODBCCachedResultSet.php.
References $cacheLobs, ResultSetCommon::$fetchmode, and ResultSetCommon::$result.
    {
        parent::__construct($conn, $result, $fetchmode);
        $this->cacheLobs = $cacheLobs;
    }
Member Function Documentation
ODBCCachedResultSet::close ()
See also:
ODBCResultSetCommon::close()
Reimplemented from ODBCResultSetCommon.
Definition at line 84 of file ODBCCachedResultSet.php.
    {
        parent::close();
        $this->recs = null;
        $this->lastPos = -1;
        $this->cacheLobs = false;
    }
ODBCCachedResultSet::getRecordCount ()
See also:
ResultSet::getRecordCount()
Implements ResultSet.
Definition at line 198 of file ODBCCachedResultSet.php.
References loadCache().
    {
        if ($this->lastPos == -1)
            $this->loadCache(-1);
        return $this->lastPos;
    }
ODBCCachedResultSet::isAfterLast ()
See also:
ResultSet::isAfterLast()
Implements ResultSet.
Definition at line 209 of file ODBCCachedResultSet.php.
Referenced by next().
    {
        // All records cached yet?
        if ($this->lastPos == -1)
            return false;
        return ($this->cursorPos > $this->lastPos);
    }
ODBCCachedResultSet::loadCache ($ recPos = -1)
Caches specified records up to and including the specified 1-based record position.
If -1 is specified, all records will be cached.
Parameters:
integer Maximum record position to cache.
Returns:
void
Exceptions:
SQLException
Definition at line 99 of file ODBCCachedResultSet.php.
References ResultSetCommon::$result, CreoleTypes::BLOB, CreoleTypes::CLOB, ODBCTypes::getType(), ODBCTypes::loadTypeMap(), CreoleTypes::LONGVARBINARY, CreoleTypes::LONGVARCHAR, and ODBCResultSetCommon::readLobData().
Referenced by getRecordCount(), next(), and seek().
    {
        $rid = $this->result->getHandle();
        $curRecs = count($this->recs);
        $totRecs = ($curRecs ? $this->offset + $curRecs : 0);
        while (1)
        {
            // Is record already cached?
            if ($this->lastPos != -1 || ($recPos > -1 && $recPos <= $curRecs))
                return;
            // Fetch row (no buffers copied yet).
            $rowNum = ++$totRecs;
            $result = @odbc_fetch_row($rid, $rowNum);
            // All records cached?
            if ($result === false || ($this->limit > 0 && $curRecs+1 > $this->limit))
            {
                $this->lastPos = $curRecs;
                continue;
            }
            // Ignore offset records.
            if ($totRecs <= $this->offset)
                continue;
            // Load row array.
            $row = array();
            for ($i = 0, $n = @odbc_num_fields($rid); $i < $n; $i++)
            {
                $fldNum = $i+1;
                $row[$i] = odbc_result($rid, $fldNum);
                // Cache lobs if necessary
                if ($this->cacheLobs)
                {
                    ODBCTypes::loadTypeMap($this->conn);
                    $nativeType = @odbc_field_type($rid, $fldNum);
                    $creoleType = ODBCTypes::getType($nativeType);
                    $isBlob = ($creoleType == CreoleTypes::BLOB ||
                               $creoleType == CreoleTypes::LONGVARBINARY);
                    $isClob = ($creoleType == CreoleTypes::CLOB ||
                               $creoleType == CreoleTypes::LONGVARCHAR);
                    if (($isBlob || $isClob) && $row[$i] !== null)
                    {
                        $binmode = ($isBlob ? ODBC_BINMODE_RETURN : ODBC_BINMODE_CONVERT);
                        $curdata = $row[$i];
                        $row[$i] = $this->readLobData($fldNum, $binmode, $curdata);
                    }
                }
            }
            // Add record to cache.
            $this->recs[++$curRecs] = $row;
        }
    }
ODBCCachedResultSet::next ()
See also:
ResultSet::next()
Implements ResultSet.
Definition at line 180 of file ODBCCachedResultSet.php.
References ResultSet::afterLast(), ODBCResultSetCommon::checkFetchMode(), isAfterLast(), and loadCache().
    {
        $this->loadCache(++$this->cursorPos);
        if ($this->isAfterLast())
        {
            $this->afterLast();
            return false;
        }
        $this->fields =& $this->checkFetchMode($this->recs[$this->cursorPos]);
        return true;
    }
ODBCCachedResultSet::seek ($ rownum)
See also:
ResultSet::seek()
Implements ResultSet.
Definition at line 165 of file ODBCCachedResultSet.php.
References loadCache().
    {
        $this->loadCache($rownum);
        if ($rownum < 0 || $rownum > count($this->recs)+1)
            return false;
        $this->cursorPos = $rownum;
        return true;
    }
Member Data Documentation
ODBCCachedResultSet::$cacheLobs = false [protected]
Definition at line 69 of file ODBCCachedResultSet.php.
Referenced by __construct().
ODBCCachedResultSet::$lastPos = -1 [protected]
Definition at line 63 of file ODBCCachedResultSet.php.
ODBCCachedResultSet::$recs = array() [protected]
Definition at line 57 of file ODBCCachedResultSet.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCCachedResultSet.php