fareofficelib: ODBCResultSet Class Reference
ODBCResultSet Class Reference
Public Member Functions
__construct (Connection $conn, $result, $fetchmode=null)
close ()
seek ($rownum)
next ()
isAfterLast ()
getRecordCount ()
getBlob ($column)
getClob ($column)
Protected Attributes
$numRows = -1
$hasRowCount = false
Detailed Description
Definition at line 45 of file ODBCResultSet.php.
Constructor & Destructor Documentation
ODBCResultSet::__construct (Connection $ conn, $ result, $ fetchmode = null)
See also:
ResultSet::__construct()
Some ODBC drivers appear not to handle odbc_num_rows() very well when more than one result handle is active at once. For example, the MySQL ODBC driver always returns the number of rows for the last executed result. For this reason, we'll store the row count here.
Note also that many ODBC drivers do not support this method. In this case, getRecordCount() will perform a manual count.
Reimplemented from ODBCResultSetCommon.
Definition at line 64 of file ODBCResultSet.php.
References ResultSetCommon::$fetchmode, and ResultSetCommon::$result.
    {
        parent::__construct($conn, $result, $fetchmode);
        $this->numRows = @odbc_num_rows($result->getHandle());
        $this->hasRowCount = $this->numRows != -1;
    }
Member Function Documentation
ODBCResultSet::close ()
See also:
ODBCResultSetCommon::close()
Reimplemented from ODBCResultSetCommon.
Definition at line 84 of file ODBCResultSet.php.
References $numRows.
    {
        parent::close();
        $numRows = -1;
    }
ODBCResultSet::getBlob ($ column)
See also:
ResultSet::getBlob()
Implements ResultSet.
Definition at line 182 of file ODBCResultSet.php.
References ODBCResultSetCommon::readLobData().
    {
        require_once 'creole/util/Blob.php';
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        $data = $this->readLobData($column, ODBC_BINMODE_RETURN, $this->fields[$idx]);
        if (!$data) { return null; }
        $b = new Blob();
        $b->setContents($data);
        return $b;
    }
ODBCResultSet::getClob ($ column)
See also:
ResultSet::getClob()
Implements ResultSet.
Definition at line 197 of file ODBCResultSet.php.
References ODBCResultSetCommon::readLobData().
    {
        require_once 'creole/util/Clob.php';
        $idx = (is_int($column) ? $column - 1 : $column);
        if (!array_key_exists($idx, $this->fields)) { throw new SQLException("Invalid resultset column: " . $column); }
        $data = $this->readLobData($column, ODBC_BINMODE_CONVERT, $this->fields[$idx]);
        if (!$data) { return null; }
        $c = new Clob();
        $c->setContents($data);
        return $c;
    }
ODBCResultSet::getRecordCount ()
See also:
ResultSet::getRecordCount()
Implements ResultSet.
Definition at line 145 of file ODBCResultSet.php.
References $numRows, ResultSet::beforeFirst(), and next().
Referenced by isAfterLast().
    {
        if ($this->hasRowCount)
        {
            // Use driver row count if provided.
            $numRows = $this->numRows - $this->offset;
            if ($this->limit > 0 && $numRows > $this->limit)
                $numRows = $this->limit;
        }
        else
        {
            // Do manual row count if driver doesn't provide one.
            if ($this->numRows == -1)
            {
                $this->numRows = 0;
                $this->beforeFirst();
                while($this->next())
                    $this->numRows++;
            }
            $numRows = $this->numRows;
        }
        // Cursor pos is -1 when an attempt to fetch past the last row was made
        // (or a fetch error occured).
        if ($this->cursorPos == -1)
            $this->cursorPos = $numRows+1;
        return $numRows;
    }
ODBCResultSet::isAfterLast ()
See also:
ResultSet::isAfterLast()
Implements ResultSet.
Definition at line 133 of file ODBCResultSet.php.
References getRecordCount().
    {
        // Force calculation of last record pos.
        if ($this->cursorPos == -1)
            $this->getRecordCount();
        return parent::isAfterLast();
    }
ODBCResultSet::next ()
See also:
ResultSet::next()
Implements ResultSet.
Definition at line 106 of file ODBCResultSet.php.
References ResultSetCommon::$fields, and ODBCResultSetCommon::checkFetchMode().
Referenced by getRecordCount().
    {
        $this->cursorPos++;
        if ($this->limit > 0 && $this->cursorPos > $this->limit) {
            $this->cursorPos = $this->limit+1;
            return false;
        }
        $rowNum = $this->offset + $this->cursorPos;
        $fields = null;
        $cols = @odbc_fetch_into($this->result->getHandle(), $fields, $rowNum);
        if ($cols === false) {
            $this->cursorPos = -1;
            return false;
        }
        $this->fields =& $this->checkFetchMode($fields);
        return true;
    }
ODBCResultSet::seek ($ rownum)
See also:
ResultSet::seek()
Implements ResultSet.
Definition at line 93 of file ODBCResultSet.php.
    {
        if ($rownum < 0 || $this->limit > 0 && $rownum > $this->limit)
            return false;
        $this->cursorPos = $rownum;
        return true;
    }
Member Data Documentation
ODBCResultSet::$hasRowCount = false [protected]
Definition at line 59 of file ODBCResultSet.php.
ODBCResultSet::$numRows = -1 [protected]
Definition at line 52 of file ODBCResultSet.php.
Referenced by close(), and getRecordCount().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/odbc/ODBCResultSet.php