fareofficelib: UTDate Class Reference
UTDate Class Reference
[Unit Tests - Unit tests for all classes/functions in fareofficelib.]
Unit test for all functions in Date.php.
Public Member Functions
doTest ()
Private Member Functions
_testIsValidDate ()
_testIsValidTime ()
Detailed Description
Unit test for all functions in Date.php.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition at line 8 of file UTDate.class.php.
Member Function Documentation
UTDate::_testIsValidDate () [private]
Definition at line 16 of file UTDate.class.php.
Referenced by doTest().
  {
    $this->setSectionLabel('isValidDate');
    eval($this->needTrue('isValidDate("2006-01-01")'));
    eval($this->needTrue('isValidDate("2006-01-01 21:02:02")'));
    eval($this->needTrue('isValidDate("now")'));
    eval($this->needTrue('isValidDate("12jan2009")'));
    eval($this->needFalse('isValidDate("2009jan12")'));
    eval($this->needFalse('isValidDate("asdfasf")'));
    eval($this->needFalse('isValidDate("")'));
  }
UTDate::_testIsValidTime () [private]
Definition at line 28 of file UTDate.class.php.
Referenced by doTest().
  {
    $this->setSectionLabel('isValidTime');
    eval($this->needTrue('isValidTime("21:02:02")'));
    eval($this->needFalse('isValidTime("21:00")'));
    eval($this->needFalse('isValidTime("25:02:02")'));
    eval($this->needFalse('isValidTime("21:62:02")'));
    eval($this->needFalse('isValidTime("21:02:62")'));
    eval($this->needFalse('isValidTime("2009jan12")'));
    eval($this->needFalse('isValidTime("asdfasf")'));
    eval($this->needFalse('isValidTime("")'));
  }
UTDate::doTest ()
Definition at line 10 of file UTDate.class.php.
References _testIsValidDate(), and _testIsValidTime().
  {
    $this->_testIsValidDate();
    $this->_testIsValidTime();
  }
The documentation for this class was generated from the following file:
Static/UnitTestHtDocs/FareOfficeLib/General/UTDate.class.php