fareofficelib: MSSQLResultSet Class Reference
MSSQLResultSet Class Reference
Public Member Functions
_setOffset ($offset)
This MSSQL-only function exists to set offset after ResultSet is instantiated.
_setLimit ($limit)
This MSSQL-only function exists to set limit after ResultSet is instantiated.
seek ($rownum)
next ()
getRecordCount ()
close ()
Private Attributes
$offset = 0
$limit = 0
Detailed Description
Definition at line 36 of file MSSQLResultSet.php.
Member Function Documentation
MSSQLResultSet::_setLimit ($ limit)
This MSSQL-only function exists to set limit after ResultSet is instantiated.
This function should be "protected" in Java sense: only available to classes in package. THIS METHOD SHOULD NOT BE CALLED BY ANYTHING EXCEPTION DRIVER CLASSES.
Parameters:
int $limit New limit. protected
Definition at line 72 of file MSSQLResultSet.php.
References $limit.
    {
        $this->limit = $limit;
    }
MSSQLResultSet::_setOffset ($ offset)
This MSSQL-only function exists to set offset after ResultSet is instantiated.
This function should be "protected" in Java sense: only available to classes in package. THIS METHOD SHOULD NOT BE CALLED BY ANYTHING EXCEPTION DRIVER CLASSES.
Parameters:
int $offset New offset. If great than 0, then seek(0) will be called to move cursor. protected
Definition at line 57 of file MSSQLResultSet.php.
References $offset, and seek().
    {
        $this->offset = $offset;
        if ($offset > 0) {
            $this->seek(0);  // 0 becomes $offset by seek() method
        }
    }
MSSQLResultSet::close ()
See also:
ResultSet::close()
Implements ResultSet.
Definition at line 150 of file MSSQLResultSet.php.
    {
        $ret = @mssql_free_result($this->result);
        $this->result = false;
        $this->fields = array();
        $this->limit = 0;
        $this->offset = 0;
    }
MSSQLResultSet::getRecordCount ()
See also:
ResultSet::getRecordCount()
Implements ResultSet.
Definition at line 136 of file MSSQLResultSet.php.
    {
        $rows = @mssql_num_rows($this->result);
        if ($rows === null) {
            throw new SQLException('Error getting record count', mssql_get_last_message());
        }
        // adjust count based on emulated LIMIT/OFFSET
        $rows -= $this->offset;
        return ($this->limit > 0 && $rows > $this->limit ? $this->limit : $rows);
    }
MSSQLResultSet::next ()
See also:
ResultSet::next()
Implements ResultSet.
Definition at line 104 of file MSSQLResultSet.php.
References ResultSetCommon::afterLast(), and ResultSet::FETCHMODE_ASSOC.
    {
        // support emulated LIMIT
        if ( $this->limit > 0 && ($this->cursorPos >= $this->limit) ) {
            $this->afterLast();
            return false;
        }
        $this->fields = mssql_fetch_array($this->result, $this->fetchmode);
        if (!$this->fields) {
            if ($errmsg = mssql_get_last_message()) {
                throw new SQLException("Error fetching result", $errmsg);
             } else {
                // We've advanced beyond end of recordset.
                $this->afterLast();
                return false;
             }
        }
        if ($this->fetchmode === ResultSet::FETCHMODE_ASSOC && $this->lowerAssocCase) {
            $this->fields = array_change_key_case($this->fields, CASE_LOWER);
        }
        // Advance cursor position
        $this->cursorPos++;
        return true;
    }
MSSQLResultSet::seek ($ rownum)
See also:
ResultSet::seek()
Implements ResultSet.
Definition at line 80 of file MSSQLResultSet.php.
Referenced by _setOffset().
    {
        // support emulated OFFSET
        $actual = $rownum + $this->offset;
        if (($this->limit > 0 && $rownum >= $this->limit) || $rownum < 0) {
                    // have to check for rownum < 0, because mssql_seek() won't
                    // complain if the $actual is valid.
            return false;
        }
        // MSSQL rows start w/ 0, but this works, because we are
        // looking to move the position _before_ the next desired position
         if (!@mssql_data_seek($this->result, $actual)) {
                return false;
        }
        $this->cursorPos = $rownum;
        return true;
    }
Member Data Documentation
MSSQLResultSet::$limit = 0 [private]
Definition at line 48 of file MSSQLResultSet.php.
Referenced by _setLimit().
MSSQLResultSet::$offset = 0 [private]
Definition at line 42 of file MSSQLResultSet.php.
Referenced by _setOffset().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/mssql/MSSQLResultSet.php