fareofficelib: Creole Class Reference
Creole Class Reference
Static Public Member Functions
static registerDriver ($phptype, $dotpath)
Register your own RDBMS driver class.
static deregisterDriver ($phptype)
Removes the driver for a PHP type.
static getDriver ($phptype)
Returns the class path to the driver registered for specified type.
static getConnection ($dsn, $flags=0)
Create a new DB connection object and connect to the specified database.
static parseDSN ($dsn)
static import ($class)
Include once a file specified in DOT notation.
Public Attributes
const PERSISTENT = 1
Constant that indicates a connection object should be used.
const NO_ASSOC_LOWER = 16
Flag to pass to the connection to indicate that no case conversions should be performed by ResultSet on keys of fetched rows.
const COMPAT_ASSOC_LOWER = 32
Flag to pass to the connection to indicate that a to-lower case conversion should be performed by ResultSet on keys of fetched rows.
const COMPAT_RTRIM_STRING = 64
Flag to pass to the connection to indicate that an rtrim() should be performed on strings (using ResultSet->getString(), etc.
const COMPAT_ALL = 96
Flag to indicate that all compatibility flags should be set.
Static Private Attributes
static $driverMap
static $connectionMap = array()
Detailed Description
Definition at line 46 of file Creole.php.
Member Function Documentation
static Creole::deregisterDriver ($ phptype) [static]
Removes the driver for a PHP type.
Note that this will remove user-registered drivers _and_ the default drivers.
Parameters:
string $phptype The PHP type for driver to de-register.
See also:
registerDriver()
Definition at line 137 of file Creole.php.
    {
        unset(self::$driverMap[$phptype]);
    }
static Creole::getConnection ($ dsn, $ flags = 0) [static]
Create a new DB connection object and connect to the specified database.
Parameters:
mixed $dsn "data source name", see the self::parseDSN method for a description of the dsn format. Can also be specified as an array of the format returned by DB::parseDSN().
int $flags Connection flags (e.g. PERSISTENT).
Returns:
Connection Newly created DB connection object
Exceptions:
SQLException
See also:
self::parseDSN()
Definition at line 171 of file Creole.php.
References COMPAT_ALL, COMPAT_ASSOC_LOWER, COMPAT_RTRIM_STRING, import(), NO_ASSOC_LOWER, parseDSN(), PERSISTENT, and SQLException::setUserInfo().
    {
        if (is_array($dsn)) {
            $dsninfo = $dsn;
        } else {
            $dsninfo = self::parseDSN($dsn);
        }
    // gather any flags from the DSN
    if ( isset ( $dsninfo['persistent'] ) && ! empty ( $dsninfo['persistent'] ) )
      $flags |= Creole::PERSISTENT;
    if ( isset ( $dsninfo['compat_assoc_lower'] ) && ! empty ( $dsninfo['compat_assoc_lower'] ) )
      $flags |= Creole::COMPAT_ASSOC_LOWER;
    if ( isset ( $dsninfo['compat_rtrim_string'] ) && ! empty ( $dsninfo['compat_rtrim_string'] ) )
      $flags |= Creole::COMPAT_RTRIM_STRING;
    if ( isset ( $dsninfo['compat_all'] ) && ! empty ( $dsninfo['compat_all'] ) )
      $flags |= Creole::COMPAT_ALL;
    if ($flags & Creole::NO_ASSOC_LOWER) {
      trigger_error("The Creole::NO_ASSOC_LOWER flag has been deprecated, and is now the default behavior. Use Creole::COMPAT_ASSOC_LOWER to lowercase resulset keys.", E_USER_WARNING);
    }
        // sort $dsninfo by keys so the serialized result is always the same
        // for identical connection parameters, no matter what their order is
        ksort($dsninfo);
        $connectionMapKey = crc32(serialize($dsninfo + array('compat_flags' => ($flags & Creole::COMPAT_ALL))));
        // see if we already have a connection with these parameters cached
        if(isset(self::$connectionMap[$connectionMapKey]))
        {
            // persistent connections will be used if a non-persistent one was requested and is available
            // but a persistent connection will be created if a non-persistent one is present
      // TODO: impliment auto close of non persistent and replacing the
      // non persistent with the persistent object so as we dont have
      // both links open for no reason
            if( isset(self::$connectionMap[$connectionMapKey][1]) ) { // is persistent
                // a persistent connection with these parameters is already there,
                // so we return it, no matter what was specified as persistent flag
                $con = self::$connectionMap[$connectionMapKey][1];
            } else {
                // we don't have a persistent connection, and since the persistent
                // flag wasn't set either, we just return the non-persistent connection
                $con = self::$connectionMap[$connectionMapKey][0];
            }
            // if we're here, a non-persistent connection was already there, but
            // the user wants a persistent one, so it will be created
            if ($con->isConnected())
                return $con;
        }
        // support "catchall" drivers which will themselves handle the details of connecting
        // using the proper RDBMS driver.
        if (isset(self::$driverMap['*'])) {
            $type = '*';
        } else {
            $type = $dsninfo['phptype'];
            if (!isset(self::$driverMap[$type])) {
                throw new SQLException("No driver has been registered to handle connection type: $type");
            }
        }
        // may need to make this more complex if we add support
        // for 'dbsyntax'
        $clazz = self::import(self::$driverMap[$type]);
        $obj = new $clazz();
        if (!($obj instanceof Connection)) {
            throw new SQLException("Class does not implement creole.Connection interface: $clazz");
        }
        try {
            $obj->connect($dsninfo, $flags);
        } catch(SQLException $sqle) {
            $sqle->setUserInfo($dsninfo);
            throw $sqle;
        }
    $persistent = ($flags & Creole::PERSISTENT) === Creole::PERSISTENT;
        return self::$connectionMap[$connectionMapKey][(int)$persistent] = $obj;
    }
static Creole::getDriver ($ phptype) [static]
Returns the class path to the driver registered for specified type.
Parameters:
string $phptype The phptype handled by driver (e.g. 'mysql', 'mssql', '*').
Returns:
string The driver class in dot-path notation (e.g. creole.drivers.mssql.MSSQLConnection) or NULL if no registered driver found.
Definition at line 148 of file Creole.php.
Referenced by DebugConnection::connect().
    {
        if (isset(self::$driverMap[$phptype])) {
            return self::$driverMap[$phptype];
        } else {
            return null;
        }
    }
static Creole::import ($ class) [static]
Include once a file specified in DOT notation.
Package notation is expected to be relative to a location on the PHP include_path.
Parameters:
string $class
Returns:
string unqualified classname
Exceptions:
SQLException - if class does not exist and cannot load file
if after loading file class still does not exist
Definition at line 371 of file Creole.php.
Referenced by ODBCConnection::connect(), DebugConnection::connect(), and getConnection().
{
        if (!class_exists($class, false)) {
            $path = strtr($class, '.', DIRECTORY_SEPARATOR) . '.php';
            $ret = include_once($path);
            if ($ret === false) {
                throw new SQLException("Unable to load driver class: " . $class);
            }
            // get just classname ('path.to.ClassName' -> 'ClassName')
            $pos = strrpos($class, '.');
            if ($pos !== false) {
                $class = substr($class, $pos + 1);
            }
            if (!class_exists($class)) {
                throw new SQLException("Unable to find loaded class: $class (Hint: make sure classname matches filename)");
            }
        }
        return $class;
    }
static Creole::parseDSN ($ dsn) [static]
Definition at line 286 of file Creole.php.
Referenced by getConnection().
    {
        if (is_array($dsn)) {
            return $dsn;
        }
        $parsed = array(
            'phptype'  => null,
            'username' => null,
            'password' => null,
            'protocol' => null,
            'hostspec' => null,
            'port'     => null,
            'socket'   => null,
            'database' => null
        );
    $preg_query = "!^(([a-z0-9]+)(\(([^()]+)\))?)(://((((([^@/:]+)(:([^@/]+))?)@)?((([a-z]+)\((([^?():]+)(:([^()?]+))?)\))|((([^/?:]+)(:([^/?]+))?))))/?)?([^?]+)?(\?(.+))?)?$!i";
    $info = array();
    if (preg_match($preg_query,$dsn,$info)) { // only if it is matching
      $parsed['phptype'] = @$info[2]; // Group 2 should always exist.
      // Don't know what to do with Group 4: phptype(xx) should => check first if available
      if (isset($info[5])) { // There is more than just the phptype
        if (strlen($info[10]) > 0) { // There is a username specified
          $parsed['username'] = @$info[10];
        }
        if (strlen($info[12]) > 0) { // There is a password specified
          $parsed['password'] = @$info[12];
        }
        if (strlen($info[15]) > 0) { // There is a protocol specified: protocol(hostspec)
          $parsed['protocol'] = @$info[15];
          if ($parsed["protocol"] === "unix") {
            $parsed['socket'] = @$info[16];
          } else {
            $parsed["hostspec"] = @$info[17];
            if (strlen($info[19]) > 0) {
              $parsed["port"] = @$info[19];
            }
          }
        } elseif (strlen($info[20]) > 0) {
          $parsed["hostspec"] = @$info[22];
          if ((isset($info[24]) && (strlen($info[24]) > 0))) { // There is a port set (not always available)
            $parsed["port"] = @$info[24];
          }
        }
        if ((isset($info[25])) && (strlen($info[25]) > 0)) { // There is a database
          $parsed["database"] = @$info[25];
        }
        if ((isset($info[27])) && (strlen($info[27]) >0)) { // There is a query
          $opts = explode('&', $info[27]);
          foreach ($opts as $opt) {
            list($key, $value) = explode('=', $opt);
            if (!isset($parsed[$key])) { // don't allow params overwrite
              $parsed[$key] = urldecode($value);
            }
          }
        }
      }
    }
        return $parsed;
    }
static Creole::registerDriver ($ phptype, $ dotpath) [static]
Register your own RDBMS driver class.
You can use this to specify your own class that replaces a default driver or adds support for a new driver. Register your own class by specifying the 'phptype' (e.g. mysql) and a dot-path notation to where your Connection class is relative to any location on the include path. You can also specify '*' as the phptype if you want to register a driver that will handle any native type (e.g. if creating a set of decorator classes that log SQL before calling native driver methods). YOU CAN ONLY REGISTER ONE CATCHALL ('*') DRIVER.
Note: the class you need to register is your Connection class because this is the class that's responsible for instantiating the other classes that are part of your driver. It is possible to mix & match drivers -- i.e. to write a custom driver where the Connection object just instantiates stock classes for ResultSet and PreparedStatement. Note that if you wanted to "override" only the ResultSet class you would also have to override the Connection and PreparedStatement classes so that they would return the correct ResultSet class. In the future we may implement a more "packaged" approach to drivers; for now we want to keep it simple.
Parameters:
string $phptype The phptype (mysql, mssql, etc.). This is first part of DSN URL (e.g. mysql://localhost/...). You may also specify '*' to register a driver that will "wrap" the any native drivers.
string $dotpath A dot-path locating your class. For example 'creole.drivers.mssql.MSSQLConnection' will be included like: include 'creole/drivers/mssql/MSSQLConnection.php' and the classname will be assumed to be 'MSSQLConnection'.
Returns:
void
Definition at line 126 of file Creole.php.
    {
        self::$driverMap[$phptype] = $dotpath;
    }
Member Data Documentation
Creole::$connectionMap = array() [static, private]
Definition at line 97 of file Creole.php.
Creole::$driverMap [static, private]
Initial value:
 array(  'mysql' => 'creole.drivers.mysql.MySQLConnection',
                                        'mysqli' => 'creole.drivers.mysqli.MySQLiConnection',
                                        'pgsql' => 'creole.drivers.pgsql.PgSQLConnection',
                                        'sqlite' => 'creole.drivers.sqlite.SQLiteConnection',
                                        'oracle' => 'creole.drivers.oracle.OCI8Connection',
                                        'mssql' => 'creole.drivers.mssql.MSSQLConnection',
                                        'odbc' => 'creole.drivers.odbc.ODBCConnection'
                                       )
Definition at line 83 of file Creole.php.
const Creole::COMPAT_ALL = 96
Flag to indicate that all compatibility flags should be set.
Definition at line 75 of file Creole.php.
Referenced by getConnection().
const Creole::COMPAT_ASSOC_LOWER = 32
Flag to pass to the connection to indicate that a to-lower case conversion should be performed by ResultSet on keys of fetched rows.
Definition at line 64 of file Creole.php.
Referenced by ResultSetCommon::__construct(), SQLiteConnection::connect(), ODBCConnection::connect(), and getConnection().
const Creole::COMPAT_RTRIM_STRING = 64
Flag to pass to the connection to indicate that an rtrim() should be performed on strings (using ResultSet->getString(), etc.
).
Definition at line 70 of file Creole.php.
Referenced by ResultSetCommon::__construct(), and getConnection().
const Creole::NO_ASSOC_LOWER = 16
Flag to pass to the connection to indicate that no case conversions should be performed by ResultSet on keys of fetched rows.
Deprecated:
use COMPAT_ASSOC_LOWER
Definition at line 58 of file Creole.php.
Referenced by getConnection().
const Creole::PERSISTENT = 1
Constant that indicates a connection object should be used.
Definition at line 51 of file Creole.php.
Referenced by SQLiteConnection::connect(), PgSQLConnection::connect(), OCI8Connection::connect(), ODBCConnection::connect(), MySQLConnection::connect(), MSSQLConnection::connect(), and getConnection().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/Creole.php