fareofficelib: Rmail Class Reference
Rmail Class Reference
o------------------------------------------------------------------------------o | This package is licensed under the Phpguru license.
Public Member Functions
__construct ()
Constructor function.
setCRLF ($crlf="\n")
Accessor to set the CRLF style.
setSMTPParams ($host=null, $port=null, $helo=null, $auth=null, $user=null, $pass=null)
Accessor to set the SMTP parameters.
setSendmailPath ($path)
Sets sendmail path and options (optionally) (when directly piping to sendmail).
setTextEncoding (iEncoding $encoding)
Accessor function to set the text encoding.
setHTMLEncoding (iEncoding $encoding)
Accessor function to set the HTML encoding.
setTextCharset ($charset= 'ISO-8859-1')
Accessor function to set the text charset.
setHTMLCharset ($charset= 'ISO-8859-1')
Accessor function to set the HTML charset.
setHeadCharset ($charset= 'ISO-8859-1')
Accessor function to set the header encoding charset.
setTextWrap ($count=998)
Accessor function to set the text wrap count.
setHeader ($name, $value)
Accessor to set a header.
setReceipt ($email)
Sets the delivery reciept address.
setSubject ($subject)
Accessor to add a Subject: header.
setFrom ($from)
Accessor to add a From: header.
setPriority ($priority= 'normal')
Accessor to set priority.
setReturnPath ($return_path)
Accessor to set the return path.
setCc ($cc)
Accessor to add a Cc: header.
setBcc ($bcc)
Accessor to add a Bcc: header.
setText ($text)
Adds plain text.
setHTML ($html, $images_dir=null)
Adds HTML to the emails, with an associated text part.
addEmbeddedImage ($embeddedImage)
Adds an image to the list of embedded images.
addAttachment ($attachment)
Adds a file to the list of attachments.
send ($recipients, $type= 'mail')
Sends the mail.
getRFC822 ($recipients, $type= 'mail')
Use this method to return the email in message/rfc822 format.
Private Member Functions
findHtmlImages ($images_dir)
Function for extracting images from html source.
addTextPart (&$message)
Adds a text subpart to a mime_part object.
addHtmlPart (&$message)
Adds a html subpart to a mime_part object.
addMixedPart (&$message)
Starts a message with a mixed part.
addAlternativePart (&$message)
Adds an alternative part to a mime_part object.
addRelatedPart (&$message)
Adds a html subpart to a mime_part object.
addHtmlImageParts (&$message)
Adds all html images to a mime_part object.
addAttachmentParts (&$message)
Adds all attachments to a mime_part object.
build ()
Builds the multipart message.
encodeHeader ($input, $charset= 'ISO-8859-1')
Function to encode a header if necessary according to RFC2047.
Private Attributes
$html
$text
The text part of the message(only used in TEXT only messages) string.
$output
The main body of the message after building string.
$html_images
An array of embedded images /objects array.
$image_types
An array of recognised image types for the findHtmlImages() method array.
$build_params
Parameters that affect the build process array.
$attachments
Array of attachments array.
$headers
The main message headers array.
$return_path
The return path address.
$smtp_params
Array of information needed for smtp sending array.
$sendmail_path
Sendmail path.
Detailed Description
o------------------------------------------------------------------------------o | This package is licensed under the Phpguru license.
A quick summary is | | that for commercial use, there is a small one-time licensing fee to pay. For | | registered charities and educational institutes there is a reduced license | | fee available. You can read more at: | | | | http://www.phpguru.org/static/license.html | o------------------------------------------------------------------------------o
© Copyright 2008,2009 Richard Heyes
Definition at line 17 of file Rmail.php.
Constructor & Destructor Documentation
Rmail::__construct ()
Constructor function.
Initialise some variables.
If you want the auto load functionality to find other image/file types, add the extension and content type here.
Set these up
Defaults for smtp sending
Make sure the MIME version header is first.
Definition at line 89 of file Rmail.php.
    {
        $this->attachments   = array();
        $this->html_images   = array();
        $this->headers       = array();
        $this->text          = '';
        $this->sendmail_path = '/usr/lib/sendmail -ti';
        $this->image_types = array('gif'  => 'image/gif',
                                   'jpg'  => 'image/jpeg',
                                   'jpeg' => 'image/jpeg',
                                   'jpe'  => 'image/jpeg',
                                   'bmp'  => 'image/bmp',
                                   'png'  => 'image/png',
                                   'tif'  => 'image/tiff',
                                   'tiff' => 'image/tiff',
                                   'swf'  => 'application/x-shockwave-flash');
        $this->build_params['html_encoding'] = new QPrintEncoding();
        $this->build_params['text_encoding'] = new SevenBitEncoding();
        $this->build_params['html_charset']  = 'ISO-8859-1';
        $this->build_params['text_charset']  = 'ISO-8859-1';
        $this->build_params['head_charset']  = 'ISO-8859-1';
        $this->build_params['text_wrap']     = 998;
        if (!empty($_SERVER['HTTP_HOST'])) {
            $helo = $_SERVER['HTTP_HOST'];
        } elseif (!empty($_SERVER['SERVER_NAME'])) {
            $helo = $_SERVER['SERVER_NAME'];
        } else {
            $helo = 'localhost';
        }
        $this->smtp_params['host'] = 'localhost';
        $this->smtp_params['port'] = 25;
        $this->smtp_params['helo'] = $helo;
        $this->smtp_params['auth'] = false;
        $this->smtp_params['user'] = '';
        $this->smtp_params['pass'] = '';
        $this->headers['MIME-Version'] = '1.0';
        $this->headers['X-Mailer'] = 'Rmail <http://www.phpguru.org/>';
    }
Member Function Documentation
Rmail::addAlternativePart (&$ message) [private]
Adds an alternative part to a mime_part object.
Parameters:
object $obj
Returns:
object Mime part object
Definition at line 515 of file Rmail.php.
Referenced by build().
    {
        $params['content_type'] = 'multipart/alternative';
        if (!empty($message)) {
            return $message->addSubpart('', $params);
        } else {
            $message = new Mail_mimePart('', $params);
        }
    }
Rmail::addAttachment ($ attachment)
Adds a file to the list of attachments.
Parameters:
string $attachment Attachment object
Definition at line 454 of file Rmail.php.
References $attachment.
    {
        $this->attachments[] = $attachment;
    }
Rmail::addAttachmentParts (&$ message) [private]
Adds all attachments to a mime_part object.
Parameters:
object $obj Message object
Definition at line 566 of file Rmail.php.
Referenced by build().
    {
        foreach ($this->attachments as $value) {
            $params['content_type'] = $value->contentType;
            $params['encoding']     = $value->encoding->getType();
            $params['disposition']  = 'attachment';
            $params['dfilename']    = $value->name;
            $message->addSubpart($value->data, $params);
        }
    }
Rmail::addEmbeddedImage ($ embeddedImage)
Adds an image to the list of embedded images.
Parameters:
string $object Embedded image object
Definition at line 441 of file Rmail.php.
Referenced by findHtmlImages().
    {
        $embeddedImage->cid = md5(uniqid(time()));
        $this->html_images[] = $embeddedImage;
    }
Rmail::addHtmlImageParts (&$ message) [private]
Adds all html images to a mime_part object.
Parameters:
object $obj Message object
Definition at line 548 of file Rmail.php.
Referenced by build().
    {
        foreach ($this->html_images as $value) {
            $params['content_type'] = $value->contentType;
            $params['encoding']     = $value->encoding->getType();
            $params['disposition']  = 'inline';
            $params['dfilename']    = $value->name;
            $params['cid']          = $value->cid;
            $message->addSubpart($value->data, $params);
        }
    }
Rmail::addHtmlPart (&$ message) [private]
Adds a html subpart to a mime_part object.
Parameters:
object $obj
Returns:
object Mime part object
Definition at line 484 of file Rmail.php.
Referenced by build().
    {
        $params['content_type'] = 'text/html';
        $params['encoding']     = $this->build_params['html_encoding']->getType();
        $params['charset']      = $this->build_params['html_charset'];
        if (!empty($message)) {
            $message->addSubpart($this->html, $params);
        } else {
            $message = new Mail_mimePart($this->html, $params);
        }
    }
Rmail::addMixedPart (&$ message) [private]
Starts a message with a mixed part.
Returns:
object Mime part object
Definition at line 502 of file Rmail.php.
Referenced by build().
    {
        $params['content_type'] = 'multipart/mixed';
        $message = new Mail_mimePart('', $params);
    }
Rmail::addRelatedPart (&$ message) [private]
Adds a html subpart to a mime_part object.
Parameters:
object $obj
Returns:
object Mime part object
Definition at line 532 of file Rmail.php.
Referenced by build().
    {
        $params['content_type'] = 'multipart/related';
        if (!empty($message)) {
            return $message->addSubpart('', $params);
        } else {
            $message = new Mail_mimePart('', $params);
        }
    }
Rmail::addTextPart (&$ message) [private]
Adds a text subpart to a mime_part object.
Parameters:
object $obj
Returns:
object Mime part object
Definition at line 465 of file Rmail.php.
Referenced by build().
    {
        $params['content_type'] = 'text/plain';
        $params['encoding']     = $this->build_params['text_encoding']->getType();
        $params['charset']      = $this->build_params['text_charset'];
        if (!empty($message)) {
            $message->addSubpart($this->text, $params);
        } else {
            $message = new Mail_mimePart($this->text, $params);
        }
    }
Rmail::build () [private]
Builds the multipart message.
Definition at line 581 of file Rmail.php.
References $attachments, $html, $html_images, $output, $text, addAlternativePart(), addAttachmentParts(), addHtmlImageParts(), addHtmlPart(), addMixedPart(), addRelatedPart(), and addTextPart().
Referenced by getRFC822(), and send().
    {
        if (!empty($this->html_images)) {
            foreach ($this->html_images as $value) {
                $quoted = preg_quote($value->name);
                $cid    = preg_quote($value->cid);
                $this->html = preg_replace("#src=\"$quoted\"|src='$quoted'#", "src=\"cid:$cid\"", $this->html);
                $this->html = preg_replace("#background=\"$quoted\"|background='$quoted'#", "background=\"cid:$cid\"", $this->html);
            }
        }
        $message     = null;
        $attachments = !empty($this->attachments);
        $html_images = !empty($this->html_images);
        $html        = !empty($this->html);
        $text        = !$html;
        switch (true) {
            case $text:
                $message = null;
                if ($attachments) {
                    $this->addMixedPart($message);
                }
                $this->addTextPart($message);
                // Attachments
                $this->addAttachmentParts($message);
                break;
            case $html AND !$attachments AND !$html_images:
                $this->addAlternativePart($message);
                $this->addTextPart($message);
                $this->addHtmlPart($message);
                break;
            case $html AND !$attachments AND $html_images:
                $this->addRelatedPart($message);
                $alt = $this->addAlternativePart($message);
                $this->addTextPart($alt);
                $this->addHtmlPart($alt);
                // HTML images
                $this->addHtmlImageParts($message);
                break;
            case $html AND $attachments AND !$html_images:
                $this->addMixedPart($message);
                $alt = $this->addAlternativePart($message);
                $this->addTextPart($alt);
                $this->addHtmlPart($alt);
                // Attachments
                $this->addAttachmentParts($message);
                break;
            case $html AND $attachments AND $html_images:
                $this->addMixedPart($message);
                $rel = $this->addRelatedPart($message);
                $alt = $this->addAlternativePart($rel);
                $this->addTextPart($alt);
                $this->addHtmlPart($alt);
                // HTML images
                $this->addHtmlImageParts($rel);
                // Attachments
                $this->addAttachmentParts($message);
                break;
        }
        if (isset($message)) {
            $output = $message->encode();
            $this->output   = $output['body'];
            $this->headers  = array_merge($this->headers, $output['headers']);
            // Figure out hostname
            if (!empty($_SERVER['HTTP_HOST'])) {
                $hostname = $_SERVER['HTTP_HOST'];
            } else if (!empty($_SERVER['SERVER_NAME'])) {
                $hostname = $_SERVER['SERVER_NAME'];
            } else if (!empty($_ENV['HOSTNAME'])) {
                $hostname = $_ENV['HOSTNAME'];
            } else {
                $hostname = 'localhost';
            }
            $message_id = sprintf('<%s.%s@%s>', base_convert(time(), 10, 36), base_convert(rand(), 10, 36), $hostname);
            $this->headers['Message-ID'] = $message_id;
            return true;
        } else {
            return false;
        }
    }
Rmail::encodeHeader ($ input, $ charset = 'ISO-8859-1') [private]
Function to encode a header if necessary according to RFC2047.
Parameters:
string $input Value to encode
string $charset Character set to use
Returns:
string Encoded value
Definition at line 694 of file Rmail.php.
Referenced by send().
    {
        preg_match_all('/(\w*[\x80-\xFF]+\w*)/', $input, $matches);
        foreach ($matches[1] as $value) {
            $replacement = preg_replace('/([\x80-\xFF])/e', '"=" . strtoupper(dechex(ord("\1")))', $value);
            $input = str_replace($value, '=?' . $charset . '?Q?' . $replacement . '?=', $input);
        }
        return $input;
    }
Rmail::findHtmlImages ($ images_dir) [private]
Function for extracting images from html source.
This function will look through the html code supplied by setHTML() and find any file that ends in one of the extensions defined in $obj->image_types. If the file exists it will read it in and embed it, (not an attachment).
Parameters:
string $images_dir Images directory to look in
Go thru found images
Definition at line 402 of file Rmail.php.
References $html_images, and addEmbeddedImage().
Referenced by setHTML().
    {
        // Build the list of image extensions
        $extensions = array_keys($this->image_types);
        preg_match_all('/(?:"|\')([^"\']+\.('.implode('|', $extensions).'))(?:"|\')/Ui', $this->html, $matches);
        foreach ($matches[1] as $m) {
            if (file_exists($images_dir . $m)) {
                $html_images[] = $m;
                $this->html = str_replace($m, basename($m), $this->html);
            }
        }
        if (!empty($html_images)) {
            // If duplicate images are embedded, they may show up as attachments, so remove them.
            $html_images = array_unique($html_images);
            sort($html_images);
            foreach ($html_images as $img) {
                if ($image = file_get_contents($images_dir . $img)) {
                    $ext          = preg_replace('#^.*\.(\w{3,4})$#e', 'strtolower("$1")', $img);
                    $content_type = $this->image_types[$ext];
                    $this->addEmbeddedImage(new stringEmbeddedImage($image, basename($img), $content_type));
                }
            }
        }
    }
Rmail::getRFC822 ($ recipients, $ type = 'mail')
Use this method to return the email in message/rfc822 format.
Useful for adding an email to another email as an attachment.
Parameters:
array $recipients Array of recipients
string $type Method to be used to send the mail. Used to determine the line ending type.
Definition at line 840 of file Rmail.php.
References $headers, build(), setCRLF(), and setHeader().
    {
        // Make up the date header as according to RFC822
        $this->setHeader('Date', date('D, d M y H:i:s O'));
        if (!defined('CRLF')) {
            $this->setCRLF($type == 'mail' ? "\n" : "\r\n");
        }
        $this->build();
        // Return path ?
        if (isset($this->return_path)) {
            $headers[] = 'Return-Path: ' . $this->return_path;
        }
        // Get flat representation of headers
        foreach ($this->headers as $name => $value) {
            $headers[] = $name . ': ' . $value;
        }
        $headers[] = 'To: ' . implode(', ', $recipients);
        return implode(CRLF, $headers) . CRLF . CRLF . $this->output;
    }
Rmail::send ($ recipients, $ type = 'mail')
Sends the mail.
Parameters:
array $recipients Array of receipients to send the mail to
string $type How to send the mail ('mail' or 'sendmail' or 'smtp')
Returns:
mixed
Definition at line 712 of file Rmail.php.
References $address, $headers, $result, build(), smtp::connect(), encodeHeader(), Mail_RFC822::parseAddressList(), and setCRLF().
    {
        if (!defined('CRLF')) {
            $this->setCRLF( ($type == 'mail' OR $type == 'sendmail') ? "\n" : "\r\n");
        }
        $this->build();
        switch ($type) {
            case 'mail':
                $subject = '';
                if (!empty($this->headers['Subject'])) {
                    $subject = $this->encodeHeader($this->headers['Subject'], $this->build_params['head_charset']);
                    unset($this->headers['Subject']);
                }
                // Get flat representation of headers
                foreach ($this->headers as $name => $value) {
                    $headers[] = $name . ': ' . $this->encodeHeader($value, $this->build_params['head_charset']);
                }
                $to = $this->encodeHeader(implode(', ', $recipients), $this->build_params['head_charset']);
                if (!empty($this->return_path)) {
                    $result = mail($to, $subject, $this->output, implode(CRLF, $headers), '-f' . $this->return_path);
                } else {
                    $result = mail($to, $subject, $this->output, implode(CRLF, $headers));
                }
                // Reset the subject in case mail is resent
                if ($subject !== '') {
                    $this->headers['Subject'] = $subject;
                }
                // Return
                return $result;
                break;
            case 'sendmail':
                // Get flat representation of headers
                foreach ($this->headers as $name => $value) {
                    $headers[] = $name . ': ' . $this->encodeHeader($value, $this->build_params['head_charset']);
                }
                // Encode To:
                $headers[] = 'To: ' . $this->encodeHeader(implode(', ', $recipients), $this->build_params['head_charset']);
                // Get return path arg for sendmail command if necessary
                $returnPath = '';
                if (!empty($this->return_path)) {
                    $returnPath = '-f' . $this->return_path;
                }
                $pipe = popen($this->sendmail_path . " " . $returnPath, 'w');
                    $bytes = fputs($pipe, implode(CRLF, $headers) . CRLF . CRLF . $this->output);
                $r = pclose($pipe);
                return $r;
                break;
            case 'smtp':
                require_once(dirname(__FILE__) . '/smtp.php');
                require_once(dirname(__FILE__) . '/RFC822.php');
                $smtp = &smtp::connect($this->smtp_params);
                // Parse recipients argument for internet addresses
                foreach ($recipients as $recipient) {
                    $addresses = Mail_RFC822::parseAddressList($recipient, $this->smtp_params['helo'], null, false);
                    foreach ($addresses as $address) {
                        $smtp_recipients[] = sprintf('%s@%s', $address->mailbox, $address->host);
                    }
                }
                unset($addresses); // These are reused
                unset($address);   // These are reused
                // Get flat representation of headers, parsing
                // Cc and Bcc as we go
                foreach ($this->headers as $name => $value) {
                    if ($name == 'Cc' OR $name == 'Bcc') {
                        $addresses = Mail_RFC822::parseAddressList($value, $this->smtp_params['helo'], null, false);
                        foreach ($addresses as $address) {
                            $smtp_recipients[] = sprintf('%s@%s', $address->mailbox, $address->host);
                        }
                    }
                    if ($name == 'Bcc') {
                        continue;
                    }
                    $headers[] = $name . ': ' . $this->encodeHeader($value, $this->build_params['head_charset']);
                }
                // Add To header based on $recipients argument
                $headers[] = 'To: ' . $this->encodeHeader(implode(', ', $recipients), $this->build_params['head_charset']);
                // Add headers to send_params
                $send_params['headers']    = $headers;
                $send_params['recipients'] = array_values(array_unique($smtp_recipients));
                $send_params['body']       = $this->output;
                // Setup return path
                if (isset($this->return_path)) {
                    $send_params['from'] = $this->return_path;
                } elseif (!empty($this->headers['From'])) {
                    $from = Mail_RFC822::parseAddressList($this->headers['From']);
                    $send_params['from'] = sprintf('%s@%s', $from[0]->mailbox, $from[0]->host);
                } else {
                    $send_params['from'] = 'postmaster@' . $this->smtp_params['helo'];
                }
                // Send it
                if (!$smtp->send($send_params)) {
                    $this->errors = $smtp->getErrors();
                    return false;
                }
                return true;
                break;
        }
    }
Rmail::setBcc ($ bcc)
Accessor to add a Bcc: header.
Parameters:
string $bcc Blind Carbon Copy address
Definition at line 358 of file Rmail.php.
    {
        $this->headers['Bcc'] = $bcc;
    }
Rmail::setCc ($ cc)
Accessor to add a Cc: header.
Parameters:
string $cc Carbon Copy address
Definition at line 348 of file Rmail.php.
    {
        $this->headers['Cc'] = $cc;
    }
Rmail::setCRLF ($ crlf = "\n")
Accessor to set the CRLF style.
Parameters:
string $crlf CRLF style to use. Use
for SMTP, and
for normal.
Definition at line 159 of file Rmail.php.
Referenced by getRFC822(), and send().
    {
        if (!defined('CRLF')) {
            define('CRLF', $crlf, true);
        }
        if (!defined('MAIL_MIMEPART_CRLF')) {
            define('MAIL_MIMEPART_CRLF', $crlf, true);
        }
    }
Rmail::setFrom ($ from)
Accessor to add a From: header.
Parameters:
string $from From address
Definition at line 298 of file Rmail.php.
    {
        $this->headers['From'] = $from;
    }
Rmail::setHeadCharset ($ charset = 'ISO-8859-1')
Accessor function to set the header encoding charset.
Parameters:
string $charset Character set to use
Definition at line 245 of file Rmail.php.
    {
        $this->build_params['head_charset'] = $charset;
    }
Rmail::setHeader ($ name, $ value)
Accessor to set a header.
Parameters:
string $name Name of header
string $value Value of header
Definition at line 266 of file Rmail.php.
Referenced by getRFC822().
    {
        $this->headers[$name] = $value;
    }
Rmail::setHTML ($ html, $ images_dir = null)
Adds HTML to the emails, with an associated text part.
If third part is given, images in the email will be loaded from this directory.
Parameters:
string $html HTML part of email
string $images_dir Images directory
Definition at line 382 of file Rmail.php.
References $html, and findHtmlImages().
    {
        $this->html = $html;
        if (!empty($images_dir)) {
            $this->findHtmlImages($images_dir);
        }
    }
Rmail::setHTMLCharset ($ charset = 'ISO-8859-1')
Accessor function to set the HTML charset.
Parameters:
string $charset Character set to use
Definition at line 235 of file Rmail.php.
    {
        $this->build_params['html_charset'] = $charset;
    }
Rmail::setHTMLEncoding (iEncoding $ encoding)
Accessor function to set the HTML encoding.
Parameters:
object $encoding HTML encoding to use
Definition at line 215 of file Rmail.php.
    {
        $this->build_params['html_encoding'] = $encoding;
    }
Rmail::setPriority ($ priority = 'normal')
Accessor to set priority.
Priority given should be either high, normal or low. Can also be specified numerically, being 1, 3 or 5 (respectively).
Parameters:
mixed $priority The priority to use.
Definition at line 310 of file Rmail.php.
    {
        switch (strtolower($priority)) {
            case 'high':
            case '1':
                $this->headers['X-Priority'] = '1';
                $this->headers['X-MSMail-Priority'] = 'High';
                break;
            case 'normal':
            case '3':
                $this->headers['X-Priority'] = '3';
                $this->headers['X-MSMail-Priority'] = 'Normal';
                break;
            case 'low':
            case '5':
                $this->headers['X-Priority'] = '5';
                $this->headers['X-MSMail-Priority'] = 'Low';
                break;
        }
    }
Rmail::setReceipt ($ email)
Sets the delivery reciept address.
Parameters:
string $email The address you want the delivery reciept sent to. Note that this is sent at the discretion of the recipient
Definition at line 278 of file Rmail.php.
    {
        $this->headers['Disposition-Notification-To'] = $email;
    }
Rmail::setReturnPath ($ return_path)
Accessor to set the return path.
Parameters:
string $return_path Return path to use
Definition at line 338 of file Rmail.php.
References $return_path.
    {
        $this->return_path = $return_path;
    }
Rmail::setSendmailPath ($ path)
Sets sendmail path and options (optionally) (when directly piping to sendmail).
Parameters:
string $path Path and options for sendmail command
Definition at line 195 of file Rmail.php.
    {
        $this->sendmail_path = $path;
    }
Rmail::setSMTPParams ($ host = null, $ port = null, $ helo = null, $ auth = null, $ user = null, $ pass = null)
Accessor to set the SMTP parameters.
Parameters:
string $host Hostname
string $port Port
string $helo HELO string to use
bool $auth User authentication or not
string $user Username
string $pass Password
Definition at line 180 of file Rmail.php.
    {
        if (!is_null($host)) $this->smtp_params['host'] = $host;
        if (!is_null($port)) $this->smtp_params['port'] = $port;
        if (!is_null($helo)) $this->smtp_params['helo'] = $helo;
        if (!is_null($auth)) $this->smtp_params['auth'] = $auth;
        if (!is_null($user)) $this->smtp_params['user'] = $user;
        if (!is_null($pass)) $this->smtp_params['pass'] = $pass;
    }
Rmail::setSubject ($ subject)
Accessor to add a Subject: header.
Parameters:
string $subject Subject to set
Definition at line 288 of file Rmail.php.
    {
        $this->headers['Subject'] = $subject;
    }
Rmail::setText ($ text)
Adds plain text.
Use this function when NOT sending html email
Parameters:
string $text Plain text of email
Definition at line 369 of file Rmail.php.
References $text.
    {
        $this->text = $text;
    }
Rmail::setTextCharset ($ charset = 'ISO-8859-1')
Accessor function to set the text charset.
Parameters:
string $charset Character set to use
Definition at line 225 of file Rmail.php.
    {
        $this->build_params['text_charset'] = $charset;
    }
Rmail::setTextEncoding (iEncoding $ encoding)
Accessor function to set the text encoding.
Parameters:
object $encoding Text encoding to use
Definition at line 205 of file Rmail.php.
    {
        $this->build_params['text_encoding'] = $encoding;
    }
Rmail::setTextWrap ($ count = 998)
Accessor function to set the text wrap count.
Parameters:
integer $count Point at which to wrap text
Definition at line 255 of file Rmail.php.
    {
        $this->build_params['text_wrap'] = $count;
    }
Member Data Documentation
Rmail::$attachments [private]
Array of attachments array.
Definition at line 59 of file Rmail.php.
Referenced by build().
Rmail::$build_params [private]
Parameters that affect the build process array.
Definition at line 53 of file Rmail.php.
Rmail::$headers [private]
The main message headers array.
Definition at line 65 of file Rmail.php.
Referenced by getRFC822(), and send().
Rmail::$html [private]
Definition at line 23 of file Rmail.php.
Referenced by build(), and setHTML().
Rmail::$html_images [private]
An array of embedded images /objects array.
Definition at line 41 of file Rmail.php.
Referenced by build(), and findHtmlImages().
Rmail::$image_types [private]
An array of recognised image types for the findHtmlImages() method array.
Definition at line 47 of file Rmail.php.
Rmail::$output [private]
The main body of the message after building string.
Definition at line 35 of file Rmail.php.
Referenced by build().
Rmail::$return_path [private]
The return path address.
If not set the From: address is used instead string
Definition at line 72 of file Rmail.php.
Referenced by setReturnPath().
Rmail::$sendmail_path [private]
Sendmail path.
Do not include -f $sendmail_path
Definition at line 84 of file Rmail.php.
Rmail::$smtp_params [private]
Array of information needed for smtp sending array.
Definition at line 78 of file Rmail.php.
Rmail::$text [private]
The text part of the message(only used in TEXT only messages) string.
Definition at line 29 of file Rmail.php.
Referenced by build(), and setText().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/Rmail/Rmail.php