fareofficelib: TableDataSet Class Reference
TableDataSet Class Reference
Public Member Functions
__construct (Connection $conn, $tableName, $p3=null, $p4=null)
Construct new TableDataSet instance.
tableName ()
Gets the tableName defined in the schema.
tableInfo ()
Load the TableInfo (metadata) object for this table.
fetchRecords ($p1=0, $p2=null)
Fetch start to max records.
addRecord ()
Creates a new Record within this DataSet.
save ()
Saves all the records in the DataSet.
removeDeletedRecords ()
Removes any records that are marked as a zombie.
setOptimisticLockingColumn ($olc)
Sets the table column used for optomistic locking.
optimisticLockingCol ()
Gets the table column used for optomistic locking.
where ($where)
Sets the value for the SQL portion of the WHERE statement.
getWhere ()
Gets the value of the SQL portion of WHERE.
order ($order)
Sets the value for the SQL portion of the ORDER statement.
getOrder ()
Gets the value of the SQL portion of ORDER.
other ($other)
Sets the value for the SQL portion of the OTHER statement.
getOther ()
Gets the value of the SQL portion of OTHER.
refresh ()
This method refreshes all of the Records stored in this TableDataSet.
setRefreshOnSave ($v)
Setting this causes each Record to refresh itself when a save() is performed on it.
refreshOnSave ()
Setting this causes each Record to refresh itself when a save() is performed on it.
getSelectSql ()
Builds the select string that was used to populate this TableDataSet.
Private Member Functions
buildSelectString ()
Used by getSelectSql() to build the select string that was used to populate this TableDataSet.
Private Attributes
$tableName
Name of current table.
$tableInfo
TableInfo (metadata) object.
$optimisticLockingCol
the optimistic locking column value
$where
the value for the sql where clause
$order
the value for the sql order by clause
$other
the value for the sql other clause
$refreshOnSave = false
Whether to reload record values when save() is performed.
Detailed Description
Definition at line 39 of file TableDataSet.php.
Constructor & Destructor Documentation
TableDataSet::__construct (Connection $ conn, $ tableName, $ p3 = null, $ p4 = null)
Construct new TableDataSet instance.
Supports a few signatures:
new TableDataSet($conn, "mytable", "col1, col2")
new TableDataSet($conn, "mytable", new KeyDef(...))
new TableDataSet($conn, "mytable", "col1, col2", new KeyDef(...))
Parameters:
Connection $conn
string $tableName
mixed $p3 KeyDef or column list (string)
mixed $p4 KeyDef or column list (string)
Definition at line 75 of file TableDataSet.php.
References $tableName, and tableName().
    {
        $this->conn = $conn;
        $this->columns = "*";
        $this->tableName = $tableName;
        if ($p4 !== null) {
            $this->columns = $p3;
            $this->keyDef = $p4;
        } elseif ($p3 !== null) {
            if ($p3 instanceof KeyDef) {
                $this->keyDef = $p3;
            } else { // it's a string (column list)
                $this->columns = $p3;
            }
        }
    }
Member Function Documentation
TableDataSet::addRecord ()
Creates a new Record within this DataSet.
Returns:
Record The added record
Exceptions:
DataSetException
SQLException
Definition at line 138 of file TableDataSet.php.
    {
        $rec = new Record($this, true);
        $rec->markForInsert();
        $this->records[] = $rec;
        return $rec;
    }
TableDataSet::buildSelectString () [private]
Used by getSelectSql() to build the select string that was used to populate this TableDataSet.
See also:
getSelectSql()
Returns:
void
Exceptions:
DataSetException
Definition at line 324 of file TableDataSet.php.
References order(), other(), tableName(), and where().
Referenced by fetchRecords().
    {
        $this->selectSql = "SELECT ";
        $this->selectSql .= $this->columns;
        $this->selectSql .= " FROM " . $this->tableName;
        if ($this->where !== null && $this->where !== "") {
            $this->selectSql .= " WHERE " . $this->where;
        }
        if ($this->order !== null && $this->order !== "") {
            $this->selectSql .= " ORDER BY " . $this->order;
        }
        if ($this->other !== null && $this->other !== "") {
            $this->selectSql .= $this->other;
        }
    }
TableDataSet::fetchRecords ($ p1 = 0, $ p2 = null)
Fetch start to max records.
start is at Record 0
Parameters:
int $start
int $max
Returns:
TableDataSet This object.
Exceptions:
SQLException
DataSetException
Reimplemented from DataSet.
Definition at line 125 of file TableDataSet.php.
References buildSelectString().
    {
        $this->buildSelectString();
        return parent::fetchRecords($p1, $p2);
    }
TableDataSet::getOrder ()
Gets the value of the SQL portion of ORDER.
Returns:
string
Definition at line 243 of file TableDataSet.php.
References order().
    {
        return $this->order;
    }
TableDataSet::getOther ()
Gets the value of the SQL portion of OTHER.
Returns:
string
Definition at line 267 of file TableDataSet.php.
References other().
    {
        return $this->other;
    }
TableDataSet::getSelectSql ()
Builds the select string that was used to populate this TableDataSet.
Returns:
SQL select string
Reimplemented from DataSet.
Definition at line 312 of file TableDataSet.php.
    {
        return $this->selectSql;
    }
TableDataSet::getWhere ()
Gets the value of the SQL portion of WHERE.
Returns:
string
Definition at line 219 of file TableDataSet.php.
References where().
    {
        return $this->where;
    }
TableDataSet::optimisticLockingCol ()
Gets the table column used for optomistic locking.
Returns:
string
Definition at line 196 of file TableDataSet.php.
Referenced by setOptimisticLockingColumn().
    {
        return $this->optimisticLockingCol;
    }
TableDataSet::order ($ order)
Sets the value for the SQL portion of the ORDER statement.
Returns:
TableDataSet instance of self
Exceptions:
DataSetException
Definition at line 230 of file TableDataSet.php.
References $order.
Referenced by buildSelectString(), and getOrder().
    {
        if ($order === null) {
            throw new DataSetException("null not allowed for order clause");
        }
        $this->order = $order;
        return $this;
    }
TableDataSet::other ($ other)
Sets the value for the SQL portion of the OTHER statement.
Parameters:
string $other
Returns:
TableDataSet instance of self
Exceptions:
DataSetException
Definition at line 254 of file TableDataSet.php.
References $other.
Referenced by buildSelectString(), and getOther().
    {
        if ($other === null) {
            throw new DataSetException("null not allowed for other clause");
        }
        $this->other = $other;
        return $this;
    }
TableDataSet::refresh ()
This method refreshes all of the Records stored in this TableDataSet.
Exceptions:
SQLException,DataSetException
Returns:
void
Definition at line 277 of file TableDataSet.php.
    {
        foreach($this->records as $rec) {
            $rec->refresh($this->conn);
        }
    }
TableDataSet::refreshOnSave ()
Setting this causes each Record to refresh itself when a save() is performed on it.
Default value is false.
Returns:
boolean True if it is on; false otherwise
Definition at line 303 of file TableDataSet.php.
Referenced by setRefreshOnSave().
    {
        return $this->refreshOnSave;
    }
TableDataSet::removeDeletedRecords ()
Removes any records that are marked as a zombie.
Returns:
void
Exceptions:
DataSetException
Definition at line 170 of file TableDataSet.php.
Referenced by save().
    {
        // this algorythm should be a fair bit
        // faster than calling DataSet::removeRecord()
        $new_recs = array();
        foreach($this->records as $rec) {
            if (!$rec->isAZombie()) {
                $new_recs[] = $rec;
            }
        }
        $this->records = $new_recs;
    }
TableDataSet::save ()
Saves all the records in the DataSet.
Returns:
int Total number of records updated/inserted/deleted.
Exceptions:
SQLException,DataSetException
Definition at line 151 of file TableDataSet.php.
References removeDeletedRecords().
    {
        $j = 0;
        foreach($this->records as $rec) {
            $rec->save();
            $j++;
        }
        // now go through and remove any records
        // that were previously marked as a zombie by the
        // delete process
        $this->removeDeletedRecords();
        return $j;
    }
TableDataSet::setOptimisticLockingColumn ($ olc)
Sets the table column used for optomistic locking.
Parameters:
string $olc
Definition at line 187 of file TableDataSet.php.
References optimisticLockingCol().
    {
        $this->optimisticLockingCol = $olc;
    }
TableDataSet::setRefreshOnSave ($ v)
Setting this causes each Record to refresh itself when a save() is performed on it.
Default value is false.
Parameters:
boolean $v
Returns:
true if it is on; false otherwise
Definition at line 291 of file TableDataSet.php.
References refreshOnSave().
    {
        $this->refreshOnSave = $v;
    }
TableDataSet::tableInfo ()
Load the TableInfo (metadata) object for this table.
Returns:
TableInfo
Exceptions:
SQLException if current conn doesn't know about $this->tableName
Definition at line 108 of file TableDataSet.php.
References tableName().
    {
        if ($this->tableInfo === null) {
            $this->tableInfo = $this->conn->getDatabaseInfo()->getTable($this->tableName);
        }
        return $this->tableInfo;
    }
TableDataSet::tableName ()
Gets the tableName defined in the schema.
Returns:
string
Exceptions:
DataSetException
Definition at line 98 of file TableDataSet.php.
Referenced by __construct(), buildSelectString(), and tableInfo().
    {
        return $this->tableName;
    }
TableDataSet::where ($ where)
Sets the value for the SQL portion of the WHERE statement.
Returns:
instance of self
Exceptions:
DataSetException
Definition at line 206 of file TableDataSet.php.
References $where.
Referenced by buildSelectString(), and getWhere().
    {
        if ($where == null) {
            throw new DataSetException("null not allowed for where clause");
        }
        $this->where = $where;
        return $this;
    }
Member Data Documentation
TableDataSet::$optimisticLockingCol [private]
the optimistic locking column value
Definition at line 48 of file TableDataSet.php.
TableDataSet::$order [private]
the value for the sql order by clause
Definition at line 54 of file TableDataSet.php.
Referenced by order().
TableDataSet::$other [private]
the value for the sql other clause
Definition at line 57 of file TableDataSet.php.
Referenced by other().
TableDataSet::$refreshOnSave = false [private]
Whether to reload record values when save() is performed.
Definition at line 60 of file TableDataSet.php.
TableDataSet::$tableInfo [private]
TableInfo (metadata) object.
Definition at line 45 of file TableDataSet.php.
TableDataSet::$tableName [private]
Name of current table.
Definition at line 42 of file TableDataSet.php.
Referenced by __construct().
TableDataSet::$where [private]
the value for the sql where clause
Definition at line 51 of file TableDataSet.php.
Referenced by where().
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/jargon/TableDataSet.php