fareofficelib: OCI8ResultSet Class Reference
OCI8ResultSet Class Reference
Public Member Functions
seek ($rownum)
next ()
getRecordCount ()
close ()
Detailed Description
Definition at line 33 of file OCI8ResultSet.php.
Member Function Documentation
OCI8ResultSet::close ()
See also:
ResultSet::close()
Implements ResultSet.
Definition at line 126 of file OCI8ResultSet.php.
    {
    $this->fields     = array();
        @oci_free_statement( $this->result );
    }
OCI8ResultSet::getRecordCount ()
See also:
ResultSet::getRecordCount()
Implements ResultSet.
Definition at line 109 of file OCI8ResultSet.php.
    {
        $rows         = oci_num_rows( $this->result );
        if ( $rows === false )
    {
            throw new SQLException( 'Error fetching num rows'
        , $this->conn->nativeError( $this->result )
      );
        }
        return ( int ) $rows;
    }
OCI8ResultSet::next ()
See also:
ResultSet::next()
Implements ResultSet.
Definition at line 60 of file OCI8ResultSet.php.
References ResultSetCommon::afterLast(), and ResultSet::FETCHMODE_ASSOC.
Referenced by seek().
    {
    // no specific result position available
    // Returns an array, which corresponds to the next result row or FALSE
    // in case of error or there is no more rows in the result.
        $this->fields     = oci_fetch_array( $this->result
                  , $this->fetchmode
                    + OCI_RETURN_NULLS
                    + OCI_RETURN_LOBS
                );
    if ( ! $this->fields )
    {
      // grab error via array
      $error        = oci_error( $this->result );
      if ( ! $error )
      {
        // end of recordset
        $this->afterLast();
        return false;
      }
      else
      {
        throw new SQLException( 'Error fetching result'
          , $error[ 'code' ] . ': ' . $error[ 'message' ]
        );
      }
    }
    // Oracle returns all field names in uppercase and associative indices
    // in the result array will be uppercased too.
        if ($this->fetchmode === ResultSet::FETCHMODE_ASSOC && $this->lowerAssocCase)
    {
      $this->fields = array_change_key_case($this->fields, CASE_LOWER);
        }
        // Advance cursor position
        $this->cursorPos++;
        return true;
    }
OCI8ResultSet::seek ($ rownum)
See also:
ResultSet::seek()
Implements ResultSet.
Definition at line 38 of file OCI8ResultSet.php.
References next().
    {
        if ( $rownum < $this->cursorPos )
    {
            // this will effectively disable previous(), first() and some calls to relative() or absolute()
            throw new SQLException( 'Oracle ResultSet is FORWARD-ONLY' );
        }
        // Oracle has no seek function imulate it here
        while ( $this->cursorPos < $rownum )
    {
            $this->next();
        }
        $this->cursorPos    = $rownum;
        return true;
    }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/oracle/OCI8ResultSet.php