fareofficelib: TableInfo Class Reference
TableInfo Class Reference
Public Member Functions
__construct (DatabaseInfo $database, $name)
__sleep ()
This "magic" method is invoked upon serialize().
__wakeup ()
This "magic" method is invoked upon unserialize().
getPrimaryKey ()
Get parimary key in this table.
getColumn ($name)
Get the ColumnInfo object for specified column.
hasColumn ($name)
Return whether table contains specified column.
getColumns ()
Get array of columns for this table.
getForeignKey ($name)
Get specified fk for this table.
getForeignKeys ()
Get all foreign keys.
getIndex ($name)
Gets the IndexInfo object for a specified index.
getIndexes ()
Get array of IndexInfo objects for this table.
getIndices ()
Alias for getIndexes() method.
getName ()
Get table name.
toString ()
foreignKeysLoaded ()
Have foreign keys been loaded?
primaryKeyLoaded ()
Has primary key info been loaded?
columnsLoaded ()
Have columns been loaded?
indexesLoaded ()
Has index information been loaded?
getVendorSpecificInfo ()
Get vendor specific optional information for this table.
addColumn (ColumnInfo $column)
Adds a column to this table.
getDatabase ()
Get the parent DatabaseInfo object.
Protected Member Functions
initColumns ()
Loads the columns.
initPrimaryKey ()
Loads the primary key information for this table.
initForeignKeys ()
Loads the foreign keys for this table.
initIndexes ()
Loads the indexes information for this table.
initVendorSpecificInfo ()
Loads the vendor specific information for this table.
Protected Attributes
$name
$columns = array()
$foreignKeys = array()
$indexes = array()
$primaryKey
$pkLoaded = false
$fksLoaded = false
$indexesLoaded = false
$colsLoaded = false
$vendorLoaded = false
$vendorSpecificInfo = array()
$conn
$database
$dblink
Shortcut to db resource link id (needed by drivers for queries).
$dbname
Shortcut to db name (needed by many drivers for queries).
Detailed Description
Definition at line 30 of file TableInfo.php.
Constructor & Destructor Documentation
TableInfo::__construct (DatabaseInfo $ database, $ name)
Parameters:
string $table The table name.
string $database The database name.
resource $dblink The db connection resource.
Definition at line 73 of file TableInfo.php.
References $name, DatabaseInfo::getConnection(), and DatabaseInfo::getName().
{
        $this->database = $database;
        $this->name = $name;
        $this->conn = $database->getConnection(); // shortcut because all drivers need this for the queries
        $this->dblink = $this->conn->getResource();
        $this->dbname = $database->getName();
    }
Member Function Documentation
TableInfo::__sleep ()
This "magic" method is invoked upon serialize().
Because the Info class hierarchy is recursive, we must handle the serialization and unserialization of this object.
Returns:
array The class variables that should be serialized (all must be public!).
Definition at line 87 of file TableInfo.php.
    {
        return array('name', 'columns', 'foreignKeys', 'indexes', 'primaryKey');
    }
TableInfo::__wakeup ()
This "magic" method is invoked upon unserialize().
This method re-hydrates the object and restores the recursive hierarchy.
Definition at line 96 of file TableInfo.php.
    {
        // restore chaining
        foreach($this->columns as $col) {
            $col->table = $this;
        }
    }
TableInfo::addColumn (ColumnInfo $ column)
Adds a column to this table.
Definition at line 295 of file TableInfo.php.
References ColumnInfo::getName().
    {
        $this->columns[$column->getName()] = $column;
    }
TableInfo::columnsLoaded ()
Have columns been loaded?
Definition at line 273 of file TableInfo.php.
    {
        return $this->colsLoaded;
    }
TableInfo::foreignKeysLoaded ()
Have foreign keys been loaded?
Definition at line 261 of file TableInfo.php.
    {
        return $this->fksLoaded;
    }
TableInfo::getColumn ($ name)
Get the ColumnInfo object for specified column.
Parameters:
string $name The column name.
Returns:
ColumnInfo
Exceptions:
SQLException - if column does not exist for this table.
Definition at line 154 of file TableInfo.php.
References $name, and initColumns().
    {
        if(!$this->colsLoaded) $this->initColumns();
        if (!isset($this->columns[$name])) {
            throw new SQLException("Table `".$this->name."` has no column `".$name."`");
        }
        return $this->columns[$name];
    }
TableInfo::getColumns ()
Get array of columns for this table.
Returns:
array ColumnInfo[]
Definition at line 178 of file TableInfo.php.
References initColumns().
    {
        if(!$this->colsLoaded) $this->initColumns();
        return array_values($this->columns); // re-key numerically
    }
TableInfo::getDatabase ()
Get the parent DatabaseInfo object.
Definition at line 301 of file TableInfo.php.
    {
        return $this->database;
    }
TableInfo::getForeignKey ($ name)
Get specified fk for this table.
Parameters:
string $name The foreign key name to retrieve.
Returns:
ForeignKeyInfo
Exceptions:
SQLException - if fkey does not exist for this table.
Definition at line 190 of file TableInfo.php.
References $name, and initForeignKeys().
    {
        if(!$this->fksLoaded) $this->initForeignKeys();
        if (!isset($this->foreignKeys[$name])) {
            throw new SQLException("Table `".$this->name."` has no foreign key `".$name."`");
        }
        return $this->foreignKeys[$name];
    }
TableInfo::getForeignKeys ()
Get all foreign keys.
Returns:
array ForeignKeyInfo[]
Definition at line 203 of file TableInfo.php.
References initForeignKeys().
    {
        if(!$this->fksLoaded) $this->initForeignKeys();
        return array_values($this->foreignKeys);
    }
TableInfo::getIndex ($ name)
Gets the IndexInfo object for a specified index.
Parameters:
string $name The index name to retrieve.
Returns:
IndexInfo
Exceptions:
SQLException - if index does not exist for this table.
Definition at line 215 of file TableInfo.php.
References $name, indexesLoaded(), and initIndexes().
    {
        if(!$this->indexesLoaded) $this->initIndexes();
        if (!isset($this->indexes[$name])) {
            throw new SQLException("Table `".$this->name."` has no index `".$name."`");
        }
        return $this->indexes[$name];
    }
TableInfo::getIndexes ()
Get array of IndexInfo objects for this table.
Returns:
array IndexInfo[]
Definition at line 228 of file TableInfo.php.
References indexesLoaded(), and initIndexes().
Referenced by getIndices().
    {
        if(!$this->indexesLoaded) $this->initIndexes();
        return array_values($this->indexes);
    }
TableInfo::getIndices ()
Alias for getIndexes() method.
Returns:
array
Definition at line 238 of file TableInfo.php.
References getIndexes().
    {
        return $this->getIndexes();
    }
TableInfo::getName ()
Get table name.
Returns:
string
Definition at line 247 of file TableInfo.php.
Referenced by DatabaseInfo::addTable().
    {
        return $this->name;
    }
TableInfo::getPrimaryKey ()
Get parimary key in this table.
Exceptions:
Exception - if foreign keys are unsupported by DB.
Returns:
array ForeignKeyInfo[]
Definition at line 142 of file TableInfo.php.
References initPrimaryKey().
    {
        if(!$this->pkLoaded) $this->initPrimaryKey();
        return $this->primaryKey;
    }
TableInfo::getVendorSpecificInfo ()
Get vendor specific optional information for this table.
Returns:
array vendorSpecificInfo[]
Definition at line 288 of file TableInfo.php.
References initVendorSpecificInfo().
    {
        if(!$this->vendorLoaded) $this->initVendorSpecificInfo();
        return $this->vendorSpecificInfo;
    }
TableInfo::hasColumn ($ name)
Return whether table contains specified column.
Parameters:
string $name The column name.
Returns:
boolean
Definition at line 168 of file TableInfo.php.
References $name, and initColumns().
    {
        if(!$this->colsLoaded) $this->initColumns();
        return isset($this->columns[$name]);
    }
TableInfo::indexesLoaded ()
Has index information been loaded?
Definition at line 279 of file TableInfo.php.
Referenced by getIndex(), getIndexes(), SQLiteTableInfo::initIndexes(), PgSQLTableInfo::initIndexes(), OCI8TableInfo::initIndexes(), MySQLiTableInfo::initIndexes(), MySQLTableInfo::initIndexes(), and MSSQLTableInfo::initIndexes().
    {
        return $this->indexesLoaded;
    }
TableInfo::initColumns () [abstract, protected]
Loads the columns.
Returns:
void
Reimplemented in MSSQLTableInfo, MySQLTableInfo, MySQLiTableInfo, ODBCTableInfo, OCI8TableInfo, PgSQLTableInfo, and SQLiteTableInfo.
Referenced by getColumn(), getColumns(), and hasColumn().
TableInfo::initForeignKeys () [abstract, protected]
Loads the foreign keys for this table.
Returns:
void
Reimplemented in MSSQLTableInfo, MySQLTableInfo, MySQLiTableInfo, ODBCTableInfo, OCI8TableInfo, PgSQLTableInfo, and SQLiteTableInfo.
Referenced by getForeignKey(), and getForeignKeys().
TableInfo::initIndexes () [abstract, protected]
Loads the indexes information for this table.
Returns:
void
Reimplemented in MSSQLTableInfo, MySQLTableInfo, MySQLiTableInfo, ODBCTableInfo, OCI8TableInfo, PgSQLTableInfo, and SQLiteTableInfo.
Referenced by getIndex(), and getIndexes().
TableInfo::initPrimaryKey () [abstract, protected]
Loads the primary key information for this table.
Returns:
void
Reimplemented in MSSQLTableInfo, MySQLTableInfo, MySQLiTableInfo, ODBCTableInfo, OCI8TableInfo, PgSQLTableInfo, and SQLiteTableInfo.
Referenced by getPrimaryKey().
TableInfo::initVendorSpecificInfo () [protected]
Loads the vendor specific information for this table.
Returns:
void
Reimplemented in MySQLTableInfo.
Definition at line 135 of file TableInfo.php.
Referenced by getVendorSpecificInfo().
{}
TableInfo::primaryKeyLoaded ()
Has primary key info been loaded?
Definition at line 267 of file TableInfo.php.
    {
        return $this->pkLoaded;
    }
TableInfo::toString ()
Returns:
string
Definition at line 255 of file TableInfo.php.
    {
        return $this->name;
    }
Member Data Documentation
TableInfo::$colsLoaded = false [protected]
Definition at line 41 of file TableInfo.php.
TableInfo::$columns = array() [protected]
Definition at line 33 of file TableInfo.php.
TableInfo::$conn [protected]
Definition at line 54 of file TableInfo.php.
TableInfo::$database [protected]
Definition at line 60 of file TableInfo.php.
TableInfo::$dblink [protected]
Shortcut to db resource link id (needed by drivers for queries).
Definition at line 63 of file TableInfo.php.
TableInfo::$dbname [protected]
Shortcut to db name (needed by many drivers for queries).
Definition at line 66 of file TableInfo.php.
TableInfo::$fksLoaded = false [protected]
Definition at line 39 of file TableInfo.php.
TableInfo::$foreignKeys = array() [protected]
Definition at line 34 of file TableInfo.php.
TableInfo::$indexes = array() [protected]
Definition at line 35 of file TableInfo.php.
TableInfo::$indexesLoaded = false [protected]
Definition at line 40 of file TableInfo.php.
TableInfo::$name [protected]
Definition at line 32 of file TableInfo.php.
Referenced by __construct(), PgSQLTableInfo::__construct(), OCI8TableInfo::__construct(), getColumn(), getForeignKey(), getIndex(), hasColumn(), SQLiteTableInfo::initColumns(), PgSQLTableInfo::initColumns(), ODBCTableInfo::initColumns(), MySQLiTableInfo::initColumns(), MySQLTableInfo::initColumns(), MSSQLTableInfo::initColumns(), PgSQLTableInfo::initForeignKeys(), OCI8TableInfo::initForeignKeys(), ODBCTableInfo::initForeignKeys(), MySQLTableInfo::initForeignKeys(), MSSQLTableInfo::initForeignKeys(), SQLiteTableInfo::initIndexes(), PgSQLTableInfo::initIndexes(), OCI8TableInfo::initIndexes(), MySQLiTableInfo::initIndexes(), MySQLTableInfo::initIndexes(), MSSQLTableInfo::initIndexes(), OCI8TableInfo::initPrimaryKey(), ODBCTableInfo::initPrimaryKey(), MySQLiTableInfo::initPrimaryKey(), MySQLTableInfo::initPrimaryKey(), and MSSQLTableInfo::initPrimaryKey().
TableInfo::$pkLoaded = false [protected]
Definition at line 38 of file TableInfo.php.
TableInfo::$primaryKey [protected]
Definition at line 36 of file TableInfo.php.
TableInfo::$vendorLoaded = false [protected]
Definition at line 42 of file TableInfo.php.
TableInfo::$vendorSpecificInfo = array() [protected]
Definition at line 48 of file TableInfo.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/metadata/TableInfo.php