fareofficelib: DataSet Class Reference
DataSet Class Reference
Public Member Functions
getIterator ()
Return iterator (for IteratorAggregate interface).
resultSet ()
Gets the ResultSet for this DataSet.
allRecordsRetrieved ()
Check if all the records have been retrieve.
setAllRecordsRetrieved ($set)
Set all records retrieved.
removeRecord (Record $rec)
Remove a record from the DataSet's internal storage.
clearRecords ()
Remove all records from the DataSet and nulls those records out and close() the DataSet.
releaseRecords ()
Removes the records from the DataSet, but does not null the records out.
close ()
Releases the records, closes the ResultSet and the Statement, and nulls the Schema and Connection references.
reset ()
Essentially the same as releaseRecords, but it won't work on a QueryDataSet that has been created with a ResultSet.
connection ()
Gets the current database connection.
schema ()
Gets the Schema for this DataSet.
getRecord ($pos)
Get Record at 0 based index position.
findRecord ($pos)
Find Record at 0 based index position.
containsRecord ($pos)
Check to see if the DataSet contains a Record at 0 based position.
fetchRecords ($p1=0, $p2=null)
Causes the DataSet to hit the database and fetch max records, starting at start.
lastFetchSize ()
The number of records that were fetched with the last fetchRecords.
keydef ()
gets the KeyDef object for this DataSet
__toString ()
This returns a represention of this DataSet.
getSelectSql ()
Classes extending this class must implement this method.
getColumns ()
Returns the columns attribute for the DataSet.
size ()
Gets the number of Records in this DataSet.
Public Attributes
const ALL_RECORDS = 0
indicates that all records should be retrieved during a fetch
Protected Attributes
$records
this DataSet's collection of Record objects
$conn
this DataSet's connection object
$allRecordsRetrieved = false
have all records been retrieved with the fetchRecords?
$recordRetrievedCount = 0
number of records retrieved
$lastFetchSize = 0
number of records that were last fetched
$totalFetchCount = 0
number of records total that have been fetched
$columns
the columns in the SELECT statement for this DataSet
$selectSql
the select string that was used to build this DataSet
$keyDef
the KeyDef for this DataSet
$resultSet
the result set for this DataSet
$stmt
the Statement for this DataSet
Detailed Description
Definition at line 50 of file DataSet.php.
Member Function Documentation
DataSet::__toString ()
This returns a represention of this DataSet.
Definition at line 379 of file DataSet.php.
References getRecord(), and size().
    {
        $sb = "";
        for ($i = 0, $size = $this->size(); $i < $size; $i++) {
            $sb .= $this->getRecord($i);
        }
        return $sb;
    }
DataSet::allRecordsRetrieved ()
Check if all the records have been retrieve.
Returns:
boolean True if all records have been retrieved
Definition at line 123 of file DataSet.php.
Referenced by fetchRecords(), and setAllRecordsRetrieved().
    {
        return $this->allRecordsRetrieved;
    }
DataSet::clearRecords ()
Remove all records from the DataSet and nulls those records out and close() the DataSet.
Returns:
an instance of myself
Definition at line 157 of file DataSet.php.
    {
        $this->records = null;
        return $this;
    }
DataSet::close ()
Releases the records, closes the ResultSet and the Statement, and nulls the Schema and Connection references.
Returns:
void
Definition at line 183 of file DataSet.php.
References releaseRecords(), resultSet(), and schema().
    {
        $this->releaseRecords();
        $this->schema = null;
        if ($this->resultSet !== null && !$this instanceof QueryDataSet) {
            $this->resultSet->close();
        }
        $this->resultSet = null;
        if ( $this->stmt !== null ) {
            $this->stmt->close();
        }
        $this->conn = null;
    }
DataSet::connection ()
Gets the current database connection.
Returns:
Connection A database connection.
Definition at line 222 of file DataSet.php.
    {
        return $this->conn;
    }
DataSet::containsRecord ($ pos)
Check to see if the DataSet contains a Record at 0 based position.
Parameters:
pos
Returns:
true if record exists
Definition at line 279 of file DataSet.php.
Referenced by findRecord(), and getRecord().
    {
        return (isset($this->records[$pos]));
    }
DataSet::fetchRecords ($ p1 = 0, $ p2 = null)
Causes the DataSet to hit the database and fetch max records, starting at start.
Record count begins at 0.
This method supports two signatures:
fetchRecords(10); // LIMIT = 10
fetchRecords(5, 10); // OFFSET = 5, LIMIT = 10
Parameters:
int $p1 max - or start if $p2 is set
int $p2 start
Returns:
DataSet This class.
Exceptions:
SQLException
DataSetException
Reimplemented in TableDataSet.
Definition at line 298 of file DataSet.php.
References allRecordsRetrieved(), lastFetchSize(), resultSet(), and setAllRecordsRetrieved().
    {
        if ($p2 !== null) {
            $start = $p1;
            $max = $p2;
        } else {
            $start = 0;
            $max = $p1;
        }
        if ($this->lastFetchSize() > 0 && $this->records !== null) {
            throw new DataSetException("You must call DataSet::clearRecords() before executing DataSet::fetchRecords() again!");
        }
        try {
            if ($this->stmt === null && $this->resultSet === null) {
                $this->stmt = $this->conn->createStatement();
                $this->stmt->setOffset($start);
                $this->stmt->setLimit($max);
                // reset, since native limit applied
                $start = 0;
                $max = 0;
                $this->resultSet = $this->stmt->executeQuery($this->selectSql);
            }
            if ($this->resultSet !== null) {
                $this->records = array();
                $startCounter = 0;
                $fetchCount = 0;
                while (! $this->allRecordsRetrieved() ) {
                    if ($this->resultSet->next()) {
                        if ($startCounter >= $start) {
                            $this->records[] = new Record($this);
                            $fetchCount++;
                            if ($fetchCount === $max) { // check after because we must fetch at least 1
                                break;
                            }
                        } else {
                            $startCounter++;
                        }
                    } else {
                        $this->setAllRecordsRetrieved(true);
                        break;
                    }
                }
                $this->lastFetchSize = $fetchCount;
            }
        } catch (SQLException $e) {
            if ($this->stmt) $this->stmt->close();
            throw $e;
        }
        return $this;
    }
DataSet::findRecord ($ pos)
Find Record at 0 based index position.
This is an internal alternative to getRecord which tries to be smart about the type of record it is.
Parameters:
int $pos
Returns:
Record an instance of the found Record
Exceptions:
DataSetException
Definition at line 265 of file DataSet.php.
References containsRecord().
    {
        if ($this->containsRecord($pos)) {
            return $this->records[$pos];
        }
        throw new DataSetException ("Record not found at index: " . $pos);
    }
DataSet::getColumns ()
Returns the columns attribute for the DataSet.
Returns:
the columns attribute for the DataSet
Definition at line 401 of file DataSet.php.
    {
        return $this->columns;
    }
DataSet::getIterator ()
Return iterator (for IteratorAggregate interface).
This allows this class to be used in a foreach() loop. foreach($dataset as $record) { print "col1 = " . $record->getValue("col1") . "\n"; }
Returns:
DataSetIterator
Definition at line 98 of file DataSet.php.
    {
        $it = new DataSetIterator($this);
        return $it;
    }
DataSet::getRecord ($ pos)
Get Record at 0 based index position.
Parameters:
int $pos
Returns:
Record An instance of the found Record
Exceptions:
DataSetException
Definition at line 244 of file DataSet.php.
References containsRecord().
Referenced by __toString().
    {
        if ($this->containsRecord($pos)) {
            $rec = $this->records[$pos];
            if ($this instanceof TableDataSet) {
                $rec->markForUpdate();
            }
            $this->recordRetrievedCount++;
            return $rec;
        }
        throw new DataSetException ("Record not found at index: " . $pos);
    }
DataSet::getSelectSql () [abstract]
Classes extending this class must implement this method.
Returns:
string The SELECT SQL.
Exceptions:
DataSetException;
Reimplemented in QueryDataSet, and TableDataSet.
DataSet::keydef ()
gets the KeyDef object for this DataSet
Returns:
KeyDef The keydef for this DataSet, this value can be null
Definition at line 371 of file DataSet.php.
    {
        return $this->keyDef;
    }
DataSet::lastFetchSize ()
The number of records that were fetched with the last fetchRecords.
Returns:
int
Definition at line 361 of file DataSet.php.
Referenced by fetchRecords(), and releaseRecords().
    {
        return $this->lastFetchSize;
    }
DataSet::releaseRecords ()
Removes the records from the DataSet, but does not null the records out.
Returns:
an instance of myself
Definition at line 168 of file DataSet.php.
References lastFetchSize(), and setAllRecordsRetrieved().
Referenced by close(), and reset().
    {
        $this->records = null;
        $this->recordRetrievedCount = 0;
        $this->lastFetchSize = 0;
        $this->setAllRecordsRetrieved(false);
        return $this;
    }
DataSet::removeRecord (Record $ rec)
Remove a record from the DataSet's internal storage.
Parameters:
Record $rec
Returns:
Record The record removed
Definition at line 144 of file DataSet.php.
    {
        $loc = array_search($rec, $this->records, true);
        $removeRec = array_splice($this->records, $loc, 1);
        return $removeRec;
    }
DataSet::reset ()
Essentially the same as releaseRecords, but it won't work on a QueryDataSet that has been created with a ResultSet.
Returns:
DataSet This object.
Exceptions:
DataSetException
Definition at line 208 of file DataSet.php.
References releaseRecords(), and resultSet().
    {
        if (! ($this->resultSet !== null && ($this instanceof QueryDataSet))) {
            return $this->releaseRecords();
        } else {
            throw new DataSetException("You cannot call reset() on a QueryDataSet.");
        }
    }
DataSet::resultSet ()
Gets the ResultSet for this DataSet.
Returns:
ResultSet The result set for this DataSet
Exceptions:
DataSetException - if resultset is null
Definition at line 110 of file DataSet.php.
Referenced by QueryDataSet::__construct(), close(), fetchRecords(), and reset().
    {
        if ($this->resultSet === null) {
            throw new DataSetException ("ResultSet is null.");
        }
        return $this->resultSet;
    }
DataSet::schema ()
Gets the Schema for this DataSet.
Returns:
Schema The Schema for this DataSet
Definition at line 232 of file DataSet.php.
Referenced by close().
    {
        return $this->schema;
    }
DataSet::setAllRecordsRetrieved ($ set)
Set all records retrieved.
Parameters:
boolean $set
Returns:
void
Definition at line 133 of file DataSet.php.
References allRecordsRetrieved().
Referenced by fetchRecords(), and releaseRecords().
    {
        $this->allRecordsRetrieved = $set;
    }
DataSet::size ()
Gets the number of Records in this DataSet.
It is 0 based.
Returns:
int Number of Records in this DataSet
Definition at line 411 of file DataSet.php.
Referenced by DataSetIterator::__construct(), and __toString().
    {
        if ( $this->records === null )
            return 0;
        return count($this->records);
    }
Member Data Documentation
DataSet::$allRecordsRetrieved = false [protected]
have all records been retrieved with the fetchRecords?
Definition at line 62 of file DataSet.php.
DataSet::$columns [protected]
the columns in the SELECT statement for this DataSet
Definition at line 74 of file DataSet.php.
DataSet::$conn [protected]
this DataSet's connection object
Definition at line 59 of file DataSet.php.
DataSet::$keyDef [protected]
the KeyDef for this DataSet
Definition at line 80 of file DataSet.php.
DataSet::$lastFetchSize = 0 [protected]
number of records that were last fetched
Definition at line 68 of file DataSet.php.
DataSet::$recordRetrievedCount = 0 [protected]
number of records retrieved
Definition at line 65 of file DataSet.php.
DataSet::$records [protected]
this DataSet's collection of Record objects
Definition at line 56 of file DataSet.php.
DataSet::$resultSet [protected]
the result set for this DataSet
Definition at line 83 of file DataSet.php.
DataSet::$selectSql [protected]
the select string that was used to build this DataSet
Definition at line 77 of file DataSet.php.
Referenced by QueryDataSet::__construct().
DataSet::$stmt [protected]
the Statement for this DataSet
Definition at line 86 of file DataSet.php.
DataSet::$totalFetchCount = 0 [protected]
number of records total that have been fetched
Definition at line 71 of file DataSet.php.
const DataSet::ALL_RECORDS = 0
indicates that all records should be retrieved during a fetch
Definition at line 53 of file DataSet.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/jargon/DataSet.php