fareofficelib: MSSQLCallableStatement Class Reference
MSSQLCallableStatement Class Reference
Public Member Functions
__construct (Connection $conn, $stmt)
Construct new MSSQLCallableStatement.
getResource ()
close ()
executeQuery ($p1=null, $fetchmode=null)
getMoreResults ()
registerOutParameter ($paramIndex, $sqlType, $maxLength=null)
setArray ($paramIndex, $value, $out=false)
setBoolean ($paramIndex, $value, $out=false)
setBlob ($paramIndex, $blob, $out=false)
setClob ($paramIndex, $clob, $out=false)
setDate ($paramIndex, $value, $out=false)
setFloat ($paramIndex, $value, $out=false)
setInt ($paramIndex, $value, $out=false)
setNull ($paramIndex)
setString ($paramIndex, $value, $out=false)
setTime ($paramIndex, $value, $out=false)
setTimestamp ($paramIndex, $value, $out=false)
getArray ($paramIndex)
getBoolean ($paramIndex)
getBlob ($paramIndex)
getClob ($paramIndex)
getDate ($paramIndex, $fmt= '%Y-%m-%d')
getFloat ($paramIndex)
getInt ($paramIndex)
getString ($paramIndex)
getTime ($paramIndex, $format='%X')
getTimestamp ($paramIndex, $format= 'Y-m-d H:i:s')
Private Attributes
$boundOutVars = array()
Output variables.
$stmt
$result
Static Private Attributes
static $typeMap
Detailed Description
Definition at line 42 of file MSSQLCallableStatement.php.
Constructor & Destructor Documentation
MSSQLCallableStatement::__construct (Connection $ conn, $ stmt)
Construct new MSSQLCallableStatement.
Parameters:
Connection $conn
resource $stmt
Reimplemented from PreparedStatementCommon.
Definition at line 89 of file MSSQLCallableStatement.php.
References $stmt.
    {
        print " - > IN CONSTRUCTOR \n";
        $this->conn = $conn;
        $this->stmt = $stmt;
    }
Member Function Documentation
MSSQLCallableStatement::close ()
See also:
CallableStatement::close()
Reimplemented from PreparedStatementCommon.
Definition at line 107 of file MSSQLCallableStatement.php.
    {
        @mssql_free_statement($this->stmt);
        $this->rsFetchCount = 0;
    }
MSSQLCallableStatement::executeQuery ($ p1 = null, $ fetchmode = null)
See also:
CallableStatement::executeQuery()
Reimplemented from MSSQLPreparedStatement.
Definition at line 116 of file MSSQLCallableStatement.php.
    {
        $params = null;
        if ($fetchmode !== null) {
            $params = $p1;
        } elseif ($p1 !== null) {
            if (is_array($p1)) $params = $p1;
            else $fetchmode = $p1;
        }
        if ($params) {
            for($i=0,$cnt=count($params); $i < $cnt; $i++) {
                $this->set($i+1, $params[$i]);
            }
        }
        $this->result = mssql_execute($this->stmt);
        if (!$this->result) {
            throw new SQLException('unable to execute callable statement', mssql_get_last_message());
        }
        return new MSSQLResultSet($this->conn, $this->result, $fetchmode, $this->offset, $this->limit);
    }
MSSQLCallableStatement::getArray ($ paramIndex)
See also:
CallableStatement::getArray()
Implements CallableStatement.
Definition at line 324 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        return (array) unserialize($this->boundOutVars[$paramIndex]);
    }
MSSQLCallableStatement::getBlob ($ paramIndex)
See also:
CallableStatement::getBlob()
Implements CallableStatement.
Definition at line 348 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        require_once 'creole/util/Blob.php';
        $b = new Blob();
        $b->setContents($this->boundOutVars[$paramIndex]);
        return $b;
    }
MSSQLCallableStatement::getBoolean ($ paramIndex)
See also:
CallableStatement::getBoolean()
Implements CallableStatement.
Definition at line 336 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        return (boolean) $this->boundOutVars[$paramIndex];
    }
MSSQLCallableStatement::getClob ($ paramIndex)
See also:
CallableStatement::getClob()
Implements CallableStatement.
Definition at line 363 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        require_once 'creole/util/Clob.php';
        $c = new Clob();
        $c->setContents($this->boundOutVars[$paramIndex]);
        return $c;
    }
MSSQLCallableStatement::getDate ($ paramIndex, $ fmt = '%Y-%m-%d')
See also:
CallableStatement::getDate()
Implements CallableStatement.
Definition at line 378 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        $ts = strtotime($this->boundOutVars[$paramIndex]);
        if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
            throw new SQLException("Unable to convert value at column " . $paramIndex . " to timestamp: " . $this->boundOutVars[$paramIndex]);
        }
        if (strpos($format, '%') !== false) {
            return strftime($format, $ts);
        } else {
            return date($format, $ts);
        }
        return $this->boundOutVars[$paramIndex];
    }
MSSQLCallableStatement::getFloat ($ paramIndex)
Parameters:
mixed $paramIndex Column name (string) or index (int).
Returns:
float
Implements CallableStatement.
Definition at line 402 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        return (float) $this->boundOutVars[$paramIndex];
    }
MSSQLCallableStatement::getInt ($ paramIndex)
See also:
CallableStatement::getInt()
Implements CallableStatement.
Definition at line 414 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        return (int) $this->boundOutVars[$paramIndex];
    }
MSSQLCallableStatement::getMoreResults ()
See also:
CallableStatement::getMoreResults()
Reimplemented from PreparedStatementCommon.
Definition at line 143 of file MSSQLCallableStatement.php.
    {
        $this->rsFetchCount++; // we track this because
        $hasMore = mssql_next_result($this->result);
        if ($this->resultSet) $this->resultSet->close();
        if ($hasMore) {
            $clazz = $this->resultClass;
            $this->resultSet = new $clazz($this, $this->result);
        } else {
            $this->resultSet = null;
        }
        return $hasMore;
    }
MSSQLCallableStatement::getResource ()
See also:
CallableStatement::getResource()
Reimplemented from PreparedStatementCommon.
Definition at line 99 of file MSSQLCallableStatement.php.
    {
        return $this->stmt;
    }
MSSQLCallableStatement::getString ($ paramIndex)
See also:
CallableStatement::getString()
Implements CallableStatement.
Definition at line 426 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        return (string) $this->boundOutVars[$paramIndex];
    }
MSSQLCallableStatement::getTime ($ paramIndex, $ format = '%X')
See also:
CallableStatement::getTime()
Implements CallableStatement.
Definition at line 438 of file MSSQLCallableStatement.php.
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        $ts = strtotime($this->boundOutVars[$paramIndex]);
        if ($ts === -1  || $ts === false) { // in PHP 5.1 return value changes to FALSE
            throw new SQLException("Unable to convert value at column " . $paramIndex . " to timestamp: " . $this->boundOutVars[$paramIndex]);
        }
        if (strpos($format, '%') !== false) {
            return strftime($format, $ts);
        } else {
            return date($format, $ts);
        }
    }
MSSQLCallableStatement::getTimestamp ($ paramIndex, $ format = 'Y-m-d H:i:s')
See also:
CallableStatement::getTimestamp()
Implements CallableStatement.
Definition at line 460 of file MSSQLCallableStatement.php.
                                                         :i:s')
    {
        if (!array_key_exists($paramIndex, $this->boundOutVars)) {
            throw new SQLException('Requesting variable not bound to output var: '.$paramIndex);
        }
        if ($this->boundOutVars[$paramIndex] === null) { return null; }
        $ts = strtotime($this->boundOutVars[$paramIndex]);
        if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
            throw new SQLException("Unable to convert value at column " . $paramIndex . " to timestamp: " . $this->boundOutVars[$paramIndex]);
        }
        if (strpos($format, '%') !== false) {
            return strftime($format, $ts);
        } else {
            return date($format, $ts);
        }
    }
MSSQLCallableStatement::registerOutParameter ($ paramIndex, $ sqlType, $ maxLength = null)
See also:
CallableStatement::registerOutParameter()
Implements CallableStatement.
Definition at line 160 of file MSSQLCallableStatement.php.
    {
        mssql_bind($this->stmt, $paramIndex, $this->boundOutVars[$paramIndex], self::$typeMap[$sqlType], true, false, $maxLength);
    }
MSSQLCallableStatement::setArray ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setArray()
Definition at line 168 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $value = serialize($value);
            mssql_bind($this->stmt, $paramIndex, $value, SQLTEXT, $out);
        }
    }
MSSQLCallableStatement::setBlob ($ paramIndex, $ blob, $ out = false)
See also:
CallableStatement::setBlob()
Definition at line 197 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($blob === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_object($blob)) {
                $blob = $blob->__toString();
            }
            if ($out) $this->boundOutVars[$paramIndex] = &$blob; // reference means that changes to value, will be reflected
            $data = unpack("H*hex", $blob);
            mssql_bind($this->stmt, $paramIndex, $data, SQLTEXT, $out);
        }
    }
MSSQLCallableStatement::setBoolean ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setBoolean()
Definition at line 182 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $value = ($value) ? 1 : 0;
            mssql_bind($this->stmt, $paramIndex, $value, SQLBIT, $out);
        }
    }
MSSQLCallableStatement::setClob ($ paramIndex, $ clob, $ out = false)
See also:
CallableStatement::setClob()
Definition at line 214 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($clob === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_object($clob)) {
                $clob = $clob->__toString();
            }
            if ($out) $this->boundOutVars[$paramIndex] = &$clob; // reference means that changes to value, will be reflected
            mssql_bind($this->stmt, $paramIndex, $clob, SQLTEXT, $out);
        }
    }
MSSQLCallableStatement::setDate ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setDate()
Definition at line 230 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date("Y-m-d", $value);
            mssql_bind($this->stmt, $paramIndex, $value, SQLVARCHAR, $out);
        }
    }
MSSQLCallableStatement::setFloat ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setFloat()
Definition at line 244 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $value = (float) $value;
            mssql_bind($this->stmt, $paramIndex, $value, SQLFLT8, $out);
        }
    }
MSSQLCallableStatement::setInt ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setInt()
Definition at line 258 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $value = (int) $value;
            mssql_bind($this->stmt, $paramIndex, $value, SQLINT4, $out);
        }
    }
MSSQLCallableStatement::setNull ($ paramIndex)
See also:
CallableStatement::setNull()
Reimplemented from PreparedStatementCommon.
Definition at line 272 of file MSSQLCallableStatement.php.
Referenced by setArray(), setBlob(), setBoolean(), setClob(), setDate(), setFloat(), setInt(), setString(), setTime(), and setTimestamp().
    {
        // hopefully type isn't essential here :)
        $value = null; // wants a var to pass by reference
        mssql_bind($this->stmt, $paramIndex, $value, $type=null, $out=false, $is_null=true);
    }
MSSQLCallableStatement::setString ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setString()
Definition at line 282 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $value = (string) $value;
            mssql_bind($this->stmt, $paramIndex, $value, SQLVARCHAR, $out);
        }
    }
MSSQLCallableStatement::setTime ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setTime()
Definition at line 296 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date("H:i:s", $value);
            mssql_bind($this->stmt, $paramIndex, $value, SQLVARCHAR, $out);
        }
    }
MSSQLCallableStatement::setTimestamp ($ paramIndex, $ value, $ out = false)
See also:
CallableStatement::setTimestamp()
Definition at line 310 of file MSSQLCallableStatement.php.
References setNull().
    {
        if ($out) $this->boundOutVars[$paramIndex] = &$value; // reference means that changes to value, will be reflected
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date('Y-m-d H:i:s', $value);
            mssql_bind($this->stmt, $paramIndex, $value, SQLVARCHAR, $out);
        }
    }
Member Data Documentation
MSSQLCallableStatement::$boundOutVars = array() [private]
Output variables.
Definition at line 45 of file MSSQLCallableStatement.php.
MSSQLCallableStatement::$result [private]
Definition at line 81 of file MSSQLCallableStatement.php.
MSSQLCallableStatement::$stmt [private]
Definition at line 74 of file MSSQLCallableStatement.php.
Referenced by __construct().
MSSQLCallableStatement::$typeMap [static, private]
Initial value:
 array(
        CreoleTypes::BOOLEAN => SQLBIT,
        CreoleTypes::BIGINT => SQLINT4,
        CreoleTypes::SMALLINT => SQLINT2,
        CreoleTypes::TINYINT => SQLINT2,
        CreoleTypes::INTEGER => SQLINT4,
        CreoleTypes::CHAR => SQLCHAR,
        CreoleTypes::VARCHAR => SQLVARCHAR,
        CreoleTypes::TEXT => SQLTEXT,
        CreoleTypes::FLOAT => SQLFLT8,
        CreoleTypes::DOUBLE => SQLFLT8,
        CreoleTypes::DATE => SQLVARCHAR,
        CreoleTypes::TIME => SQLVARCHAR,
        CreoleTypes::TIMESTAMP => SQLVARCHAR,
        CreoleTypes::VARBINARY => SQLVARCHAR,
        CreoleTypes::NUMERIC => SQLINT4,
        CreoleTypes::DECIMAL => SQLFLT8
    )
Definition at line 51 of file MSSQLCallableStatement.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/drivers/mssql/MSSQLCallableStatement.php