fareofficelib: ShellCmd Class Reference
ShellCmd Class Reference
[General]
Functions to execute shell commands.
Static Public Member Functions
static exec ($command_, $parameter_=NULL)
Execute any shell command.
static sshExec ($remoteServer_, $command_)
Execute a shell command on a remoteserver, through SSH.
static sshGet ($remoteServer_, $from_, $to_)
Get a file from a remote server through SSH.
static sshPut ($remoteServer_, $from_, $to_)
Put a file on a remote server through SSH.
Detailed Description
Functions to execute shell commands.
Author:
Daniel Lindh <daniel@fareoffice.com>
Todo:
: Use escapeshellarg() or escapeshellcmd() to ensure that users cannot trick the system into executing arbitrary commands.
Definition at line 10 of file ShellCmd.class.php.
Member Function Documentation
static ShellCmd::exec ($ command_, $ parameter_ = NULL) [static]
Execute any shell command.
If any error occurs an exception will be sent.
 try
 {
   ShellCmd::exec('whoami');
   ShellCmd::exec("wc", "I may be synthetic, but I\'m not stupid.\n\n");
 }
 catch (Exception $e)
 {
   return $e->getMessage();
 }
Parameters:
$command_ - string - The command that should be executed.
$parameter_ - string - Any parameter that should be sent to the shell input, after the command has been executed. Ie. A password after a login command has been executed
Returns:
- string - The output generated by the command.
Definition at line 40 of file ShellCmd.class.php.
Referenced by sshExec(), sshGet(), sshPut(), and UTShellCmd::testExec().
  {
    $retval = '';
    $error = '';
    $descriptorspec = array
    (
      0 => array('pipe', 'r'),
      1 => array('pipe', 'w'),
      2 => array('pipe', 'w')
    );
    $pipes = array();
    $resource = proc_open($command_, $descriptorspec, $pipes, null, $_ENV);
    if (is_resource($resource))
    {
      $stdin = $pipes[0];
      $stdout = $pipes[1];
      $stderr = $pipes[2];
      // Write to standard in
      if (!empty($parameter_))
      {
        fwrite($stdin, $parameter_);
      }
      fclose($stdin);
      // Get result from command
      while (!feof($stdout))
      {
        $retval .= fgets($stdout);
      }
      fclose($stdout);
      // Get the errors back, if any
      while (!feof($stderr))
      {
        $error .= fgets($stderr);
      }
      fclose($stderr);
      $exitCode =  proc_close($resource);
      if (0 != $exitCode)
      {
        $error .= ' Exit code: ' . $exitCode;
      }
    }
    if (! empty($error))
    {
      throw new Exception($error);
    }
    else
    {
      return $retval;
    }
  }
static ShellCmd::sshExec ($ remoteServer_, $ command_) [static]
Execute a shell command on a remoteserver, through SSH.
Parameters:
$remoteServer_ - string - Login and servername of remote server Ie. fareoffice@dpwww1.fareoffice.com
$command_ - string - The command that should be executed on the remote server.
Definition at line 108 of file ShellCmd.class.php.
References exec().
Referenced by UTShellCmd::testSshExec().
  {
    return ShellCmd::exec('/usr/bin/ssh ' . $remoteServer_ . ' "' . $command_ . '"');
  }
static ShellCmd::sshGet ($ remoteServer_, $ from_, $ to_) [static]
Get a file from a remote server through SSH.
Parameters:
$remoteServer_ Login and servername of remote server Ie. fareoffice@dpwww1.fareoffice.com
$from_ Directory and file on remote server that should be copied. Ie. /home/fareoffice/file.txt
$to_ Directory and file on local server where the file should be copied to. Ie. /home/fareoffice/LocalFile.txt
Definition at line 129 of file ShellCmd.class.php.
References exec().
  {
    ShellCmd::exec('/usr/bin/scp ' . $remoteServer_ . ':' . $from_ . ' ' . $to_);
  }
static ShellCmd::sshPut ($ remoteServer_, $ from_, $ to_) [static]
Put a file on a remote server through SSH.
Parameters:
$remoteServer_ Login and servername of remote server Ie. fareoffice@dpwww1.fareoffice.com
$from_ Directory and file on local server that should be copied. Ie. /home/fareoffice/LocalFile.txt
$to_ Directory and file on remote server where the file should be placed. Ie. /home/fareoffice/file.txt
Definition at line 150 of file ShellCmd.class.php.
References exec().
  {
    ShellCmd::exec('/usr/bin/scp ' . $from_ . ' ' . $remoteServer_ .':' . $to_);
  }
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/General/ShellCmd.class.php