fareofficelib: PreparedStatementCommon Class Reference
PreparedStatementCommon Class Reference
Public Member Functions
__construct (Connection $conn, $sql)
Create new prepared statement instance.
setLimit ($v)
getLimit ()
setOffset ($v)
getOffset ()
getResultSet ()
getUpdateCount ()
getMoreResults ()
getConnection ()
getResource ()
Statement resources do not exist for emulated prepared statements, so this just returns null.
close ()
Nothing to close for emulated prepared statements.
executeQuery ($p1=null, $fetchmode=null)
Executes the SQL query in this PreparedStatement object and returns the resultset generated by the query.
executeUpdate ($params=null)
Executes the SQL INSERT, UPDATE, or DELETE statement in this PreparedStatement object.
set ($paramIndex, $value)
A generic set method.
setArray ($paramIndex, $value)
Sets an array.
setBoolean ($paramIndex, $value)
Sets a boolean value.
setBlob ($paramIndex, $blob)
setClob ($paramIndex, $clob)
setDate ($paramIndex, $value)
setDecimal ($paramIndex, $value)
setDouble ($paramIndex, $value)
setFloat ($paramIndex, $value)
setInt ($paramIndex, $value)
setInteger ($paramIndex, $value)
Alias for setInt().
setNull ($paramIndex)
setString ($paramIndex, $value)
setTime ($paramIndex, $value)
setTimestamp ($paramIndex, $value)
Protected Member Functions
parseQuery ($sql)
Parse the SQL query for ? positions.
replaceParams ()
Replaces placeholders with the specified parameter values in the SQL.
escape ($str)
Escapes special characters (usu.
Protected Attributes
$conn
$limit = 0
$offset = 0
$sql
$sql_cache
$sql_cache_valid = false
$positions
$positionsCount
$boundInVars = array()
$resultSet
$updateCount
Detailed Description
Definition at line 34 of file PreparedStatementCommon.php.
Constructor & Destructor Documentation
PreparedStatementCommon::__construct (Connection $ conn, $ sql)
Create new prepared statement instance.
Parameters:
object $conn Connection object
string $sql The SQL to work with.
array $positions The positions in SQL of ?'s.
restult $stmt If the driver supports prepared queries, then $stmt will contain the statement to use.
Reimplemented in MSSQLCallableStatement.
Definition at line 115 of file PreparedStatementCommon.php.
References $sql, and parseQuery().
    {
        $this->conn = $conn;
        $this->sql = $sql;
  $this->positions = $this->parseQuery ( $sql );
        // save processing later in cases where we may repeatedly exec statement
  $this->positionsCount = count ( $this->positions );
    }
Member Function Documentation
PreparedStatementCommon::close ()
Nothing to close for emulated prepared statements.
Reimplemented in MSSQLCallableStatement, and OCI8PreparedStatement.
Definition at line 255 of file PreparedStatementCommon.php.
    {
    }
PreparedStatementCommon::escape ($ str) [abstract, protected]
Escapes special characters (usu.
quotes) using native driver function.
Parameters:
string $str The input string.
Returns:
string The escaped string.
Reimplemented in MSSQLPreparedStatement, MySQLPreparedStatement, MySQLiPreparedStatement, ODBCPreparedStatement, OCI8PreparedStatement, PgSQLPreparedStatement, and SQLitePreparedStatement.
Referenced by setArray(), setBlob(), setClob(), setDate(), setString(), and setTime().
PreparedStatementCommon::executeQuery ($ p1 = null, $ fetchmode = null)
Executes the SQL query in this PreparedStatement object and returns the resultset generated by the query.
We support two signatures for this method:
$stmt->executeQuery(ResultSet::FETCHMODE_NUM);
$stmt->executeQuery(array($param1, $param2), ResultSet::FETCHMODE_NUM);
Parameters:
mixed $p1 Either (array) Parameters that will be set using PreparedStatement::set() before query is executed or (int) fetchmode.
int $fetchmode The mode to use when fetching the results (e.g. ResultSet::FETCHMODE_NUM, ResultSet::FETCHMODE_ASSOC).
Returns:
ResultSet
Exceptions:
SQLException if a database access error occurs.
Reimplemented in MSSQLCallableStatement, MSSQLPreparedStatement, and OCI8PreparedStatement.
Definition at line 310 of file PreparedStatementCommon.php.
References $sql, and replaceParams().
  {
      $params = null;
    if ($fetchmode !== null) {
      $params = $p1;
    } elseif ($p1 !== null) {
      if (is_array($p1)) $params = $p1;
      else $fetchmode = $p1;
    }
        foreach ( (array) $params as $i=>$param ) {
      $this->set ( $i + 1, $param );
      unset ( $i, $param );
    }
    unset ( $params );
        $this->updateCount = null; // reset
        $sql = $this->replaceParams();
        if ($this->limit > 0 || $this->offset > 0) {
            $this->conn->applyLimit($sql, $this->offset, $this->limit);
        }
        $this->resultSet = $this->conn->executeQuery($sql, $fetchmode);
        return $this->resultSet;
    }
PreparedStatementCommon::executeUpdate ($ params = null)
Executes the SQL INSERT, UPDATE, or DELETE statement in this PreparedStatement object.
Parameters:
array $params Parameters that will be set using PreparedStatement::set() before query is executed.
Returns:
int Number of affected rows (or 0 for drivers that return nothing).
Exceptions:
SQLException if a database access error occurs.
Reimplemented in ODBCPreparedStatement, and OCI8PreparedStatement.
Definition at line 344 of file PreparedStatementCommon.php.
References $sql, and replaceParams().
    {
    foreach ( (array) $params as $i=>$param ) {
      $this->set ( $i + 1, $param );
      unset ( $i, $param );
    }
    unset ( $params );
        if($this->resultSet) $this->resultSet->close();
        $this->resultSet = null; // reset
        $sql = $this->replaceParams();
        $this->updateCount = $this->conn->executeUpdate($sql);
        return $this->updateCount;
    }
PreparedStatementCommon::getConnection ()
See also:
PreparedStatement::getConnection()
Definition at line 237 of file PreparedStatementCommon.php.
Referenced by MySQLiPreparedStatement::escape().
    {
        return $this->conn;
    }
PreparedStatementCommon::getLimit ()
See also:
PreparedStatement::getLimit()
Definition at line 187 of file PreparedStatementCommon.php.
    {
        return $this->limit;
    }
PreparedStatementCommon::getMoreResults ()
See also:
PreparedStatement::getMoreResults()
Reimplemented in MSSQLCallableStatement.
Definition at line 227 of file PreparedStatementCommon.php.
    {
        if ($this->resultSet) $this->resultSet->close();
        $this->resultSet = null;
        return false;
    }
PreparedStatementCommon::getOffset ()
See also:
PreparedStatement::getOffset()
Definition at line 203 of file PreparedStatementCommon.php.
    {
        return $this->offset;
    }
PreparedStatementCommon::getResource ()
Statement resources do not exist for emulated prepared statements, so this just returns null.
Returns:
null
Reimplemented in MSSQLCallableStatement.
Definition at line 247 of file PreparedStatementCommon.php.
Referenced by MySQLiPreparedStatement::escape().
    {
        return null;
    }
PreparedStatementCommon::getResultSet ()
See also:
PreparedStatement::getResultSet()
Definition at line 211 of file PreparedStatementCommon.php.
    {
        return $this->resultSet;
    }
PreparedStatementCommon::getUpdateCount ()
See also:
PreparedStatement::getUpdateCount()
Definition at line 219 of file PreparedStatementCommon.php.
    {
        return $this->updateCount;
    }
PreparedStatementCommon::parseQuery ($ sql) [protected]
Parse the SQL query for ? positions.
Parameters:
string $sql The query to process
Returns:
array Positions from the start of the string that ?'s appear at
Definition at line 131 of file PreparedStatementCommon.php.
References $positions, and $sql.
Referenced by __construct().
    {
        $positions = array();
  // match anything ? ' " or \ in $sql with an early out if we find nothing
        if ( preg_match_all ( '([\?]|[\']|[\"]|[\\\])', $sql, $matches, PREG_OFFSET_CAPTURE ) !== 0 ) {
                $matches = $matches['0'];
                $open = NULL;
    // go thru all our matches and see what we can find
                for ( $i = 0, $j = count ( $matches ); $i < $j; $i++ ) {
                        switch ( $matches[$i]['0'] ) {
        // if we already have an open " or ' then check if this is the end
        // to close it or not
                                case $open:
                                        $open = NULL;
                                        break;
        // we have a quote, set ourselves open
                                case '"':
                                case "'":
                                        $open = $matches[$i]['0'];
                                        break;
        // check if it is an escaped quote and skip if it is
                                case '\\':
                                        $next_match = $matches[$i+1]['0'];
                                        if ( $next_match === '"' || $next_match === "'" ) {
                                                $i++;
                                        }
                                        unset ( $next_match );
                                        break;
        // we found a ?, check we arent in an open "/' first and
        // add it to the position list if we arent
                                default:
                                        if ( $open === NULL ) {
                                                $positions[] = $matches[$i]['1'];
                                        }
                        }
                        unset ( $matches[$i] );
                }
                unset ( $open, $matches, $i, $j );
        }
  return $positions;
    }
PreparedStatementCommon::replaceParams () [protected]
Replaces placeholders with the specified parameter values in the SQL.
This is for emulated prepared statements.
Returns:
string New SQL statement with parameters replaced.
Exceptions:
SQLException - if param not bound.
Reimplemented in ODBCPreparedStatement.
Definition at line 267 of file PreparedStatementCommon.php.
References $sql.
Referenced by MSSQLPreparedStatement::executeQuery(), executeQuery(), and executeUpdate().
    {
      // early out if we still have the same query ready
      if ( $this->sql_cache_valid === true ) {
    return $this->sql_cache;
  }
        // Default behavior for this function is to behave in 'emulated' mode.
        $sql = '';
        $last_position = 0;
        for ($position = 0; $position < $this->positionsCount; $position++) {
            if (!isset($this->boundInVars[$position + 1])) {
                throw new SQLException('Replace params: undefined query param: ' . ($position + 1));
            }
            $current_position = $this->positions[$position];
            $sql .= substr($this->sql, $last_position, $current_position - $last_position);
            $sql .= $this->boundInVars[$position + 1];
            $last_position = $current_position + 1;
        }
        // append the rest of the query
        $sql .= substr($this->sql, $last_position);
  // just so we dont touch anything with a blob/clob
  if ( strlen ( $sql ) > 2048 ) {
    $this->sql_cache = $sql;
        $this->sql_cache_valid = true;
    return $this->sql_cache;
  } else {
    return $sql;
  }
    }
PreparedStatementCommon::set ($ paramIndex, $ value)
A generic set method.
You can use this if you don't want to concern yourself with the details. It involves slightly more overhead than the specific settesr, since it grabs the PHP type to determine which method makes most sense.
Parameters:
int $paramIndex
mixed $value
Returns:
void
Exceptions:
SQLException
Definition at line 378 of file PreparedStatementCommon.php.
References setBlob(), setClob(), and setTimestamp().
    {
        $type = gettype($value);
        if ($type == "object") {
            if (is_a($value, 'Blob')) {
                $this->setBlob($paramIndex, $value);
            } elseif (is_a($value, 'Clob')) {
                $this->setClob($paramIndex, $value);
            } elseif (is_a($value, 'Date')) {
                 // can't be sure if the column type is a DATE, TIME, or TIMESTAMP column
                 // we'll just use TIMESTAMP by default; hopefully DB won't complain (if
                 // it does, then this method just shouldn't be used).
                 $this->setTimestamp($paramIndex, $value);
            } else {
                throw new SQLException("Unsupported object type passed to set(): " . get_class($value));
            }
        } else {
      switch ( $type ) {
        case 'integer':
      $type = 'int';
      break;
    case 'double':
      $type = 'float';
      break;
      }
    $setter = 'set' . ucfirst($type); // PHP types are case-insensitive, but we'll do this in case that change
    if ( method_exists ( $this, $setter ) ) {
      $this->$setter($paramIndex, $value);
    } else {
      throw new SQLException ( "Unsupported datatype passed to set(): " . $type );
    }
        }
    }
PreparedStatementCommon::setArray ($ paramIndex, $ value)
Sets an array.
Unless a driver-specific method is used, this means simply serializing the passed parameter and storing it as a string.
Parameters:
int $paramIndex
array $value
Returns:
void
Reimplemented in PgSQLPreparedStatement.
Definition at line 420 of file PreparedStatementCommon.php.
References escape(), and setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $this->boundInVars[$paramIndex] = "'" . $this->escape(serialize($value)) . "'";
        }
    }
PreparedStatementCommon::setBlob ($ paramIndex, $ blob)
See also:
PreparedStatement::setBlob()
Reimplemented in MSSQLPreparedStatement, ODBCPreparedStatement, OCI8PreparedStatement, PgSQLPreparedStatement, and SQLitePreparedStatement.
Definition at line 451 of file PreparedStatementCommon.php.
References escape(), and setNull().
Referenced by set().
    {
      $this->sql_cache_valid = false;
        if ($blob === null) {
            $this->setNull($paramIndex);
        } else {
            // they took magic __toString() out of PHP5.0.0; this sucks
            if (is_object($blob)) {
              $this->boundInVars[$paramIndex] = "'" . $this->escape($blob->__toString()) . "'";
            } else {
              $this->boundInVars[$paramIndex] = "'" . $this->escape($blob) . "'";
      }
        }
    }
PreparedStatementCommon::setBoolean ($ paramIndex, $ value)
Sets a boolean value.
Default behavior is true = 1, false = 0.
Parameters:
int $paramIndex
boolean $value
Returns:
void
Reimplemented in PgSQLPreparedStatement.
Definition at line 437 of file PreparedStatementCommon.php.
References setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $this->boundInVars[$paramIndex] = (int) $value;
        }
    }
PreparedStatementCommon::setClob ($ paramIndex, $ clob)
See also:
PreparedStatement::setClob()
Reimplemented in ODBCPreparedStatement, and OCI8PreparedStatement.
Definition at line 469 of file PreparedStatementCommon.php.
References escape(), and setNull().
Referenced by set().
    {
      $this->sql_cache_valid = false;
        if ($clob === null) {
            $this->setNull($paramIndex);
        } else {
            // they took magic __toString() out of PHP5.0.0; this sucks
            if (is_object($clob)) {
              $this->boundInVars[$paramIndex] = "'" . $this->escape($clob->__toString()) . "'";
            } else {
              $this->boundInVars[$paramIndex] = "'" . $this->escape($clob) . "'";
      }
        }
    }
PreparedStatementCommon::setDate ($ paramIndex, $ value)
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented in OCI8PreparedStatement.
Definition at line 489 of file PreparedStatementCommon.php.
References escape(), and setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date("Y-m-d", $value);
            elseif (is_object($value)) $value = date("Y-m-d", $value->getTime());
            $this->boundInVars[$paramIndex] = "'" . $this->escape($value) . "'";
        }
    }
PreparedStatementCommon::setDecimal ($ paramIndex, $ value)
Parameters:
int $paramIndex
double $value
Returns:
void
Definition at line 506 of file PreparedStatementCommon.php.
References setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $this->boundInVars[$paramIndex] = (float) $value;
        }
    }
PreparedStatementCommon::setDouble ($ paramIndex, $ value)
Parameters:
int $paramIndex
double $value
Returns:
void
Definition at line 521 of file PreparedStatementCommon.php.
References setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $this->boundInVars[$paramIndex] = (double) $value;
        }
    }
PreparedStatementCommon::setFloat ($ paramIndex, $ value)
Parameters:
int $paramIndex
float $value
Returns:
void
Definition at line 536 of file PreparedStatementCommon.php.
References setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $this->boundInVars[$paramIndex] = (float) $value;
        }
    }
PreparedStatementCommon::setInt ($ paramIndex, $ value)
Parameters:
int $paramIndex
int $value
Returns:
void
Definition at line 551 of file PreparedStatementCommon.php.
References setNull().
Referenced by setInteger().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            $this->boundInVars[$paramIndex] = (int) $value;
        }
    }
PreparedStatementCommon::setInteger ($ paramIndex, $ value)
Alias for setInt().
Parameters:
int $paramIndex
int $value
Definition at line 566 of file PreparedStatementCommon.php.
References setInt().
    {
      $this->sql_cache_valid = false;
        $this->setInt($paramIndex, $value);
    }
PreparedStatementCommon::setLimit ($ v)
See also:
PreparedStatement::setLimit()
Definition at line 179 of file PreparedStatementCommon.php.
    {
        $this->limit = (int) $v;
    }
PreparedStatementCommon::setNull ($ paramIndex)
Parameters:
int $paramIndex
Returns:
void
Reimplemented in MSSQLCallableStatement, ODBCPreparedStatement, and OCI8PreparedStatement.
Definition at line 576 of file PreparedStatementCommon.php.
Referenced by PgSQLPreparedStatement::setArray(), setArray(), SQLitePreparedStatement::setBlob(), PgSQLPreparedStatement::setBlob(), MSSQLPreparedStatement::setBlob(), setBlob(), PgSQLPreparedStatement::setBoolean(), setBoolean(), setClob(), setDate(), setDecimal(), setDouble(), setFloat(), setInt(), setString(), PgSQLPreparedStatement::setTime(), setTime(), PgSQLPreparedStatement::setTimestamp(), and setTimestamp().
    {
      $this->sql_cache_valid = false;
        $this->boundInVars[$paramIndex] = 'NULL';
    }
PreparedStatementCommon::setOffset ($ v)
See also:
PreparedStatement::setOffset()
Definition at line 195 of file PreparedStatementCommon.php.
    {
        $this->offset = (int) $v;
    }
PreparedStatementCommon::setString ($ paramIndex, $ value)
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented in OCI8PreparedStatement.
Definition at line 587 of file PreparedStatementCommon.php.
References escape(), and setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            // it's ok to have a fatal error here, IMO, if object doesn't have
            // __toString() and is being passed to this method.
      if ( is_object ( $value ) ) {
              $this->boundInVars[$paramIndex] = "'" . $this->escape($value->__toString()) . "'";
      } else {
              $this->boundInVars[$paramIndex] = "'" . $this->escape((string)$value) . "'";
      }
        }
    }
PreparedStatementCommon::setTime ($ paramIndex, $ value)
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented in PgSQLPreparedStatement.
Definition at line 608 of file PreparedStatementCommon.php.
References escape(), and setNull().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if ( is_numeric ( $value ) ) {
          $value = date ('H:i:s', $value );
        } elseif ( is_object ( $value ) ) {
          $value = date ('H:i:s', $value->getTime ( ) );
        }
            $this->boundInVars [ $paramIndex ] = "'" . $this->escape ( $value ) . "'";
        }
    }
PreparedStatementCommon::setTimestamp ($ paramIndex, $ value)
Parameters:
int $paramIndex
string $value
Returns:
void
Reimplemented in OCI8PreparedStatement, and PgSQLPreparedStatement.
Definition at line 628 of file PreparedStatementCommon.php.
References setNull().
Referenced by set().
    {
      $this->sql_cache_valid = false;
        if ($value === null) {
            $this->setNull($paramIndex);
        } else {
            if (is_numeric($value)) $value = date('Y-m-d H:i:s', $value);
            elseif (is_object($value)) $value = date('Y-m-d H:i:s', $value->getTime());
            $this->boundInVars[$paramIndex] = "'".$this->escape($value)."'";
        }
    }
Member Data Documentation
PreparedStatementCommon::$boundInVars = array() [protected]
Definition at line 93 of file PreparedStatementCommon.php.
PreparedStatementCommon::$conn [protected]
Definition at line 40 of file PreparedStatementCommon.php.
PreparedStatementCommon::$limit = 0 [protected]
Definition at line 46 of file PreparedStatementCommon.php.
PreparedStatementCommon::$offset = 0 [protected]
Definition at line 53 of file PreparedStatementCommon.php.
PreparedStatementCommon::$positions [protected]
Definition at line 80 of file PreparedStatementCommon.php.
Referenced by parseQuery().
PreparedStatementCommon::$positionsCount [protected]
Definition at line 87 of file PreparedStatementCommon.php.
PreparedStatementCommon::$resultSet [protected]
Definition at line 99 of file PreparedStatementCommon.php.
PreparedStatementCommon::$sql [protected]
Definition at line 59 of file PreparedStatementCommon.php.
Referenced by __construct(), ODBCPreparedStatement::_execute(), OCI8PreparedStatement::executeQuery(), ODBCPreparedStatement::executeQuery(), MSSQLPreparedStatement::executeQuery(), executeQuery(), ODBCPreparedStatement::executeUpdate(), executeUpdate(), parseQuery(), replaceParams(), and OCI8PreparedStatement::sqlToOracleBindVars().
PreparedStatementCommon::$sql_cache [protected]
Definition at line 68 of file PreparedStatementCommon.php.
PreparedStatementCommon::$sql_cache_valid = false [protected]
Definition at line 74 of file PreparedStatementCommon.php.
PreparedStatementCommon::$updateCount [protected]
Definition at line 105 of file PreparedStatementCommon.php.
The documentation for this class was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/common/PreparedStatementCommon.php