fareofficelib: Connection Interface Reference
Connection Interface Reference
Public Member Functions
connect ($dsn, $flags=false)
Connect to a database and log in as the specified user.
getResource ()
Get the PHP native resource for the database connection/link.
getFlags ()
Get any flags that were passed to connection.
getDSN ()
Get the DSN array used by connect() method to connect to database.
getDatabaseInfo ()
Gets a DatabaseInfo class for the current database.
getIdGenerator ()
Loads and returns an IdGenerator object for current RDBMS.
prepareStatement ($sql)
Prepares a query for multiple execution with execute().
createStatement ()
Creates a new empty Statement.
applyLimit (&$sql, $offset, $limit)
If RDBMS supports native LIMIT/OFFSET then query SQL is modified so that no emulation is performed in ResultSet.
executeQuery ($sql, $fetchmode=null)
Executes the SQL query in this PreparedStatement object and returns the resultset.
executeUpdate ($sql)
Executes the SQL INSERT, UPDATE, or DELETE statement.
prepareCall ($sql)
Creates a CallableStatement object for calling database stored procedures.
close ()
Free the db resources.
isConnected ()
Returns false if connection is closed.
getAutoCommit ()
Get auto-commit status.
setAutoCommit ($bit)
Enable/disable automatic commits.
begin ()
Begins a transaction (if supported).
commit ()
Commits statements in a transaction.
rollback ()
Rollback changes in a transaction.
getUpdateCount ()
Gets the number of rows affected by the data manipulation query.
Detailed Description
Definition at line 35 of file Connection.php.
Member Function Documentation
Connection::applyLimit (&$ sql, $ offset, $ limit)
If RDBMS supports native LIMIT/OFFSET then query SQL is modified so that no emulation is performed in ResultSet.
Parameters:
string &$sql The query that will be modified.
int $offset
int $limit
Returns:
void
Exceptions:
SQLException - if unable to modify query for any reason.
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::begin ()
Begins a transaction (if supported).
Implemented in DebugConnection.
Connection::close ()
Free the db resources.
Returns:
void
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::commit ()
Commits statements in a transaction.
Implemented in DebugConnection.
Connection::connect ($ dsn, $ flags = false)
Connect to a database and log in as the specified user.
Parameters:
array $dsn The PEAR-style data source hash.
int $flags (optional) Flags for connection (e.g. Creole::PERSISTENT). These flags may apply to any of the driver classes.
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::createStatement ()
Creates a new empty Statement.
Returns:
Statement
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::executeQuery ($ sql, $ fetchmode = null)
Executes the SQL query in this PreparedStatement object and returns the resultset.
Parameters:
string $sql The SQL statement.
int $fetchmode
Returns:
object ResultSet
Exceptions:
SQLException if a database access error occurs.
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::executeUpdate ($ sql)
Executes the SQL INSERT, UPDATE, or DELETE statement.
Parameters:
string $sql This method may optionally be called with the SQL statement.
Returns:
int Number of affected rows (or 0 for drivers that return nothing).
Exceptions:
SQLException if a database access error occurs.
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::getAutoCommit ()
Get auto-commit status.
Returns:
boolean
Implemented in DebugConnection.
Connection::getDatabaseInfo ()
Gets a DatabaseInfo class for the current database.
This is not modeled on the JDBC MetaData class, but provides a possibly more useful metadata system. All the same, there may eventually be a getMetaData() which returns a class that behaves like JDBC's DatabaseMetaData.
Returns:
DatabaseInfo
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::getDSN ()
Get the DSN array used by connect() method to connect to database.
See also:
connect()
Returns:
array
Implemented in DebugConnection.
Referenced by DatabaseInfo::__construct(), and OCI8DatabaseInfo::__construct().
Connection::getFlags ()
Get any flags that were passed to connection.
Returns:
int
Implemented in DebugConnection.
Referenced by ResultSetCommon::__construct().
Connection::getIdGenerator ()
Loads and returns an IdGenerator object for current RDBMS.
Returns:
IdGenerator
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::getResource ()
Get the PHP native resource for the database connection/link.
Returns:
resource
Implemented in DebugConnection.
Referenced by DatabaseInfo::__construct().
Connection::getUpdateCount ()
Gets the number of rows affected by the data manipulation query.
Returns:
int Number of rows affected by the last query.
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::isConnected ()
Returns false if connection is closed.
Returns:
boolean
Implemented in DebugConnection.
Connection::prepareCall ($ sql)
Creates a CallableStatement object for calling database stored procedures.
Parameters:
string $sql
Returns:
CallableStatement
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::prepareStatement ($ sql)
Prepares a query for multiple execution with execute().
With some database backends, this is emulated. prepare() requires a generic query as string like "INSERT INTO numbers VALUES(?,?,?)". The ? are placeholders.
IMPORTANT: All occurrences of the placeholder (?) will be assumed to be a parameter. Therefore be sure not to have ? anywhere else in the query.
So, ... DO NOT MIX WILDCARDS WITH ALREADY-PREPARED QUERIES
INCORRECT: SELECT * FROM mytable WHERE id = ? AND title = 'Where are you?' and body LIKE ?
CORRECT: SELECT * FROM mytable WHERE id = ? AND title = ? and body LIKE ?
Parameters:
string $sql The query to prepare.
Returns:
PreparedStatement
Exceptions:
SQLException
See also:
PreparedStatement::execute()
Implemented in DebugConnection, MSSQLConnection, MySQLConnection, MySQLiConnection, ODBCConnection, OCI8Connection, PgSQLConnection, and SQLiteConnection.
Connection::rollback ()
Rollback changes in a transaction.
Implemented in DebugConnection.
Connection::setAutoCommit ($ bit)
Enable/disable automatic commits.
Pushes SQLWarning onto $warnings stack if the autocommit value is being changed mid-transaction. This function is overridden by driver classes so that they can perform the necessary begin/end transaction SQL.
If auto-commit is being set to TRUE, then the current transaction will be committed immediately.
Parameters:
boolean $bit New value for auto commit.
Returns:
void
Implemented in DebugConnection.
The documentation for this interface was generated from the following file:
Static/PhpInclude/FareOfficeLib/3dPart/creole/Connection.php