fareofficelib: Static/PhpInclude/FareOfficeLib/General/String.php File Reference
Static/PhpInclude/FareOfficeLib/General/String.php File Reference
Includes string manipulating functions.
Functions
emptyString (&$value)
Returns FALSE if var has a non-empty value.
Detailed Description
Includes string manipulating functions.
Author:
Daniel Lindh <daniel@fareoffice.com>
Definition in file String.php.
Function Documentation
emptyString (&$ value)
Returns FALSE if var has a non-empty value.
The following things are considered to be empty:
"" (an empty string) NULL array() (an empty array) var $var; (a variable declared, but without a value in a class)
Definition at line 20 of file String.php.
Referenced by escN(), escS(), and getVarContent().
{
  if (empty($value) && $value != '0')
    return true;
  return false;
}